// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_COMPONENTS_JSON_PARSER_UNESCAPED
#define QOR_PP_H_COMPONENTS_JSON_PARSER_UNESCAPED

#include "../tokens.h"

namespace qor { namespace components { namespace parser { namespace json {

    class qor_pp_module_interface(QOR_JSON) unescaped : public components::parser::AnyOneOf
    {        
    public: unescaped(Parser* parser) :
                AnyOneOf(parser,
                    new_ref<OneOfARange>(parser, (byte)0x20, (byte)0x21, static_cast<uint64_t>(eToken::Lexical)),
                    new_ref<AnyOneOf>(parser,
                        new_ref<OneOfARange>(parser, (byte)0x23, (byte)0x5B, static_cast<uint64_t>(eToken::Lexical)),
                        new_ref<OneOfARange>(parser, (byte)0x5D, (byte)(0xFF)/*0x10FFFF*/, static_cast<uint64_t>(eToken::Lexical)),
                        static_cast<uint64_t>(eToken::Lexical)
                    ),
                    static_cast<uint64_t>(jsonToken::unescaped)){ }

        virtual ~unescaped() = default;
        virtual void Prepare()
        {
            log::debug("Looking for an unescaped character...");
        }

        void Emit()
        {
            log::debug("Emitting an unescaped character: ");
        }

        void Fail()
        {
            log::debug("...Didn't find an unescaped character.");
        }
    };

}}}}//qor::components::parser::json

#endif//QOR_PP_H_COMPONENTS_JSON_PARSER_UNESCAPED