// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_FRAMEWORK_DESKTOPUI_LAYOUT_FLEXNODE
#define QOR_PP_H_FRAMEWORK_DESKTOPUI_LAYOUT_FLEXNODE

#include "../node.h"
#include "vbox.h"
#include "hbox.h"

namespace qor{ namespace ui{ namespace layout { 

	namespace 
	{
		using FlexFunction = void (*)(Requirement&);

		void function_flex_grow(Requirement& r) 
		{
			r.flex_grow_x = 1;
			r.flex_grow_y = 1;
		}

		void function_xflex_grow(Requirement& r) 
		{
			r.flex_grow_x = 1;
		}

		void function_yflex_grow(Requirement& r) 
		{
			r.flex_grow_y = 1;
		}

		void function_flex_shrink(Requirement& r) 
		{
			r.flex_shrink_x = 1;
			r.flex_shrink_y = 1;
		}

		void function_xflex_shrink(Requirement& r) 
		{
			r.flex_shrink_x = 1;
		}

		void function_yflex_shrink(Requirement& r) 
		{
			r.flex_shrink_y = 1;
		}

		void function_flex(Requirement& r) 
		{
			r.flex_grow_x = 1;
			r.flex_grow_y = 1;
			r.flex_shrink_x = 1;
			r.flex_shrink_y = 1;
		}

		void function_xflex(Requirement& r) 
		{
			r.flex_grow_x = 1;
			r.flex_shrink_x = 1;
		}

		void function_yflex(Requirement& r) 
		{
			r.flex_grow_y = 1;
			r.flex_shrink_y = 1;
		}

		void function_not_flex(Requirement& r) 
		{
			r.flex_grow_x = 0;
			r.flex_grow_y = 0;
			r.flex_shrink_x = 0;
			r.flex_shrink_y = 0;
		}

		class Flex : public Node 
		{
		public:
			explicit Flex(FlexFunction f) : f_(f) {}

			Flex(FlexFunction f, Element child) : Node(detail::unpack(std::move(child))), f_(f) {}

			void ComputeRequirement() override 
			{
				requirement_.min_x = 0;
				requirement_.min_y = 0;
				if (!children_.empty()) 
				{
					children_[0]->ComputeRequirement();
					requirement_ = children_[0]->requirement();
				}
				f_(requirement_);
			}

			void SetBox(Box box) override {
				Node::SetBox(box);
				if (children_.empty()) 
				{
					return;
				}
				children_[0]->SetBox(box);
			}

			FlexFunction f_;
		};

	}//

}}}//qor::ui::layout

#endif//QOR_PP_H_FRAMEWORK_DESKTOPUI_LAYOUT_DBOX

