// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include "src/qor/error/error.h"

#include "keyboardlistener.h"
#include "../keyboard.h"

namespace qor{ namespace platform { namespace nslinux{ namespace wl{
    
    KeyboardListener::KeyboardListener()
    {
        wl_keyboard_listener::keymap = [](void* data, wl_keyboard* wl_keyboard, uint32_t format, int32_t fd, uint32_t size)
        {
            Keyboard* keyboard = Keyboard::KeyboardFrom(wl_keyboard);
            if(keyboard)
            {
                keyboard->OnKeymap(data, format, fd, size);
            }
        };
        wl_keyboard_listener::enter = [](void* data, wl_keyboard* wl_keyboard, uint32_t serial, wl_surface* surface, wl_array* keys)
        {
            Keyboard* keyboard = Keyboard::KeyboardFrom(wl_keyboard);
            if(keyboard)
            {
                keyboard->OnEnter(data, serial, surface, keys);
            }
        };
        wl_keyboard_listener::leave = [](void* data, wl_keyboard* wl_keyboard, uint32_t serial, wl_surface* surface)
        {
            Keyboard* keyboard = Keyboard::KeyboardFrom(wl_keyboard);
            if(keyboard)
            {
                keyboard->OnLeave(data, serial, surface);
            }
        };
        wl_keyboard_listener::key = [](void* data, wl_keyboard* wl_keyboard, uint32_t serial, uint32_t time, uint32_t key, uint32_t state)
        {
            Keyboard* keyboard = Keyboard::KeyboardFrom(wl_keyboard);
            if(keyboard)
            {
                keyboard->OnKey(data, serial, time, key, state);
            }
        };
        wl_keyboard_listener::modifiers = [](void* data, wl_keyboard* wl_keyboard, uint32_t serial, uint32_t mods_depressed, uint32_t mods_latched, uint32_t mods_locked, uint32_t group)
        {
            Keyboard* keyboard = Keyboard::KeyboardFrom(wl_keyboard);
            if(keyboard)
            {
                keyboard->OnModifiers(data, serial, mods_depressed, mods_latched, mods_locked, group);
            }
        };           
    }
}}}}//qor::platform::nslinux::wl
