// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_LINUX_WAYLAND_POINTER_LISTENER
#define QOR_PP_H_LINUX_WAYLAND_POINTER_LISTENER

#include <stdint.h>
#include <wayland-client-core.h>
#include <wayland-client-protocol.h>

namespace qor{ namespace platform { namespace nslinux{ namespace wl{

    template<uint32_t ver = 1>
    struct qor_pp_module_interface(QOR_LINWAYLAND) PointerListener : public wl_pointer_listener
    {
        PointerListener()
        {
            this->enter = [](void* data, wl_pointer* wl_pointer, uint32_t serial, wl_surface* surface, wl_fixed_t sx, wl_fixed_t sy)
            {
                Pointer* pointer = Pointer::PointerFrom(wl_pointer);
                if(pointer)
                {
                    pointer->OnEnter(data, serial, surface, sx, sy);
                }
            };
            this->leave = [](void* data, wl_pointer* wl_pointer, uint32_t serial, wl_surface* surface)
            {
                Pointer* pointer = Pointer::PointerFrom(wl_pointer);
                if(pointer)
                {
                    pointer->OnLeave(data, serial, surface);
                }
            };
            this->motion = [](void* data, wl_pointer* wl_pointer, uint32_t time, wl_fixed_t sx, wl_fixed_t sy)
            {
                Pointer* pointer = Pointer::PointerFrom(wl_pointer);
                if(pointer)
                {
                    pointer->OnMotion(data, time, sx, sy);
                }
            };
            this->button = [](void* data, wl_pointer* wl_pointer, uint32_t serial, uint32_t time, uint32_t button, uint32_t state)
            {
                Pointer* pointer = Pointer::PointerFrom(wl_pointer);
                if(pointer)
                {
                    pointer->OnButton(data, serial, time, button, state);
                }
            };
            this->axis = [](void* data, wl_pointer* wl_pointer, uint32_t time, uint32_t axis, wl_fixed_t value)
            {
                Pointer* pointer = Pointer::PointerFrom(wl_pointer);
                if(pointer)
                {
                    pointer->OnAxis(data, time, axis, value);
                }
            };
        }
    };

    template<>
    struct qor_pp_module_interface(QOR_LINWAYLAND) PointerListener<5> : public PointerListener<1>
    {
        PointerListener()
        {
            this->frame = [](void* data, wl_pointer* wl_pointer)
            {
                Pointer* pointer = Pointer::PointerFrom(wl_pointer);
                if(pointer)
                {
                    pointer->OnFrame(data);
                }
            };
            this->axis_discrete = [](void* data, wl_pointer* wl_pointer, uint32_t axis, int32_t discrete)
            {
                Pointer* pointer = Pointer::PointerFrom(wl_pointer);
                if(pointer)
                {
                    pointer->OnAxisDiscrete(data, axis, discrete);
                }
            };
            this->axis_source = [](void* data, wl_pointer* wl_pointer, uint32_t axisSource)
            {
                Pointer* pointer = Pointer::PointerFrom(wl_pointer);
                if(pointer)
                {
                    pointer->OnAxisSource(data, axisSource);
                }
            };
            this->axis_stop = [](void* data, wl_pointer* wl_pointer, uint32_t time, uint32_t axis)
            {
                Pointer* pointer = Pointer::PointerFrom(wl_pointer);
                if(pointer)
                {
                    pointer->OnAxisStop(data, time, axis);
                }
            };
        }
    };

}}}}//qor::platform::nslinux::wl

#endif//QOR_PP_H_LINUX_WAYLAND_POINTER_LISTENER