// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "toplevel.h"
#include "../messages.h"
#include "../../controllers/windowcontroller.h"

#include "src/platform/os/windows/api_layer/user/user32.h"

namespace qor{ namespace platform { namespace win{ namespace gui{ namespace view{
    
    long long TopLevelLifetimeHandler::OnDestroy(Window& window, unsigned int uMsg, unsigned long long wParam, long long lParam)
    {
        qor::win::api::User32::PostQuitMessage(EXIT_SUCCESS);//The app exits when this window is destroyed.
        return 0;
    }

    TopLevelWindowHandler::TopLevelWindowHandler()
    {        
        m_lifetime = new_ref<TopLevelLifetimeHandler>();
    }

    void TopLevelWindowHandler::SetCommandCallback(ref_of<WindowController>::type ctrl, unsigned short notification, cmd_callback cb)
    {
        unsigned short id = ctrl->GetId();
        Command cmd{ ctrl, cb};
        unsigned long key = MakeKey(id, notification);
        auto it = m_commandMap.find(key);
        if( it == m_commandMap.end())
        {
            m_commandMap.insert(std::make_pair(key, cmd));
        }
        else
        {
            it->second = cmd;
        }
    }

    bool TopLevelWindowHandler::ProcessMessage(Window& window, long long& lResult, unsigned int msg, unsigned long long wParam, long long lParam)
    {
        if(ProcessHook(window, lResult, msg, wParam, lParam))
        {
            return true;
        }

        switch (msg)
        {
            case wmEnterIdle:
            {                
                Window w(PrimitiveHandle((void*)(lParam)));
                if(OnEnterIdle(static_cast< unsigned short>(wParam), w))
                {
                    lResult = 0;
                }
                return true;
            }
            case wmSysCommand:
            {                
                unsigned short wYPos = 0;
                unsigned short wXPos = LoWord(lParam);
                unsigned short wData = HiWord(lParam);
                bool bAcceleratorUsed = (wData == -1) ? true : false;
                bool bMnemonic = (wData == 0) ? true : false;
                if (!bAcceleratorUsed && !bMnemonic)
                {
                    wYPos = wData;
                }
                unsigned short code = wParam & 0XFFF0;
                if(OnSysCommand(window, code, wYPos, wXPos, bAcceleratorUsed, bMnemonic, wParam, lParam))
                {
                    lResult = 0;
                }
                return true;
            }
            case wmDropFiles:
            {
                void* hDropInfo = reinterpret_cast<void*>(wParam);
                OnDropFiles(hDropInfo);
                lResult = 0;
                return true;
            }
            case wmQueryEndSession:
            {
                bool bLoggingOff = (lParam & EndSessionLogOff) > 0 ? true : false;
                lResult = OnQueryEndSession(bLoggingOff) ? true : false;
                return true;
            }
            case wmEndSession:
            {
                bool bEnd = wParam ? true : false;
                bool bLoggingOff = (lParam & EndSessionLogOff) > 0 ? true : false;
                OnEndSession(bEnd, bLoggingOff);
                lResult = 0;
                return true;
            }
            case wmQueryNewPalette:
            {
                lResult = OnQueryNewPalette() ? true : false;
                window.DefWindowProcT(msg, wParam, lParam);
                return true;
            }
            case wmPaletteChanged:
            {
                window.DefWindowProcT(msg, wParam, lParam);
                Window w(PrimitiveHandle((void*)(wParam)));
                OnPaletteChanged(w);
                return true;
            }
            case wmCommand:
            {
                unsigned short wNotify = HiWord(wParam);
                unsigned short wID = LoWord(wParam);
                if(OnCommand(window, wNotify, wID, lParam))
                {
                    lResult = 0;
                }
                return true;
            }
            case wmActivateApp:
            {
                bool bActivate = wParam ? true : false;
                unsigned long dwThreadID = static_cast< unsigned long >(lParam);
                if(OnActivateApp(bActivate, dwThreadID))
                {
                    lResult = 0;
                }                
                return true;
            }
            case wmDeviceChange:
            {
                lResult = window.DefWindowProcT(msg, wParam, lParam);
                return true;
            }
            case wmGetTitleBarInfoEx:
            {
                if(OnGetTitleBarInfo(reinterpret_cast<TitleBarInfoEx*>(lParam)))
                {
                    lResult = 0;
                }
                return true;
            }
        }
        return InteractiveWindowHandler::ProcessMessage(window, lResult, msg, wParam, lParam);
    }

    bool TopLevelWindowHandler::OnEnterIdle(unsigned short wWhy, Window& who)
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommand(Window& window, unsigned short code, unsigned short wYPos, unsigned short wXPos, bool bAcceleratorUsed, bool bMnemonic, unsigned long long wParam, long long lParam)
    {
        switch(code)
        {
            case scClose:
            {
                return OnSysCommandClose(window, wParam, lParam);
            }
            case scContextHelp:
            {
                return OnSysCommandContextHelp();//Changes the cursor to a question mark with a pointer. If the user then clicks a control in the dialog box, the control receives a WM_HELP message.
            }
            case scDefault:
            {
                return OnSysCommandDefault();//Selects the default item; the user double-clicked the window menu.
            }
            case scHotKey:
            {
                return OnSysCommandHotKey();//Activates the window associated with the application-specified hot key. The lParam parameter identifies the window to activate.
            }
            case scHScroll:
            {
                return OnSysCommandHScroll();//Scrolls horizontally.
            }
            case scVScroll:
            {
                return OnSysCommandVScroll();//Scrolls vertically.
            }
            case scKeyMenu:
            {
                return OnSysCommandKeyMenu();//Retrieves the window menu as a result of a keystroke.
            }
            case scMaximize:
            {
                return OnSysCommandMaximize();//Maximizes the window.
            }
            case scMinimize:
            {
                return OnSysCommandMinimize();//Minimizes the window.
            }
            case scMonitorPower:
            {
                return OnSysCommandMonitorPower();
                /*Sets the state of the display. This command supports devices that have power-saving features, such as a battery-powered personal computer.
                The lParam parameter can have the following values:
                -1 (the display is powering on)
                1 (the display is going to low power)
                2 (the display is being shut off)
                */
            }
            case scMouseMenu:
            {
                return OnSysCommandMouseMenu();//Retrieves the window menu as a result of a mouse click.
            }
            case scMove:
            {
                return OnSysCommandMove();//Moves the window.
            }
            case scNextWindow:
            {
                return OnSysCommandNextWindow();//Moves to the next window.
            }
            case scPrevWindow:
            {
                return OnSysCommandPrevWindow();//Moves to the previous window.
            }
            case scRestore:
            {
                return OnSysCommandRestore();//Restores the window to its normal position and size.
            }
            case scScreenSave:
            {
                return OnSysCommandScreenSaver();//Executes the screen saver application specified in the [boot] section of the System.ini file.
            }
            case scSize:
            {
                return OnSysCommandSize();//Sizes the window.
            }
            case scTaskList:
            {
                return OnSysCommandTaskList();//Activates the Start menu.
            }
        }
        return false;
    }

    void TopLevelWindowHandler::OnDropFiles(void* hDropInfo)
    {
    }

    bool TopLevelWindowHandler::OnQueryEndSession(bool bLoggingOff)
    {
        return true;
    }
    
    void TopLevelWindowHandler::OnEndSession(bool bEnd, bool bLoggingOff)
    {
    }

    bool TopLevelWindowHandler::OnQueryNewPalette()
    {
        return false;
    }

    void TopLevelWindowHandler::OnPaletteChanged(Window& changeSource)
    {
    }
    
    bool TopLevelWindowHandler::OnCommand(Window& window, unsigned short notification, unsigned short id, long long param)
    {        
        auto it = m_commandMap.find(MakeKey(id, notification));
        if(it != m_commandMap.end())
        {
            return it->second.cb(window, it->second.ctrl);
        }
        return false;
    }

    bool TopLevelWindowHandler::OnActivateApp(bool bActivate, unsigned long threadId)
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandClose(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmSysCommand, wParam, lParam);
        return true;
    }

    bool TopLevelWindowHandler::OnSysCommandContextHelp()
    {
        return false;
    }
    
    bool TopLevelWindowHandler::OnSysCommandDefault()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandHotKey()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandHScroll()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandVScroll()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandKeyMenu()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandMaximize()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandMinimize()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandMonitorPower()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandMouseMenu()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandMove()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandNextWindow()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandPrevWindow()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandRestore()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandScreenSaver()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandSize()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnSysCommandTaskList()
    {
        return false;
    }

    bool TopLevelWindowHandler::OnGetTitleBarInfo(TitleBarInfoEx* titleBarInfo)
    {
        return false;
    }
    
}}}}}//qor::platform::win::gui::view
