// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_OS_WINDOWS_FRAMEWORK_ASYNCIOSERVICE_IOCP_RECVFROMOP
#define QOR_PP_H_OS_WINDOWS_FRAMEWORK_ASYNCIOSERVICE_IOCP_RECVFROMOP

#include <system_error>
#include <coroutine>
#include <tuple>
#include "overlappedoperationcancellable.h"
#include "overlappedoperation.h"
#include "src/framework/task/cancellation/cancellationtoken.h"
#include "src/platform/network/socket.h"
#include "src/platform/network/ipendpoint.h"

namespace qor { namespace nswindows { namespace framework {

	class socket_recv_from_operation_impl
	{
	public:

		socket_recv_from_operation_impl( network::Socket& socket, void* buffer, std::size_t byteCount) noexcept
			: m_socket(socket)
			, m_buffer(buffer, byteCount)
		{
		}

		bool try_start(win32_overlapped_operation_base& operation) noexcept;
		void cancel(win32_overlapped_operation_base& operation) noexcept;
		std::tuple<std::size_t, network::IPEndpoint> get_result(win32_overlapped_operation_base& operation);

	private:

		network::Socket& m_socket;
		wsabuf m_buffer;

		static constexpr std::size_t sockaddrStorageAlignment = 4;

		// Storage suitable for either SOCKADDR_IN or SOCKADDR_IN6
		alignas(sockaddrStorageAlignment) std::uint8_t m_sourceSockaddrStorage[28];
		int m_sourceSockaddrLength;

	};

	class socket_recv_from_operation
		: public win32_overlapped_operation<socket_recv_from_operation>
	{
		friend class win32_overlapped_operation<socket_recv_from_operation>;

	public:

		socket_recv_from_operation(
			network::Socket& socket,
			void* buffer,
			std::size_t byteCount) noexcept
			: m_impl(socket, buffer, byteCount)
		{
		}

	private:

		bool try_start() noexcept { return m_impl.try_start(*this); }
		decltype(auto) get_result() { return m_impl.get_result(*this); }

		socket_recv_from_operation_impl m_impl;

	};

	class socket_recv_from_operation_cancellable : public win32_overlapped_operation_cancellable<socket_recv_from_operation_cancellable>
	{
		friend class win32_overlapped_operation_cancellable<socket_recv_from_operation_cancellable>;

	public:

		socket_recv_from_operation_cancellable(
			network::Socket& socket,
			void* buffer,
			std::size_t byteCount,
			CancellationToken&& ct) noexcept
			: win32_overlapped_operation_cancellable<socket_recv_from_operation_cancellable>(std::move(ct))
			, m_impl(socket, buffer, byteCount)
		{
		}

	private:

		bool try_start() noexcept { return m_impl.try_start(*this); }
		void cancel() noexcept { m_impl.cancel(*this); }
		decltype(auto) get_result() { return m_impl.get_result(*this); }

		socket_recv_from_operation_impl m_impl;

	};

}}}//qor::nswindows::framework

#endif//QOR_PP_H_OS_WINDOWS_FRAMEWORK_ASYNCIOSERVICE_IOCP_RECVFROMOP
