// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "display.h"
#include "context.h"
#include "window.h"

namespace qor{ namespace platform { namespace nswindows{

    EglDisplay::EglDisplay() : qor::components::EGLDisplay()
    {
        m_nativeWindow = new EglWindow();
        m_display = EGL::StaticGetDisplay((EGLNativeDisplayType)(m_nativeWindow->GetNativeSurface()));
        if( m_display == nullptr)
        {
            //TODO: error
        }
        else
        {
            if(!Initialize())
            {
                /*
                EGL_BAD_DISPLAY is generated if display is not an EGL display connection.

                EGL_NOT_INITIALIZED is generated if display cannot be initialized.*/
            }
        }
    }

    EglDisplay::EglDisplay(void* nativeDisplay) : qor::components::EGLDisplay(nativeDisplay)
    {
        m_display = EGL::StaticGetDisplay((EGLNativeDisplayType)nativeDisplay);
        if( m_display == nullptr)
        {
            //TODO: error
        }
        else
        {
            if(!Initialize())
            {
                /*
                EGL_BAD_DISPLAY is generated if display is not an EGL display connection.

                EGL_NOT_INITIALIZED is generated if display cannot be initialized.*/
            }
        }
    }

    EglDisplay::EglDisplay(EGLenum platform, void* nativeDisplay, const intptr_t* attrib_list) : qor::components::EGLDisplay(platform, nativeDisplay, attrib_list)
    {
        m_display = EGL::StaticGetPlatformDisplay(platform, nativeDisplay, attrib_list);
        if(m_display == nullptr)
        {
            //TODO: error
        }
        else
        {
            if(!Initialize())
            {
                /*
                EGL_BAD_DISPLAY is generated if display is not an EGL display connection.

                EGL_NOT_INITIALIZED is generated if display cannot be initialized.*/                
            }
        }
    }

    EglDisplay::~EglDisplay()
    {
        if(!Terminate())
        {
            //EGL_BAD_DISPLAY is generated if display is not an EGL display connection
        }
    }

    bool EglDisplay::Initialize()
    {
        return EGL::StaticInitialize(m_display, &m_major, & m_minor);
    }

    bool EglDisplay::Terminate()
    {
        return EGL::StaticTerminate(m_display);
    }

    bool EglDisplay::ChooseConfig(const int32_t* attrib_list, void** configs, int32_t config_size, int32_t* num_config)
    {
        return EGL::StaticChooseConfig(m_display, attrib_list, configs, config_size, num_config);
    }

    bool EglDisplay::CopyBuffers(void* surface, void* target)
    {
        return EGL::StaticCopyBuffers(m_display, surface, (HBITMAP)(target));
    }

    void* EglDisplay::InternalCreateContext(void* config, void* share_context, const int32_t *attrib_list)
    {
        return EGL::StaticCreateContext(m_display, config, share_context, attrib_list);
    }

    ref_of<qor::components::EGLContext>::type EglDisplay::CreateContext(void* config, void* share_context, const int32_t *attrib_list)
    {
        return new_ref<EglContext>(this, config, share_context, attrib_list);
    }

    void* EglDisplay::CreatePbufferSurface(void* config, const int32_t *attrib_list)
    {
        return EGL::StaticCreatePbufferSurface(m_display, config, attrib_list);
    }

    void* EglDisplay::CreatePixmapSurface(void* config, void* pixmap, const int32_t *attrib_list)
    {
        return EGL::StaticCreatePixmapSurface(m_display, config, (HBITMAP)(pixmap), attrib_list);
    }

    void* EglDisplay::CreateWindowSurface(void* config, void* win, const int32_t *attrib_list)
    {
        return EGL::StaticCreateWindowSurface(m_display, config, (HWND)(win), attrib_list);
    }

    bool EglDisplay::InternalDestroyContext(void* ctx)
    {
        return EGL::StaticDestroyContext(m_display, ctx);
    }

    bool EglDisplay::DestroySurface(void* surface)
    {
        return EGL::StaticDestroySurface(m_display, surface);
    }

    bool EglDisplay::GetConfigAttrib(void* config, int32_t attribute, int32_t *value)
    {
        return EGL::StaticGetConfigAttrib(m_display, config, attribute, value);
    }

    bool EglDisplay::GetConfigs(void* *configs, int32_t config_size, int32_t *num_config)
    {
        return EGL::StaticGetConfigs(m_display, configs, config_size, num_config);
    }

    bool EglDisplay::MakeCurrent(void* draw, void* read, void* ctx)
    {
        return EGL::StaticMakeCurrent(m_display, draw, read, ctx);
    }

    bool EglDisplay::InternalQueryContext(void* ctx, int32_t attribute, int32_t *value)
    {
        return EGL::StaticQueryContext(m_display, ctx, attribute, value);
    }

    const char* EglDisplay::QueryString(int32_t name)
    {
        return EGL::StaticQueryString(m_display, name);
    }

    bool EglDisplay::QuerySurface(void* surface, int32_t attribute, int32_t *value)
    {
        return EGL::StaticQuerySurface(m_display, surface, attribute, value);
    }

    bool EglDisplay::SwapBuffers(void* surface)
    {
        return EGL::StaticSwapBuffers(m_display, surface);
    }

    bool EglDisplay::BindTexImage(void* surface, int32_t buffer)
    {
        return EGL::StaticBindTexImage(m_display, surface, buffer);
    }

    bool EglDisplay::ReleaseTexImage(void* surface, int32_t buffer)
    {
        return EGL::StaticReleaseTexImage(m_display, surface, buffer);
    }

    bool EglDisplay::SurfaceAttrib(void* surface, int32_t attribute, int32_t value)
    {
        return EGL::StaticSurfaceAttrib(m_display, surface, attribute, value);
    }

    bool EglDisplay::SwapInterval(int32_t interval)
    {
        return EGL::StaticSwapInterval(m_display, interval);
    }

    void* EglDisplay::CreatePbufferFromClientBuffer(unsigned int buftype, void* buffer, void* config, const int32_t *attrib_list)
    {
        return EGL::StaticCreatePbufferFromClientBuffer(m_display, buftype, buffer, config, attrib_list);
    }

    void* EglDisplay::CreateSync(unsigned int type, const intptr_t *attrib_list)
    {
        return EGL::StaticCreateSync(m_display, type, attrib_list);
    }

    bool EglDisplay::DestroySync(void* sync)
    {
        return EGL::StaticDestroySync(m_display, sync);
    }

    int32_t EglDisplay::ClientWaitSync(void* sync, int32_t flags, unsigned long long timeout)
    {
        return EGL::StaticClientWaitSync(m_display, sync, flags, timeout);
    }

    bool EglDisplay::GetSyncAttrib(void* sync, int32_t attribute, intptr_t *value)
    {
        return EGL::StaticGetSyncAttrib(m_display, sync, attribute, value);
    }

    void* EglDisplay::InternalCreateImage(void* ctx, unsigned int target, void* buffer, const intptr_t *attrib_list)
    {
        return EGL::StaticCreateImage(m_display, ctx, target, buffer, attrib_list);
    }

    bool EglDisplay::DestroyImage(void* image)
    {
        return EGL::StaticDestroyImage(m_display, image);
    }

    void* EglDisplay::CreatePlatformWindowSurface(void* config, void *native_window, const intptr_t *attrib_list)
    {
        return EGL::StaticCreatePlatformWindowSurface(m_display, config, native_window, attrib_list);
    }

    void* EglDisplay::CreatePlatformPixmapSurface(void* config, void *native_pixmap, const intptr_t *attrib_list)
    {
        return EGL::StaticCreatePlatformPixmapSurface(m_display, config, native_pixmap, attrib_list);
    }

    bool EglDisplay::WaitSync(void* sync, int32_t flags)
    {
        return EGL::StaticWaitSync(m_display, sync, flags);
    }

}}}//qor::platform::nswindows
