// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include "src/qor/error/error.h"

#include "presentation.h"
#include "feedback.h"

#include "src/platform/os/linux/wayland/client/surface.h"

#include <wayland-client-core.h>
#include <wayland-client-protocol.h>
#include "presentation-time.h"
#include "listeners/presentationlistener.h"

namespace qor{ namespace platform { namespace nslinux{ namespace wl{

    const char* const Presentation::TagName = "QOR::PLATFORM::NSLINUX::WL::PRESENTATION";

    Presentation* Presentation::PresentationFrom(wp_presentation* pres)
    {
        if(!pres)
        {
            return nullptr;
        }
        Presentation* result = reinterpret_cast<Presentation*>(wp_presentation_get_user_data(pres));
        if(result && result->Tag() == TagName)
        {
            return result;
        }
        else if(result)
        {
            continuable("Wayland wp_presentation user data tag mismatch");
        }
        return new Presentation(pres);
    }

    Presentation::Presentation(wp_presentation* pres) : m_pres(pres)
    {
        if(m_pres)
        {
            wp_presentation_set_user_data(m_pres, this);
        }
        else
        {
            continuable("Presentation created with null wp_presentation pointer");
        }
    }

    Presentation::Presentation(Presentation&& rhs) noexcept : m_pres(rhs.m_pres)
    {
        rhs.m_pres = nullptr;
        if (m_pres)
        {
            wp_presentation_set_user_data(m_pres, this);
        }
    }

    Presentation& Presentation::operator=(Presentation&& rhs) noexcept
    {
        if (this != &rhs)
        {
            if (m_pres)
            {
                wp_presentation_destroy(m_pres);
            }
            m_pres = rhs.m_pres;
            rhs.m_pres = nullptr;
            if (m_pres)
            {
                wp_presentation_set_user_data(m_pres, this);
            }
        }
        return *this;
    }

    Presentation::~Presentation()
    {
        if(m_pres)
        {
            wp_presentation_destroy(m_pres);
        }
    }

    wp_presentation* Presentation::Use() const
    {
        if(!m_pres)
        {
            warning("Using Presentation with null wp_presentation pointer");
        }
        return m_pres;
    }

    uint32_t Presentation::Version() const
    {
        if(!m_pres)
        {
            warning("Getting version of Presentation with null wp_presentation pointer");
            return 0;
        }
        return wp_presentation_get_version(m_pres);
    }

    int Presentation::AddListener(const PresentationListener& listener, void* context)
    {
        return wp_presentation_add_listener(m_pres, &listener, context);
    }

    qor::ref_of<Feedback>::type Presentation::CreateFeedback(Surface* surface)
    {
        return new_ref<Feedback>( (struct wp_presentation_feedback*)(wp_presentation_feedback(m_pres, surface ? surface->Use() : nullptr)));
    }

    void Presentation::ClockId(void* data, uint32_t clkId)
    {

    }
}}}}//qor::platform::nslinux::wl
