
// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_LINUX_XINPUT_DEVICE
#define QOR_PP_H_LINUX_XINPUT_DEVICE

#include <vector>

namespace qor{ namespace platform { namespace nslinux{ namespace x{

    class qor_pp_module_interface(QOR_LINX) Display;
    class qor_pp_module_interface(QOR_LINX) Window;
    union qor_pp_module_interface(QOR_LINX) Event;

    struct ModifierKeymap;

    struct FeedbackState
    {
        unsigned long   c_class;
        int             length;
        unsigned long   id;
    };

    struct FeedbackControl
    {
        unsigned long   c_class;
        int             length;
        unsigned long   id;
    };

    struct InputClass;

    struct DeviceState
    {
        unsigned long   device_id;
        int		        num_classes;
        InputClass*     data;
    };

    struct DeviceControl
    {
        unsigned long   control;
        int             length;
    };

    struct DeviceTimeCoord
    {
        unsigned long   time;
        int*            data;
    };


    class qor_pp_module_interface(QOR_LINXINPUT) Device
    {
    public:
    
        Device(Display* dpy, void* device);
        virtual ~Device();

        void* Use()
        {
            return m_device;
        }

        int	ChangeKeyboard();
        int	ChangePointer(int xaxis, int yaxis);
        int	Grab(Window& grabWindow, int ownerEvents, int eventCount, unsigned long* eventList, int thisDeviceMode, int otherDevicesMode, unsigned long time);
        int	Ungrab(unsigned long time);
        int GrabKey(unsigned int key, unsigned int modifiers, Device& modifierDevice, Window& grabWindow, int ownerEvents, unsigned int eventCount, unsigned long* eventList, int thisDeviceMode, int otherDevicesMode);
        int	UngrabKey(unsigned int key, unsigned int modifiers, Device& modifierDev, Window& grabWindow);
        int	GrabButton(unsigned int button, unsigned int modifiers, Device& modifierDevice, Window& grabWindow, int ownerEvents, unsigned int eventCount, unsigned long* eventList, int thisDeviceMode, int otherDevicesMode);
        int	UngrabButton(unsigned int button, unsigned int modifiers, Device& modifierDev, Window& grabWindow);
        int AllowEvents(int eventMode, unsigned long time);
        int	GetFocus(unsigned long& focus, int& revert_to, unsigned long& time);
        int	SetFocus(unsigned long focus, int revert_to, unsigned long time);
        std::vector<FeedbackState> GetFeedbackControl();
        int	ChangeFeedbackControl(unsigned long mask, FeedbackControl& f);
        int	Bell(unsigned long feedbackclass, unsigned long feedbackid, int percent);
        int	ChangeKeyMapping(int first, int symsPerCode, std::vector<unsigned long> keysyms);
        std::vector<unsigned char> GetModifierMapping(int& maxKeyPerMod);
        int	SetModifierMapping(std::vector<unsigned char> map, int maxKeyPerMod);
        int	SetButtonMapping(std::vector<unsigned char>& map);
        int	GetButtonMapping(std::vector<unsigned char>& map);
        std::vector<InputClass> QueryState();        
        int	SetMode(int mode);        
        int	SetValuators(int* valuators, int first_valuator, int num_valuators);
        DeviceControl GetControl(int control);        
        int	ChangeControl(int control, DeviceControl& d);
        int	SendExtensionEvent(Window& dest, int prop, int count, unsigned long* list, Event* event);
        std::vector<DeviceTimeCoord> GetMotionEvents(unsigned long start, unsigned long stop, int* mode, int* axis_count);
        std::vector<unsigned long> ListProperties();
        void ChangeProperty(unsigned long property, unsigned long type, int format, int mode, const std::vector<unsigned char> data);
        void DeleteProperty(unsigned long property);
        int GetProperty(unsigned long property, long offset, long length, int del, unsigned long reqType, unsigned long& actualType, int& actualFormat, unsigned long& bytesAfter, std::vector<unsigned char>& prop);
        std::vector<unsigned long> GetKeyMapping(unsigned int first, int keycount, int& symsPercode);

    protected:

        Display* m_display;
        void* m_device;
    };

}}}}//qor::platform::nslinux::x
    
#endif//QOR_PP_H_LINUX_XINPUT_DEVICE
