// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "input.h"
#include "device.h"
#include "src/qor/error/error.h"

#include <X11/Xlib.h>
#include <X11/X.h>
#include <X11/Xcms.h>
#include <X11/Xutil.h>
#include <X11/Xresource.h>
#include <X11/Xatom.h>
#include <X11/cursorfont.h>
#include <X11/keysymdef.h>
#include <X11/keysym.h>
#include <X11/Xlibint.h>
#include <X11/Xproto.h>
#include <X11/Xprotostr.h>

#include <X11/extensions/XI.h>
#include <X11/extensions/XInput.h>

namespace qor{ namespace platform { namespace nslinux{ namespace x{

    XInput::XInput(Display* dpy) : m_display(dpy)
    {        
        XExtCodes* data = XInitExtension((::Display*)(m_display->Use()), "XInputExtension");
        m_extCodes = *(reinterpret_cast<ExtCodes*>(data));
        XFree(data);
    }

    XInput::~XInput()
    {
    }

    ExtensionVersion XInput::GetExtensionVersion()
    {
        ExtensionVersion version;
        XExtensionVersion* data = XGetExtensionVersion((::Display*)(m_display->Use()), "XInputExtension");
        version = *(reinterpret_cast<ExtensionVersion*>(data));
        XFree(data);
        return version;
    }

    std::vector<DeviceInfo> XInput::ListInputDevices()
    {
        std::vector<DeviceInfo> devices;
        int count = 0;
        XDeviceInfo* data = XListInputDevices((::Display*)(m_display->Use()), &count);
        if(count != 0 && data != nullptr)
        {
            devices.resize(count);
            memcpy(devices.data(), data, sizeof(DeviceInfo) * count);
            ::XFreeDeviceList(data);
        }
        return devices;
    }

    Device XInput::OpenDevice(unsigned long Id)
    {
        Device device(m_display, XOpenDevice((::Display*)(m_display->Use()),Id));
        return device;
    }
    
}}}}//qor::platform::nslinux::x