// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include "datasource.h"

namespace qor{ namespace pipeline{

    DataSource::DataSource() = default;
    DataSource::~DataSource() = default;

    void DataSource::SetCallback( const Delegate<bool(size_t&, size_t)>& callback)
    {
        m_callBack = callback;
    }

    void DataSource::SetByteOrder(const arch::Endian byteOrder)
    {
        m_outputByteOrder = byteOrder;
    }

    bool DataSource::Insert(byte* data, size_t byteCount)
    {        
        Buffer* buffer = GetBuffer();    
        byte* space = nullptr;
        size_t totalWritten = 0;
        size_t unitsPumped = 0;
        size_t realWrite = 0;
        do
        {
            realWrite = byteCount - totalWritten;
            space = buffer->WriteRequest(realWrite);
            totalWritten += realWrite;
            if(space)
            {
                InsertBufferValue(space, realWrite, data, byteCount, totalWritten);
                buffer->WriteAcknowledge(realWrite);
            }

            unitsPumped = 0;
        }while(m_callBack(unitsPumped, realWrite) && space && totalWritten < byteCount);
        return totalWritten == byteCount ? true : false;
    }

    bool DataSource::Pull(size_t& unitsRead, size_t unitsToRead)
    {
        Buffer* buffer = GetBuffer();
        if(buffer)
        {
            size_t bufferCapacity = buffer->ReadCapacity();
            unitsRead = std::min(unitsToRead, bufferCapacity);
            if(unitsRead == 0)
            {
                OnEndOfData();            
            }
            return true;
        }
        else
        {
            return false;
        }
    }

    void DataSource::InsertBufferValue(byte* space, size_t realWrite, byte* data, size_t size, size_t totalWritten)
    {
        if(arch::endian != m_outputByteOrder)
        {
            int index = 0;
            while(index < realWrite)
            {
                space[realWrite - (index + 1)] = data[index + (size - totalWritten)];
                ++index;
            }
        }
        else
        {
            memcpy(space + static_cast<int>(totalWritten - realWrite), data, realWrite);
        }
    }
    
}}//qor::pipeline