// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "extcursor.h"
#include "src/platform/os/linux/x/xlib/display.h"
#include "src/platform/os/linux/x/xlib/pixmap.h"
#include "src/platform/os/linux/x/xlib/font.h"

#include <X11/extensions/Xfixes.h>

namespace qor{ namespace platform { namespace nslinux{ namespace x{

    ExtCursor::ExtCursor(Display* display, unsigned long id) : 
        Cursor(display, id)
    {
    }

    ExtCursor::ExtCursor(Display* display, Pixmap& source, Pixmap& mask, Colour& foregroundColour, Colour& backgroundColour, int x, int y) :
        Cursor(display, source, mask, foregroundColour, backgroundColour, x, y)
    {
    }

    ExtCursor::ExtCursor(Display* display, Font& sourceFont, Font& maskFont, unsigned int sourceChar, unsigned int maskChar, Colour& foregroundColour, Colour& backgroundColour) : 
        Cursor(display, sourceFont, maskFont, sourceChar, maskChar, foregroundColour, backgroundColour)
    {
    }

    ExtCursor::ExtCursor(Display* display, unsigned int shape) : Cursor(display, shape)
    {
    }

    ExtCursor::~ExtCursor()
    {        
    }

    void ExtCursor::SetName(const std::string& name)
    {
        XFixesSetCursorName((::Display*)(m_display->Use()), (::Cursor)(m_Id), name.c_str());
    }

    std::string ExtCursor::GetName(unsigned long& atom)
    {
        std::string name(XFixesGetCursorName((::Display*)(m_display->Use()), (::Cursor)(m_Id), &atom));
        return name;
    }

    void ExtCursor::Change(Cursor source)
    {
        XFixesChangeCursor((::Display*)(m_display->Use()), source.GetId(), m_Id);
    }

    void ExtCursor::ChangeByName(Cursor source, std::string& name)
    {
        XFixesChangeCursorByName((::Display*)(m_display->Use()), source.GetId(), name.c_str());
    }

    CursorImage ExtCursor::GetCursorImage()
    {
        return *(reinterpret_cast<CursorImage*>(::XFixesGetCursorImage((::Display*)(m_display->Use()))));
    }

}}}}//qor::platform::nslinux::x
