// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_LINUX_WAYLAND_XDGTOPLEVEL
#define QOR_PP_H_LINUX_WAYLAND_XDGTOPLEVEL

#include <stdint.h>

struct xdg_toplevel;
struct xdg_toplevel_listener;
struct wl_array;

namespace qor{ namespace platform { namespace nslinux{ namespace wl{

    class qor_pp_module_interface(QOR_LINWLXDGSHELL) Output;
    class qor_pp_module_interface(QOR_LINWLXDGSHELL) Seat;

    class qor_pp_module_interface(QOR_LINWLXDGSHELL) XDGSession;

    class qor_pp_module_interface(QOR_LINWLXDGSHELL) XDGTopLevel
    {
    public:
        static const char* const TagName;
        static XDGTopLevel* XDGTopLevelFrom(xdg_toplevel* toplevel);
        explicit XDGTopLevel(xdg_toplevel* toplevel);
        virtual ~XDGTopLevel();
        XDGTopLevel(const XDGTopLevel&) = delete;
        XDGTopLevel& operator=(const XDGTopLevel&) = delete;
        XDGTopLevel(XDGTopLevel&& rhs) noexcept;
        XDGTopLevel& operator=(XDGTopLevel&& rhs) noexcept;
        virtual const char* Tag() const{return TagName;}
        xdg_toplevel* Use() const;
        uint32_t Version() const;
        void AddListener(const xdg_toplevel_listener& listener, void* data);
        void Move(uint32_t serial);
        void Resize(uint32_t serial, uint32_t edges);
        void SetAppId(const char* app_id);
        void SetFullscreen(Output& output);
        void SetMaxSize(int32_t width, int32_t height);
        void SetMaximized();
        void SetMinSize(int32_t width, int32_t height);
        void SetMinimized();
        void SetParent(XDGTopLevel* parent);
        void SetTitle(const char* title);
        void ShowWindowMenu(Seat* seat, uint32_t serial, int32_t x, int32_t y);
        void UnsetFullscreen();
        void UnsetMaximized();
        virtual void OnConfigure(void* context, int32_t width, int32_t height, struct wl_array* states);
        virtual void OnClose(void* context);
        void SetSession(XDGSession* session);

    private:

        xdg_toplevel* m_toplevel;
        XDGSession* m_session;
    };

}}}}//qor::platform::nslinux::wl

#endif//#define QOR_PP_H_LINUX_WAYLAND_XDGTOPLEVEL
