// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include <string>
#include <format>

#include "errorhandler.h"

//Windows specific headers must be last to prevent contaminating generic headers with Windows specific types and definitions
#include "kernel32.h" //kernel32.h must be the first windows header as it's the primary inclusion point for windows.h
#include "../returncheck.h"
#include "../library.h"

namespace qor { namespace nswindows { namespace api {

    //Returns the last Win32 error, in string format. Returns an empty string if there is no error.
    std::string GetLastErrorAsString()
    {
        //Get the error message ID, if any.
        DWORD errorMessageID = ::GetLastError();
        if(errorMessageID == 0) {
            return std::string(); //No error message has been recorded
        }
        
        LPSTR messageBuffer = nullptr;

        //Ask Win32 to give us the string version of that message ID.
        //The parameters we pass in, tell Win32 to create the buffer that holds the message for us (because we don't yet know how long the message string will be).
        size_t size = FormatMessageA(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                                    NULL, errorMessageID, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPSTR)&messageBuffer, 0, NULL);
        
        //Copy the error message into a std::string.
        std::string message(messageBuffer, size);
        
        //Free the Win32's string's buffer.
        LocalFree(messageBuffer);
                
        return message;
    }

    bool Win32ErrorHandler::Handle(const qor::Error& error)
    {        
        switch(error.what().GetSeverity())
        {
            case Severity::Note:
                ::OutputDebugStringA(error.what().Content().c_str());
                return true;//default ignore;
                break;
            case Severity::Warning:
                ::OutputDebugStringA(error.what().Content().c_str());
                return true;
                break;
            case Severity::Continuable_Error:
                {                    
                    std::string message = GetLastErrorAsString();
                    //std::string Message = MessageText(error.what().GetSeverity(), error.what().Content(), GetWhereClause(error), error.when().TimePoint());
                    ::OutputDebugStringA(std::format("{0}. Windows error status - {1}",error.what().Content(), message).c_str());
                    return false;
                }
                break;
            case Severity::Serious_Error:
                {                    
                    std::string message = GetLastErrorAsString();
                    ::OutputDebugStringA(std::format("{0}. Windows error status - {1}",error.what().Content(), message).c_str());
                    return false;
                }                
                break;
            case Severity::Fatal_Error:
                {                    
                    std::string message = GetLastErrorAsString();
                    ::OutputDebugStringA(std::format("{0}. Windows error status - {1}",error.what().Content(), message).c_str());
                    return false;
                }
                break;
        }   
        return false;     
    }
}}}//qor::nswindows::api