// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_EXAMPLES_ECHOSERVER_ECHOPROTOCOL
#define QOR_PP_H_EXAMPLES_ECHOSERVER_ECHOPROTOCOL

#include "src/framework/thread/currentthread.h"
#include "src/qor/reference/newref.h"
#include "src/framework/application/irunable.h"
#include "src/framework/pipeline/pipeline.h"
#include "src/framework/pipeline/copyfilter.h"

class EchoProtocol : public qor::framework::IRunable
{
public:

    static constexpr size_t maxEchoSize = 1024;

    EchoProtocol(qor::ref_of<qor::pipeline::Pipeline>::type pipeline);
    virtual ~EchoProtocol() noexcept = default;
    virtual int Run(void);
        
private:
    qor::pipeline::CopyFilter m_copyFilter;
    qor::ref_of<qor::pipeline::Pipeline>::type m_Pipeline;
};

#endif//QOR_PP_H_EXAMPLES_ECHOSERVER_ECHOPROTOCOL