// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include <iostream>
#include <format>
#include "src/qor/error/error.h"
#include "serverloghandler.h"
#include "src/components/framework/logaggregator/logaggregator.h"

ServerLogHandler::ServerLogHandler(qor::log::Level logLevel) : qor::components::LogHandler(logLevel)
{
}

std::string ServerLogHandler::WhereText(const char* module, const char* file, const char* function, int line, const std::string& exceptionText, const std::string& instanceText, const std::string& threadText) const
{
    return std::format("Module: {0}| File: {1}| Function: {2}| Line: {3}| {4}| {5}| Thread: {6}", 
        module, 
        file, 
        function, 
        line,
        exceptionText,
        instanceText,
        threadText);

}

std::string ServerLogHandler::InstanceText(bool inInstance, const qor::AnyObject& any) const
{
    return inInstance ?
        std::format("Object at: {0}", any.Ptr()->operator void*()) : 
        "Free function";
}

std::string ServerLogHandler::InExceptionText(bool inException) const
{
    return inException ? "Exceptional flow" : "Normal flow";
}

std::string ServerLogHandler::MessageText(const std::string_view& level, const std::string& what, const std::string& where, const std::chrono::time_point<std::chrono::high_resolution_clock, std::chrono::nanoseconds>& when) const
{
    //TODO: Fix windows side formatting of nanosecond durations
    return std::format("{0}:TODO:|{2} \"{1}\"\n",level, what, where/*, when*/);
}
