// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include "src/qor/error/error.h"

#include "compositor.h"
#include "surface.h"
#include "region.h"

#include <wayland-client-core.h>
#include <wayland-client-protocol.h>

namespace qor{ namespace platform { namespace nslinux{ namespace wl{

    const char* const Compositor::TagName = "QOR::PLATFORM::NSLINUX::WL::COMPOSITOR";

    Compositor* Compositor::CompositorFrom(wl_compositor* compositor)
    {
        if(!compositor)
        {
            return nullptr;
        }
        Compositor* result = reinterpret_cast<Compositor*>(wl_compositor_get_user_data(compositor));
        if(result && result->Tag() == TagName)
        {
            return result;
        }
        else if(result)
        {
            continuable("Wayland wl_compositor user data tag mismatch");
        }
        return new Compositor(compositor);
    }

    Compositor::Compositor(wl_compositor* compositor) : m_compositor(compositor)
    {
        if(compositor)
        {
            wl_compositor_set_user_data(m_compositor, this);
        }
        else
        {
            continuable("Compositor created with null wl_compositor pointer");
        }
    }

    Compositor::Compositor(Compositor&& rhs) noexcept : m_compositor(rhs.m_compositor)
    {
        rhs.m_compositor = nullptr;
        if (m_compositor)
        {
            wl_compositor_set_user_data(m_compositor, this);
        }
    }

    Compositor& Compositor::operator=(Compositor&& rhs) noexcept
    {
        if (this != &rhs)
        {
            if (m_compositor)
            {
                wl_compositor_destroy(m_compositor);
            }

            m_compositor = rhs.m_compositor;
            rhs.m_compositor = nullptr;

            if (m_compositor)
            {
                wl_compositor_set_user_data(m_compositor, this);
            }
        }
        return *this;
    }

    Compositor::~Compositor()
    {
        if(m_compositor)
        {
            wl_compositor_destroy(m_compositor);
        }
    }

    wl_compositor* Compositor::Use() const
    {
        if(!m_compositor)
        {
            warning("Using Compositor with null wl_compositor pointer");
        }
        return m_compositor;
    }

    uint32_t Compositor::Version() const
    {
        if(!m_compositor)
        {
            warning("Getting version of Compositor with null wl_compositor pointer");
            return 0;
        }
        return wl_compositor_get_version(m_compositor);
    }

    wl_surface* Compositor::InternalCreateSurface()
    {
        if(!m_compositor)
        {
            warning("Creating surface with null wl_compositor pointer");
            return nullptr;
        }
        return wl_compositor_create_surface(m_compositor);
    }

    wl_region* Compositor::InternalCreateRegion()
    {
        if(!m_compositor)
        {
            warning("Creating region with null wl_compositor pointer");
            return nullptr;
        }
        return wl_compositor_create_region(m_compositor);
    }

}}}}//qor::platform::nslinux::wl
