// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include "src/qor/error/error.h"

#include "datadevicemanager.h"
#include "seat.h"
#include "datasource.h"
#include "datadevice.h"

#include <wayland-client-core.h>
#include <wayland-client-protocol.h>

namespace qor{ namespace platform { namespace nslinux{ namespace wl{

    DataDeviceManager* DataDeviceManager::DataDeviceManagerFrom(wl_data_device_manager* ddm)
    {
        return reinterpret_cast<DataDeviceManager*>(wl_data_device_manager_get_user_data(ddm));
    }

    DataDeviceManager::DataDeviceManager(wl_data_device_manager* ddm) : m_ddm(ddm)
    {
        wl_data_device_manager_set_user_data(m_ddm, this);
    }    

    DataDeviceManager::~DataDeviceManager()
    {
        wl_data_device_manager_destroy(m_ddm);
    }

    wl_data_device_manager* DataDeviceManager::Use()
    {
        return m_ddm;
    }

    uint32_t DataDeviceManager::Version()
    {
        return wl_data_device_manager_get_version(m_ddm);
    }

    DataSource DataDeviceManager::CreateDataSource()
    {
        return DataSource(wl_data_device_manager_create_data_source(m_ddm));    
    }

    DataDevice DataDeviceManager::GetDataDevice(Seat* seat)
    {
        return DataDevice(wl_data_device_manager_get_data_device(m_ddm, seat ? seat->Use() : nullptr));
    }
    
}}}}//qor::platform::nslinux::wl
