// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "themedata.h"
#include "../gdiobjects/devicecontext.h"

#include "src/platform/os/windows/api_layer/uxtheme/uxtheme.h"

#undef DrawTextEx

using namespace qor::win::api;

namespace qor{ namespace platform { namespace win{

    ThemeData::ThemeData(const Window& window) : 
        m_handle(UXTheme::GetWindowTheme((HWND)(window.GetHandle().Use())))
    {
        m_handle.DontClose();
    }
    
    ThemeData::ThemeData(const Window& window, const wchar_t* classList) :
        m_handle((UXTheme::OpenThemeData((HWND)(window.GetHandle().Use()), classList)))
    {        
        m_handle.DontClose();
    }

    ThemeData::ThemeData(const Window& window, const wchar_t* classList, unsigned long flags) :
        m_handle((UXTheme::OpenThemeDataEx((HWND)(window.GetHandle().Use()), classList, flags)))
    {
        m_handle.DontClose();
    }

    ThemeData::~ThemeData()
    {
        UXTheme::CloseThemeData((HTHEME)(m_handle.Use()));
    }

    int ThemeData::GetSysSize(int sizeId)
    {
        return UXTheme::GetThemeSysSize((HTHEME)(m_handle.Use()), sizeId);
    }

    long ThemeData::GetSysFont(int fontId, LogFont& logFont)
    {
        return UXTheme::GetThemeSysFont((HTHEME)(m_handle.Use()), fontId, reinterpret_cast<LOGFONTW*>(&logFont));
    }

    long ThemeData::DrawBackground(DeviceContext& dc, int partId, int stateId, const Rect& rect, Rect& clipRect)
    {
        return UXTheme::DrawThemeBackground((HTHEME)(m_handle.Use()), (HDC)(dc.GetHandle().Use()), partId, stateId, reinterpret_cast<LPCRECT>(&rect), reinterpret_cast<LPCRECT>(&clipRect));
    }

    long ThemeData::DrawEdge(DeviceContext& dc, int partId, int stateId, const Rect& destRect,unsigned int edge, unsigned int flags, Rect& contentRect)
    {
        return UXTheme::DrawThemeEdge((HTHEME)(m_handle.Use()), (HDC)(dc.GetHandle().Use()), partId, stateId, reinterpret_cast<LPCRECT>(&destRect), edge, flags, reinterpret_cast<LPRECT>(&contentRect));
    }

    long ThemeData::DrawTextEx(DeviceContext& dc, int partId, int stateId, const std::wstring& text, unsigned long flags, Rect& rect)
    {
        return UXTheme::DrawThemeTextEx((HTHEME)(m_handle.Use()), (HDC)(dc.GetHandle().Use()), partId, stateId, text.c_str(), static_cast<int>(text.size()), flags, reinterpret_cast<LPRECT>(&rect), nullptr);
    }

    long ThemeData::DrawTextEx(DeviceContext& dc, int partId, int stateId, const std::wstring& text, unsigned long flags, Rect& rect, const DTTOpts& options)
    {
        return UXTheme::DrawThemeTextEx((HTHEME)(m_handle.Use()), (HDC)(dc.GetHandle().Use()), partId, stateId, text.c_str(), static_cast<int>(text.size()), flags, reinterpret_cast<LPRECT>(&rect), reinterpret_cast<const DTTOPTS *>(&options));
    }

}}}//qor::platform::nswindow
