// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "brush.h"
#include "src/platform/os/windows/common/stringconv.h"
#include "src/platform/os/windows/api_layer/user/user32.h"
#include "src/platform/os/windows/api_layer/gdi/gdi32.h"

using namespace qor::nswindows::api;

namespace qor{ namespace platform { namespace nswindows{

    Brush::Brush() : GDIObject(OBrush)
    {
    }

    Brush::Brush(int colour) : GDIObject(colour, OBrush)
    {
    }

    Brush::Brush(const PrimitiveHandle& h) : GDIObject(h, OBrush)
    {
    }

    Brush::~Brush()
    {
    }

    Brush Brush::CreateIndirect(const LogBrush& logBrush)
    {
        Brush b(GDI32::CreateBrushIndirect(reinterpret_cast<const LOGBRUSH*>(&logBrush)));
        return b;
    }

    Brush Brush::CreateDIBPattern(void* hglbDIBPacked, unsigned int fuColorSpec)
    {
        Brush b(GDI32::CreateDIBPatternBrush(hglbDIBPacked, fuColorSpec));
        return b;
    }
    
    Brush Brush::CreateHatch(int fnStyle, unsigned long clrref)
    {
        Brush b(GDI32::CreateHatchBrush(fnStyle, clrref));
        return b;
    }

    Brush Brush::CreatePattern(Handle& bitmap)
    {
        Brush b(GDI32::CreatePatternBrush((HBITMAP)(bitmap.Use())));
        return b;
    }

    Brush Brush::CreateSolid(unsigned long crColor)
    {
        Brush b(GDI32::CreateSolidBrush(crColor));
        return b;
    }

    bool Brush::GetOrg(const Handle& deviceContext, Point& pt)
    {
        return GDI32::GetBrushOrgEx((HDC)(deviceContext.Use()), reinterpret_cast<LPPOINT>(&pt)) ? true : false;
    }

    bool Brush::SetOrg(const Handle& deviceContext, int x, int y, Point& pt)
    {
        return GDI32::SetBrushOrgEx((HDC)(deviceContext.Use()), x, y, reinterpret_cast<LPPOINT>(&pt)) ? true : false;
    }

    
    SysBrush::SysBrush(int nIndex) : Brush()
    {        
        m_handle = User32::GetSysColorBrush(nIndex);
        m_handle.DontClose();
    }

    SysBrush::~SysBrush()
    {
    }

    
}}}//qor::platform::nswindows
