// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_WINDOWS_GUI_MESSAGEHANDLER
#define QOR_PP_H_WINDOWS_GUI_MESSAGEHANDLER

#include "message.h"
#include "acceleratortable.h"
#include "window.h"
//All types on this interface must be portable
namespace qor{ namespace platform { namespace nswindows{ 

    struct LUID 
    {
        unsigned long LowPart;
        long HighPart;
    };

    struct BSMINFO
    {
        unsigned int  cbSize;
        void* hdesk;
        void*  hwnd;
        LUID  luid;
    };

    typedef void (* SendAsyncProc)(void*, unsigned int, unsigned long long, long long);

    class qor_pp_module_interface(QOR_WINGUI) MessageHandler
    {
    public:

        static const unsigned short PMNoRemove = 0x0000;
        static const unsigned short PMRemove = 0x0001;
        static const unsigned short PMNoYield = 0x0002;
        //static const unsigned int PMQSInput = (QSINPUT << 16));
        //static const unsigned int PMQSPostMessage = ((QSPOSTMESSAGE | QSHOTKEY | QSTIMER) << 16));
        //static const unsigned int PMQSPaint = (QSPAINT << 16));
        //static const unsigned int PMQSSendMessage = (QSSENDMESSAGE << 16));

        MessageHandler();
        MessageHandler(const MessageHandler& src);
        virtual ~MessageHandler() = default;
        MessageHandler& operator = (const MessageHandler& src);
        
        long BroadcastSystemMessageT(unsigned long dwFlags, unsigned long* lpdwRecipients, unsigned int uiMessage, unsigned long long wParam, long long lParam);
        long BroadcastSystemMessageT(unsigned long dwFlags, unsigned long* lpdwRecipients, unsigned int uiMessage, unsigned long long wParam, long long lParam, BSMINFO* pBSMInfo);
        long long Dispatch(const Message* lpmsg);
        bool GetInputState(void);
        bool Get(Message* lpMsg, void* hwnd, unsigned int wMsgFilterMin, unsigned int wMsgFilterMax);
        long long GetMessageExtraInfo(void);
        unsigned long GetMessagePos(void);
        long GetMessageTime(void);
        unsigned long GetQueueStatus(unsigned int flags);
        bool InSend(void);
        unsigned long InSendEx();
        bool Peek(Message* lpMsg, void* hwnd, unsigned int wMsgFilterMin, unsigned int wMsgFilterMax, unsigned int wRemoveMsg);
        bool Post(Window& Wnd, unsigned int Msg, unsigned long long wParam, long long lParam);        
        void PostQuit(int nExitCode);
        bool PostToThread(unsigned long idThread, unsigned int Msg, unsigned long long wParam, long long lParam);
        unsigned int RegisterWindowMessageT(const TCHAR* lpString);
        bool Reply(long long lResult);
        bool SendWithCallback(Window& hWnd, unsigned int Msg, unsigned long long wParam, long long lParam, SendAsyncProc lpCallBack, unsigned long long dwData);
        long long SendWithTimeout(Window& hWnd, unsigned int Msg, unsigned long long wParam, long long lParam, unsigned int fuFlags, unsigned int uTimeout, unsigned long long* lpdwResult);
        long long Send(Window& hWnd, unsigned int Msg, unsigned long long wParam, long long lParam);
        bool SendNotify(Window& hWnd, unsigned int Msg, unsigned long long wParam, long long lParam);
        long long SetMessageExtraInfo(long long lParam);
        bool Translate(const Message* lpMsg);
        bool TranslateMDISysAccel(Window& WndClient, Message* lpMsg);
        bool IsWow64(void);
        bool Wait(void);
        
        virtual int IsIdleMessage(Message* pMsg)  // checks for special messages
        {
            return 0;
        }

        virtual int OnIdle(long lCount) // return TRUE if more idle processing
        {
            return 0;
        }
        
        virtual bool RouteMessage(void);
        virtual bool RouteMessage(AcceleratorTable& acceleratorTable);
        virtual int MessageLoop(AcceleratorTable& acceleratorTable);
        
        virtual void Quit(int nExitCode)
        {
            PostQuit(nExitCode);
        }
        
    };
    
}}}//qor::platform::nswindows

#endif//QOR_PP_H_WINDOWS_GUI_MESSAGEHANDLER
