// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_COMPONENTS_FRAMEWORK_UI_EGL_SESSION
#define QOR_PP_H_COMPONENTS_FRAMEWORK_UI_EGL_SESSION

#include "src/framework/thread/currentthread.h"
#include "src/qor/reference/newref.h"
#include "display.h"
#include "egl.h"

namespace qor { namespace components{

    class qor_pp_module_interface(QOR_EGL) EGLDisplay;

    class EGLSession
    {
    public:
        
        EGLSession(ref_of<EGLDisplay>::type eglDisplay) : m_eglDisplay(eglDisplay)
        {
            m_eglDisplay->Initialize();
        }

        virtual ~EGLSession()
        {
        }

        virtual ref_of<EGLDisplay>::type GetEGLDisplay()
        {
            return m_eglDisplay;
        }

        virtual EGLPlatformHint GetPlatform()
        {
            return Wayland;
        }

    protected:

        ref_of<EGLDisplay>::type m_eglDisplay;        
    };

    template<class NativeSession, class PlatformEGLDisplay>
    class EGLSessionWrapper : public NativeSession, public EGLSession
    {
    public:

        template<class NativeDisplayRef>
        EGLSessionWrapper(NativeDisplayRef nativeDisplay) : NativeSession(nativeDisplay), EGLSession(new_ref<PlatformEGLDisplay>(NativeSession::GetDisplay()->Use()))
        {
        }

        template<class NativeDisplayRef>
        EGLSessionWrapper(NativeDisplayRef nativeDisplay, ref_of<PlatformEGLDisplay>::type eglDisplay) : NativeSession(nativeDisplay), EGLSession(eglDisplay)
        {
        }

        virtual ~EGLSessionWrapper()
        {
        }

    };
    
}}//qor::components

#endif//QOR_PP_H_COMPONENTS_FRAMEWORK_UI_EGL_SESSION
