// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_GL_VIDMODE
#define QOR_PP_H_GL_VIDMODE

namespace qor{ namespace gl{

    struct qor_pp_module_interface(QOR_GL) VidMode
    {     
        int width = {0};              // The width, in screen coordinates, of the video mode.
        int height = {0};             // The height, in screen coordinates, of the video mode.
        int redBits = {0};            // The bit depth of the red channel of the video mode.
        int greenBits= {0};           // The bit depth of the green channel of the video mode.
        int blueBits = {0};           // The bit depth of the blue channel of the video mode.
        int refreshRate = {0};        // The refresh rate, in Hz, of the video mode.
    };

}}//qor::gl

#endif//QOR_PP_H_GL_VIDMODE
