// Copyright Querysoft Limited 2008 - 2025

#ifndef QOR_PP_H_TEXT_UNICODE_SCRIPTS
#define QOR_PP_H_TEXT_UNICODE_SCRIPTS

#include <stdint.h>

namespace qor{ namespace unicode{

    typedef uint32_t tag_t;
    
    constexpr inline tag_t make_tag(unsigned char c1, unsigned char c2, unsigned char c3, unsigned char c4){ 
        return ((tag_t)((((uint32_t)(c1)&0xFF)<<24)|(((uint32_t)(c2)&0xFF)<<16)|(((uint32_t)(c3)&0xFF)<<8)|((uint32_t)(c4)&0xFF)));
    }

    constexpr inline uint8_t* untag(tag_t t){ uint8_t a[4]{(uint8_t)(((t)>>24)&0xFF),(uint8_t)(((t)>>16)&0xFF),(uint8_t)(((t)>>8)&0xFF),(uint8_t)((t)&0xFF)}; return a;}

    constexpr inline tag_t tag_none(){ return make_tag(0,0,0,0);}
    constexpr inline tag_t tag_max_signed(){ return make_tag(0x7f,0xff,0xff,0xff);}
    constexpr inline tag_t tag_max(){ return make_tag(0xff,0xff,0xff,0xff);}

    enum class script : uint32_t
    {
        COMMON			    = make_tag('Z','y','y','y'),
        INHERITED		    = make_tag('Z','i','n','h'),
        UNKNOWN			    = make_tag('Z','z','z','z'),
        ARABIC			    = make_tag('A','r','a','b'),
        ARMENIAN			= make_tag('A','r','m','n'),
        BENGALI			    = make_tag('B','e','n','g'),
        CYRILLIC			= make_tag('C','y','r','l'),
        DEVANAGARI		    = make_tag('D','e','v','a'),
        GEORGIAN			= make_tag('G','e','o','r'),
        GREEK			    = make_tag('G','r','e','k'),
        GUJARATI			= make_tag('G','u','j','r'),
        GURMUKHI			= make_tag('G','u','r','u'),
        HANGUL			    = make_tag('H','a','n','g'),
        HAN				    = make_tag('H','a','n','i'),
        HEBREW			    = make_tag('H','e','b','r'),
        HIRAGANA			= make_tag('H','i','r','a'),
        KANNADA			    = make_tag('K','n','d','a'),
        KATAKANA			= make_tag('K','a','n','a'),
        LAO				    = make_tag('L','a','o','o'),
        LATIN			    = make_tag('L','a','t','n'),
        MALAYALAM		    = make_tag('M','l','y','m'),
        ORIYA			    = make_tag('O','r','y','a'),
        TAMIL			    = make_tag('T','a','m','l'),
        TELUGU			    = make_tag('T','e','l','u'),
        THAI			    = make_tag('T','h','a','i'),
        TIBETAN			    = make_tag('T','i','b','t'),
        BOPOMOFO			= make_tag('B','o','p','o'),
        BRAILLE			    = make_tag('B','r','a','i'),
        CANADIAN_SYLLABICS  = make_tag('C','a','n','s'),
        CHEROKEE			= make_tag('C','h','e','r'),
        ETHIOPIC			= make_tag('E','t','h','i'),
        KHMER			    = make_tag('K','h','m','r'),
        MONGOLIAN		    = make_tag('M','o','n','g'),
        MYANMAR			    = make_tag('M','y','m','r'),
        OGHAM			    = make_tag('O','g','a','m'),
        RUNIC			    = make_tag('R','u','n','r'),
        SINHALA			    = make_tag('S','i','n','h'),
        SYRIAC			    = make_tag('S','y','r','c'),
        THAANA			    = make_tag('T','h','a','a'),
        YI				    = make_tag('Y','i','i','i'),
        DESERET			    = make_tag('D','s','r','t'),
        GOTHIC			    = make_tag('G','o','t','h'),
        OLD_ITALIC		    = make_tag('I','t','a','l'),
        BUHID			    = make_tag('B','u','h','d'),
        HANUNOO			    = make_tag('H','a','n','o'),
        TAGALOG			    = make_tag('T','g','l','g'),
        TAGBANWA			= make_tag('T','a','g','b'),
        CYPRIOT			    = make_tag('C','p','r','t'),
        LIMBU			    = make_tag('L','i','m','b'),
        LINEAR_B			= make_tag('L','i','n','b'),
        OSMANYA			    = make_tag('O','s','m','a'),
        SHAVIAN			    = make_tag('S','h','a','w'),
        TAI_LE			    = make_tag('T','a','l','e'),
        UGARITIC			= make_tag('U','g','a','r'),
        BUGINESE			= make_tag('B','u','g','i'),
        COPTIC			    = make_tag('C','o','p','t'),
        GLAGOLITIC		    = make_tag('G','l','a','g'),
        KHAROSHTHI		    = make_tag('K','h','a','r'),
        NEW_TAI_LUE		    = make_tag('T','a','l','u'),
        OLD_PERSIAN		    = make_tag('X','p','e','o'),
        SYLOTI_NAGRI		= make_tag('S','y','l','o'),
        TIFINAGH			= make_tag('T','f','n','g'),
        BALINESE			= make_tag('B','a','l','i'),
        CUNEIFORM		    = make_tag('X','s','u','x'),
        NKO				    = make_tag('N','k','o','o'),
        PHAGS_PA			= make_tag('P','h','a','g'),
        PHOENICIAN		    = make_tag('P','h','n','x'),
        CARIAN			    = make_tag('C','a','r','i'),
        CHAM			    = make_tag('C','h','a','m'),
        KAYAH_LI			= make_tag('K','a','l','i'),
        LEPCHA			    = make_tag('L','e','p','c'),
        LYCIAN			    = make_tag('L','y','c','i'),
        LYDIAN			    = make_tag('L','y','d','i'),
        OL_CHIKI			= make_tag('O','l','c','k'),
        REJANG			    = make_tag('R','j','n','g'),
        SAURASHTRA		    = make_tag('S','a','u','r'),
        SUNDANESE		    = make_tag('S','u','n','d'),
        VAI				    = make_tag('V','a','i','i'),
        AVESTAN			    = make_tag('A','v','s','t'),
        BAMUM			    = make_tag('B','a','m','u'),
        EGYPTIAN_HIEROGLYPHS= make_tag('E','g','y','p'),
        IMPERIAL_ARAMAIC	= make_tag('A','r','m','i'),
        INSCRIPTIONAL_PAHLAVI= make_tag('P','h','l','i'),
        INSCRIPTIONAL_PARTHIAN= make_tag('P','r','t','i'),
        JAVANESE			= make_tag('J','a','v','a'),
        KAITHI			    = make_tag('K','t','h','i'),
        LISU			    = make_tag('L','i','s','u'),
        MEETEI_MAYEK		= make_tag('M','t','e','i'),
        OLD_SOUTH_ARABIAN   = make_tag('S','a','r','b'),
        OLD_TURKIC		    = make_tag('O','r','k','h'),
        SAMARITAN		    = make_tag('S','a','m','r'),
        TAI_THAM			= make_tag('L','a','n','a'),
        TAI_VIET			= make_tag('T','a','v','t'),
        BATAK			    = make_tag('B','a','t','k'),
        BRAHMI			    = make_tag('B','r','a','h'),
        MANDAIC			    = make_tag('M','a','n','d'),
        CHAKMA			    = make_tag('C','a','k','m'),
        MEROITIC_CURSIVE	= make_tag('M','e','r','c'),
        MEROITIC_HIEROGLYPHS= make_tag('M','e','r','o'),
        MIAO			    = make_tag('P','l','r','d'),
        SHARADA			    = make_tag('S','h','r','d'),
        SORA_SOMPENG		= make_tag('S','o','r','a'),
        TAKRI			    = make_tag('T','a','k','r'),
        BASSA_VAH		    = make_tag('B','a','s','s'),
        CAUCASIAN_ALBANIAN  = make_tag('A','g','h','b'),
        DUPLOYAN			= make_tag('D','u','p','l'),
        ELBASAN			    = make_tag('E','l','b','a'),
        GRANTHA			    = make_tag('G','r','a','n'),
        KHOJKI			    = make_tag('K','h','o','j'),
        KHUDAWADI		    = make_tag('S','i','n','d'),
        LINEAR_A			= make_tag('L','i','n','a'),
        MAHAJANI			= make_tag('M','a','h','j'),
        MANICHAEAN		    = make_tag('M','a','n','i'),
        MENDE_KIKAKUI	    = make_tag('M','e','n','d'),
        MODI		    	= make_tag('M','o','d','i'),
        MRO				    = make_tag('M','r','o','o'),
        NABATAEAN		    = make_tag('N','b','a','t'),
        OLD_NORTH_ARABIAN   = make_tag('N','a','r','b'),
        OLD_PERMIC		    = make_tag('P','e','r','m'),
        PAHAWH_HMONG		= make_tag('H','m','n','g'),
        PALMYRENE		    = make_tag('P','a','l','m'),
        PAU_CIN_HAU		    = make_tag('P','a','u','c'),
        PSALTER_PAHLAVI	    = make_tag('P','h','l','p'),
        SIDDHAM			    = make_tag('S','i','d','d'),
        TIRHUTA			    = make_tag('T','i','r','h'),
        WARANG_CITI		    = make_tag('W','a','r','a'),
        AHOM			    = make_tag('A','h','o','m'),
        ANATOLIAN_HIEROGLYPHS= make_tag('H','l','u','w'),
        HATRAN			    = make_tag('H','a','t','r'),
        MULTANI			    = make_tag('M','u','l','t'),
        OLD_HUNGARIAN	    = make_tag('H','u','n','g'),
        SIGNWRITING		    = make_tag('S','g','n','w'),
        ADLAM			    = make_tag('A','d','l','m'),
        BHAIKSUKI		    = make_tag('B','h','k','s'),
        MARCHEN			    = make_tag('M','a','r','c'),
        OSAGE			    = make_tag('O','s','g','e'),
        TANGUT			    = make_tag('T','a','n','g'),
        NEWA			    = make_tag('N','e','w','a'),
        MASARAM_GONDI	    = make_tag('G','o','n','m'),
        NUSHU			    = make_tag('N','s','h','u'),
        SOYOMBO			    = make_tag('S','o','y','o'),
        ZANABAZAR_SQUARE	= make_tag('Z','a','n','b'),
        DOGRA			    = make_tag('D','o','g','r'),
        GUNJALA_GONDI	    = make_tag('G','o','n','g'),
        HANIFI_ROHINGYA	    = make_tag('R','o','h','g'),
        MAKASAR			    = make_tag('M','a','k','a'),
        MEDEFAIDRIN		    = make_tag('M','e','d','f'),
        OLD_SOGDIAN		    = make_tag('S','o','g','o'),
        SOGDIAN			    = make_tag('S','o','g','d'),
        ELYMAIC			    = make_tag('E','l','y','m'),
        NANDINAGARI		    = make_tag('N','a','n','d'),
        NYIAKENG_PUACHUE_HMONG= make_tag('H','m','n','p'),
        WANCHO			    = make_tag('W','c','h','o'),
        CHORASMIAN		    = make_tag('C','h','r','s'),
        DIVES_AKURU		    = make_tag('D','i','a','k'),
        KHITAN_SMALL_SCRIPT = make_tag('K','i','t','s'),
        YEZIDI			    = make_tag('Y','e','z','i'),
        CYPRO_MINOAN		= make_tag('C','p','m','n'),
        OLD_UYGHUR		    = make_tag('O','u','g','r'),
        TANGSA			    = make_tag('T','n','s','a'),
        TOTO			    = make_tag('T','o','t','o'),
        VITHKUQI			= make_tag('V','i','t','h'),
        MATH		    	= make_tag('Z','m','t','h'),
        KAWI			    = make_tag('K','a','w','i'),
        NAG_MUNDARI		    = make_tag('N','a','g','m'),
        GARAY			    = make_tag('G','a','r','a'),
        GURUNG_KHEMA		= make_tag('G','u','k','h'),
        KIRAT_RAI		    = make_tag('K','r','a','i'),
        OL_ONAL			    = make_tag('O','n','a','o'),
        SUNUWAR			    = make_tag('S','u','n','u'),
        TODHRI			    = make_tag('T','o','d','r'),
        TULU_TIGALARI	    = make_tag('T','u','t','g'),
        BERIA_ERFE		    = make_tag('B','e','r','f'),
        SIDETIC			    = make_tag('S','i','d','t'),
        TAI_YO			    = make_tag('T','a','y','o'),
        TOLONG_SIKI		    = make_tag('T','o','l','s'),
        INVALID			    = tag_none(),
        _MAX_VALUE          = tag_max_signed()
    };

}}//qor::unicode

#endif//QOR_PP_H_TEXT_UNICODE_SCRIPTS