// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include "src/qor/module/module.h"
#include "src/qor/interception/functioncontext.h"
#include "src/qor/error/error.h"

//Windows specific headers must be last to prevent contaminating generic headers with Windows specific types and definitions
#include "gdi32.h"
#include "../returncheck.h"
#include "../library.h"

namespace qor { namespace nswindows { namespace api {

    BOOL GDI32::AngleArc(HDC hdc, int X, int Y, DWORD dwRadius, FLOAT eStartAngle, FLOAT eSweepAngle)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, AngleArc);
        return Library::Call< BOOL, HDC, int, int, DWORD, FLOAT, FLOAT >(pFunc, hdc, X, Y, dwRadius, eStartAngle, eSweepAngle);
    }

    BOOL GDI32::Arc(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect, int nXStartArc, int nYStartArc, int nXEndArc, int nYEndArc)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, Arc);
        return Library::Call< BOOL, HDC, int, int, int, int, int, int, int, int >(
            pFunc, hdc, nLeftRect, nTopRect, nRightRect, nBottomRect, nXStartArc, nYStartArc, nXEndArc, nYEndArc);
    }

    BOOL GDI32::ArcTo(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect, int nXRadial1, int nYRadial1, int nXRadial2, int nYRadial2)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, ArcTo);
        return Library::Call< BOOL, HDC, int, int, int, int, int, int, int, int >(
            pFunc, hdc, nLeftRect, nTopRect, nRightRect, nBottomRect, nXRadial1, nYRadial1, nXRadial2, nYRadial2);
    }

    int GDI32::GetArcDirection(HDC hdc)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, GetArcDirection);
        return Library::Call< int, HDC >(pFunc, hdc);
    }

    BOOL GDI32::LineDDA(int nXStart, int nYStart, int nXEnd, int nYEnd, ::LINEDDAPROC lpLineFunc, LPARAM lpData)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, LineDDA);
        return Library::Call< BOOL, int, int, int, int, ::LINEDDAPROC, LPARAM >(pFunc, nXStart, nYStart, nXEnd, nYEnd, lpLineFunc, lpData);
    }

    BOOL GDI32::LineTo(HDC hdc, int nXEnd, int nYEnd)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, LineTo);
        return Library::Call< BOOL, HDC, int, int >(pFunc, hdc, nXEnd, nYEnd);
    }

    BOOL GDI32::MoveToEx(HDC hdc, int X, int Y, ::LPPOINT lpPoint)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, MoveToEx);
        return Library::Call< BOOL, HDC, int, int, ::LPPOINT >(pFunc, hdc, X, Y, lpPoint );
    }

    BOOL GDI32::PolyBezier(HDC hdc, CONST::POINT* lppt, DWORD cPoints)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, PolyBezier);
        return Library::Call< BOOL, HDC, CONST ::POINT*, DWORD >(pFunc, hdc, lppt, cPoints);
    }

    BOOL GDI32::PolyBezierTo(HDC hdc, CONST::POINT* lppt, DWORD cCount)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, PolyBezierTo);
        return Library::Call< BOOL, HDC, CONST ::POINT*, DWORD >(pFunc, hdc, lppt, cCount);
    }

    BOOL GDI32::PolyDraw(HDC hdc, CONST::POINT* lppt, CONST BYTE* lpbTypes, int cCount)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, PolyDraw);
        return Library::Call< BOOL, HDC, CONST ::POINT*, CONST BYTE*, int >(pFunc, hdc, lppt, lpbTypes, cCount);
    }

    BOOL GDI32::Polyline(HDC hdc, CONST::POINT* lppt, int cPoints)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, Polyline);
        return Library::Call< BOOL, HDC, CONST ::POINT*, int >(pFunc, hdc, lppt, cPoints);
    }

    BOOL GDI32::PolylineTo(HDC hdc, CONST::POINT* lppt, DWORD cCount)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, PolylineTo);
        return Library::Call< BOOL, HDC, CONST ::POINT*, DWORD >(pFunc, hdc, lppt, cCount);
    }

    BOOL GDI32::PolyPolyline(HDC hdc, CONST::POINT* lppt, CONST DWORD* lpdwPolyPoints, DWORD cCount)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, PolyPolyline);
        return Library::Call< BOOL, HDC, CONST ::POINT*, CONST DWORD*, DWORD >(pFunc, hdc, lppt, lpdwPolyPoints, cCount);
    }

    int GDI32::SetArcDirection(HDC hdc, int ArcDirection)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, SetArcDirection);
        return Library::Call< int, HDC, int >(pFunc, hdc, ArcDirection);
    }

    BOOL GDI32::Chord(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect, int nXRadial1, int nYRadial1, int nXRadial2, int nYRadial2)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, Chord);
        return Library::Call< BOOL, HDC, int, int, int, int, int, int, int, int >(
            pFunc, hdc, nLeftRect, nTopRect, nRightRect, nBottomRect, nXRadial1, nYRadial1, nXRadial2, nYRadial2);
    }

    BOOL GDI32::Ellipse(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, Ellipse);
        return Library::Call< BOOL, HDC, int, int, int, int >(pFunc, hdc, nLeftRect, nTopRect, nRightRect, nBottomRect);
    }

    BOOL GDI32::Pie(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect, int nXRadial1, int nYRadial1, int nXRadial2, int nYRadial2)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, Pie);
        return Library::Call< BOOL, HDC, int, int, int, int, int, int, int, int >(
            pFunc, hdc, nLeftRect, nTopRect, nRightRect, nBottomRect, nXRadial1, nYRadial1, nXRadial2, nYRadial2);
    }

    BOOL GDI32::Polygon(HDC hdc, CONST::POINT* lpPoints, int nCount)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, Polygon);
        return Library::Call< BOOL, HDC, CONST ::POINT*, int >(pFunc, hdc, lpPoints, nCount);
    }

    BOOL GDI32::PolyPolygon(HDC hdc, CONST::POINT* lpPoints, CONST INT* lpPolyCounts, int nCount)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, PolyPolygon);
        return Library::Call< BOOL, HDC, CONST ::POINT*, CONST INT*, int >(pFunc, hdc, lpPoints, lpPolyCounts, nCount);
    }

    BOOL GDI32::Rectangle(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, Rectangle);
        return Library::Call< BOOL, HDC, int, int, int, int >(pFunc, hdc, nLeftRect, nTopRect, nRightRect, nBottomRect);
    }

    BOOL GDI32::RoundRect(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect, int nWidth, int nHeight)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(gdi32, RoundRect);
        return Library::Call< BOOL, HDC, int, int, int, int, int, int >(
            pFunc, hdc, nLeftRect, nTopRect, nRightRect, nBottomRect, nWidth, nHeight);
    }

}}}//qor::nswindows::api

