// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include "src/qor/module/module.h"
#include "src/qor/interception/functioncontext.h"
#include "src/qor/error/error.h"

//Windows specific headers must be last to prevent contaminating generic headers with Windows specific types and definitions
#include "dwm.h"
#include "../returncheck.h"
#include "../library.h"

namespace qor { namespace nswindows { namespace api {

    HRESULT DWM::EnableBlurBehindWindow(HWND hWnd, const DWM_BLURBEHIND* pBlurBehind)
    {
        qor_pp_fcontext;        
        qor_pp_useswinapi(dwmapi, DwmEnableBlurBehindWindow);
        return Library::Call<HRESULT, HWND, const DWM_BLURBEHIND*>(pFunc, hWnd, pBlurBehind);
    }

    HRESULT DWM::EnableComposition(bool enable)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmEnableComposition);
        return Library::Call<HRESULT, UINT>(pFunc, enable ? DWM_EC_ENABLECOMPOSITION : DWM_EC_DISABLECOMPOSITION);
    }

    HRESULT DWM::EnableMMCSS(bool enableMMCSS)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmEnableMMCSS);
        return Library::Call<HRESULT, BOOL>(pFunc, enableMMCSS ? TRUE : FALSE);
    }

    HRESULT DWM::ExtendFrameIntoClientArea(HWND hWnd, const MARGINS* pMarInset)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmExtendFrameIntoClientArea);
        return Library::Call<HRESULT, HWND, const MARGINS*>(pFunc, hWnd, pMarInset);
    }

    HRESULT DWM::Flush()
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmFlush);
        return Library::Call<HRESULT>(pFunc);
    }

    HRESULT DWM::GetColorizationColor(DWORD* pcrColorization,BOOL* pfOpaqueBlend)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmGetColorizationColor);
        return Library::Call<HRESULT, DWORD*, BOOL*>( pFunc, pcrColorization, pfOpaqueBlend);
    }

    HRESULT DWM::GetCompositionTimingInfo(DWM_TIMING_INFO *pTimingInfo)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmGetCompositionTimingInfo);
        return Library::Call<HRESULT, HWND, DWM_TIMING_INFO*>(pFunc, NULL, pTimingInfo);
    }

    HRESULT DWM::GetTransportAttributes(BOOL* pfIsRemoting, BOOL* pfIsConnected, DWORD* pDwGeneration)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmGetTransportAttributes);
        return Library::Call<HRESULT, BOOL*, BOOL*, DWORD*>(pFunc, pfIsRemoting, pfIsConnected, pDwGeneration);
    }

    HRESULT DWM::GetWindowAttribute(HWND hwnd,DWORD dwAttribute, PVOID pvAttribute, DWORD cbAttribute)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmGetWindowAttribute);
        return Library::Call<HRESULT, HWND, DWORD, PVOID, DWORD>(pFunc, hwnd, dwAttribute, pvAttribute, cbAttribute);
    }

    HRESULT DWM::InvalidateIconicBitmaps(HWND hwnd)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmInvalidateIconicBitmaps);
        return Library::Call<HRESULT, HWND>(pFunc, hwnd);
    }

    HRESULT DWM::IsCompositionEnabled(BOOL* pfEnabled)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmIsCompositionEnabled);
        return Library::Call<HRESULT, BOOL*>(pFunc, pfEnabled);
    }

    HRESULT DWM::QueryThumbnailSourceSize(HTHUMBNAIL hThumbnail, PSIZE pSize)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmQueryThumbnailSourceSize);
        return Library::Call<HRESULT, HTHUMBNAIL, PSIZE>(pFunc, hThumbnail, pSize);
    }

    HRESULT DWM::RegisterThumbnail(HWND hwndDestination, HWND hwndSource, PHTHUMBNAIL phThumbnailId)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmRegisterThumbnail);
        return Library::Call<HRESULT, HWND, HWND, PHTHUMBNAIL>(pFunc, hwndDestination, hwndSource, phThumbnailId);
    }

    HRESULT DWM::RenderGesture(GESTURE_TYPE gt, UINT cContacts, const DWORD* pdwPointerID, const POINT* pPoints)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmRenderGesture);
        return Library::Call<HRESULT, GESTURE_TYPE, UINT, const DWORD*, const POINT*>(pFunc, gt, cContacts, pdwPointerID, pPoints);
    }

    HRESULT DWM::SetIconicLivePreviewBitmap(HWND hwnd, HBITMAP hbmp, POINT* pptClient, DWORD dwSITFlags)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmSetIconicLivePreviewBitmap);
        return Library::Call<HRESULT, HWND, HBITMAP, POINT*, DWORD>(pFunc, hwnd, hbmp, pptClient, dwSITFlags);
    }

    HRESULT DWM::SetIconicThumbnail(HWND hwnd, HBITMAP hbmp, DWORD dwSITFlags)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmSetIconicThumbnail);
        return Library::Call<HRESULT, HWND, HBITMAP, DWORD>(pFunc, hwnd, hbmp, dwSITFlags);
    }

    HRESULT DWM::SetWindowAttribute(HWND hwnd, DWORD dwAttribute, LPCVOID pvAttribute, DWORD cbAttribute)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmSetWindowAttribute);
        return Library::Call<HRESULT, HWND, DWORD, LPCVOID, DWORD>(pFunc, hwnd, dwAttribute, pvAttribute, cbAttribute);
    }

    HRESULT DWM::ShowContact(DWORD dwPointerID, DWM_SHOWCONTACT eShowContact)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmShowContact);
        return Library::Call<HRESULT, DWORD, DWM_SHOWCONTACT>(pFunc, dwPointerID, eShowContact);
    }

    HRESULT DWM::TetherContact(DWORD dwPointerID, BOOL fEnable, POINT ptTether)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmTetherContact);
        return Library::Call<HRESULT, DWORD, BOOL, POINT>(pFunc, dwPointerID, fEnable, ptTether);
    }

    HRESULT DWM::TransitionOwnedWindow(HWND hwnd, DWMTRANSITION_OWNEDWINDOW_TARGET target)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmTransitionOwnedWindow);
        return Library::Call<HRESULT, HWND, DWMTRANSITION_OWNEDWINDOW_TARGET>(pFunc, hwnd, target);
    }

    HRESULT DWM::UnregisterThumbnail(HTHUMBNAIL hThumbnailId)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmUnregisterThumbnail);
        return Library::Call<HRESULT, HTHUMBNAIL>(pFunc, hThumbnailId);
    }

    HRESULT DWM::UpdateThumbnailProperties(HTHUMBNAIL hThumbnailId, const DWM_THUMBNAIL_PROPERTIES* ptnProperties)
    {
        qor_pp_fcontext;
        qor_pp_useswinapi(dwmapi, DwmUpdateThumbnailProperties);
        return Library::Call<HRESULT, HTHUMBNAIL, const DWM_THUMBNAIL_PROPERTIES*>(pFunc, hThumbnailId, ptnProperties);
    }

}}}//qor::nswindows::api
