// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "src/qor/error/error.h"

#include "touchcontroller.h"
#include "../touch.h"
#include "../surface.h"

namespace qor{ namespace platform { namespace nslinux{ namespace wl{

    TouchController::TouchController(ref_of<Touch>::type touch) : m_touch(touch)
    {
        if(m_touch)
        {
            connect(*m_touch, &Touch::DownEvent, *this, &TouchController::OnDown);
            connect(*m_touch, &Touch::UpEvent, *this, &TouchController::OnUp);
            connect(*m_touch, &Touch::MotionEvent, *this, &TouchController::OnMotion);
            connect(*m_touch, &Touch::FrameEvent, *this, &TouchController::OnFrame);
            connect(*m_touch, &Touch::CancelEvent, *this, &TouchController::OnCancel);
        }
        else
        {
            continuable("No touch specified for new TouchController.");
        }
    }

    TouchController::~TouchController()
    {
        if(m_touch)
        {
            disconnect(*m_touch, &Touch::CancelEvent, *this, &TouchController::OnCancel);
            disconnect(*m_touch, &Touch::FrameEvent, *this, &TouchController::OnFrame);
            disconnect(*m_touch, &Touch::MotionEvent, *this, &TouchController::OnMotion);
            disconnect(*m_touch, &Touch::UpEvent, *this, &TouchController::OnUp);
            disconnect(*m_touch, &Touch::DownEvent, *this, &TouchController::OnDown);
        }
    }

    void TouchController::OnDown(uint32_t serial, uint32_t time, Surface* surface, int32_t id, int32_t x_w, int32_t y_w)
    {

    }

    void TouchController::OnUp(uint32_t serial, uint32_t time, int32_t id)
    {

    }

    void TouchController::OnMotion(uint32_t time, int32_t id, int32_t x_w, int32_t y_w)
    {

    }

    void TouchController::OnFrame()
    {

    }

    void TouchController::OnCancel()
    {

    }

}}}}//qor::platform::nslinux::wl
