// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_FRAMEWORK_RESOURCES_JSONRESOURCE
#define QOR_PP_H_FRAMEWORK_RESOURCES_JSONRESOURCE

#include <string>

#include "../../resource.h"
#include "src/platform/filesystem/path.h"
#include "src/platform/filesystem/fileindex.h"
#include "src/components/json/nodes/object.h"

namespace qor{ namespace framework{ namespace res {

    class qor_pp_module_interface(QOR_RESOURCES) JSON : public Resource
    {
    public:

        static const char* StaticType();

        JSON(ResourceManager* manager, const qor::platform::FileIndex& index) : Resource(manager), m_index(index)
        {            
            Name();
        }
        
        virtual ~JSON() = default;

        virtual const char* Type();
        virtual void Name();
        virtual void Locate();
        virtual void Claim();
        
        qor::ref_of<qor::components::json::Object>::type GetObject();
        
    protected:

        const qor::platform::FileIndex m_index;
        qor::ref_of<qor::components::json::Object>::type m_object;
        
    private:
        static const char* s_jsonResourceType;
        
    };

}}}//qor::framework::res

#endif//QOR_PP_H_FRAMEWORK_RESOURCES_JSONRESOURCE