// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_COMPONENTS_PARSER_TOKENS
#define QOR_PP_H_COMPONENTS_PARSER_TOKENS

#include <map>
#include <string>

namespace qor { namespace components { namespace parser {

    enum class eToken : uint64_t
    {
        Lexical = 0,
        Octet = 1ull << 32,
        CarriageReturn,
        LineFeed,
        HorizontalTab,
        DoubleQuote,
        Space,
        Digit,
        VisibleChar,
        Control,
        HexDigit,
        WhiteSpace,
        LinearWhiteSpace,
        CarriageReturnLineFeed,
        Bit,
        Char,
        Alpha,

        Max,
    };

    inline const std::map<uint64_t, std::string> tokenNames = {{
        {static_cast< uint64_t>(eToken::Lexical), "Lexical"},
        {static_cast< uint64_t>(eToken::Octet), "Octet"},
        {static_cast< uint64_t>(eToken::CarriageReturn), "CarriageReturn"},
        {static_cast< uint64_t>(eToken::LineFeed), "LineFeed"},
        {static_cast< uint64_t>(eToken::HorizontalTab), "HorizontalTab"},
        {static_cast< uint64_t>(eToken::DoubleQuote), "DoubleQuote"},
        {static_cast< uint64_t>(eToken::Space), "Space"},
        {static_cast< uint64_t>(eToken::Digit), "Digit"},
        {static_cast< uint64_t>(eToken::VisibleChar), "VisibleChar"},
        {static_cast< uint64_t>(eToken::Control), "Control"},
        {static_cast< uint64_t>(eToken::HexDigit), "HexDigit"},
        {static_cast< uint64_t>(eToken::WhiteSpace), "WhiteSpace"},
        {static_cast< uint64_t>(eToken::LinearWhiteSpace), "LinearWhiteSpace"},
        {static_cast< uint64_t>(eToken::CarriageReturnLineFeed), "CarriageReturnLineFeed"},
        {static_cast< uint64_t>(eToken::Bit), "Bit"},
        {static_cast< uint64_t>(eToken::Char), "Char"},
        {static_cast< uint64_t>(eToken::Alpha), "Alpha"},
    }};

}}}//qor::components::parser

#endif//QOR_PP_H_COMPONENTS_PARSER_TOKENS