// Copyright Querysoft Limited 2008 - Present
// SPDX-License-Identifier: BSL-1.0

#ifndef QOR_PP_H_MPL_MPL
#define QOR_PP_H_MPL_MPL

#include "algorithm/all.h"
#include "algorithm/any.h"
#include "algorithm/combinations.h"
#include "algorithm/countif.h"
#include "algorithm/extreme.h"
#include "algorithm/filter.h"
#include "algorithm/findif.h"
#include "algorithm/flatten.h"
#include "algorithm/foldleft.h"
#include "algorithm/foldright.h"
#include "algorithm/group.h"
#include "algorithm/none.h"
#include "algorithm/partition.h"
#include "algorithm/product.h"
#include "algorithm/removeadjacent.h"
#include "algorithm/removeif.h"
#include "algorithm/replaceif.h"
#include "algorithm/reverse.h"
#include "algorithm/rotate.h"
#include "algorithm/sort.h"
#include "algorithm/splitif.h"
#include "algorithm/stablesort.h"
#include "algorithm/transform.h"
#include "algorithm/zipwith.h"

//#include "compatability/compatability.hpp"
#include "compatability/dependentcall.h"

#include "functional/bind.h"
#include "functional/call.h"
#include "functional/compose.h"
#include "functional/flow.h"
#include "functional/fork.h"
#include "functional/identity.h"

#include "functions/arithmetic/decrement.h"
#include "functions/arithmetic/divide.h"
#include "functions/arithmetic/increment.h"
#include "functions/arithmetic/invert.h"
#include "functions/arithmetic/max.h"
#include "functions/arithmetic/min.h"
#include "functions/arithmetic/minus.h"
#include "functions/arithmetic/modulo.h"
#include "functions/arithmetic/negate.h"
#include "functions/arithmetic/plus.h"
#include "functions/arithmetic/times.h"
#include "functions/bitwise/bitwiseand.h"
#include "functions/bitwise/bitwisecomplement.h"
#include "functions/bitwise/bitwiseor.h"
#include "functions/bitwise/bitwiseshl.h"
#include "functions/bitwise/bitwiseshr.h"
#include "functions/bitwise/bitwisexor.h"
#include "functions/comparison/equal.h"
#include "functions/comparison/greaterthanorequal.h"
#include "functions/comparison/greaterthan.h"
#include "functions/comparison/lessthanorequal.h"
#include "functions/comparison/lessthan.h"
#include "functions/comparison/notequal.h"
#include "functions/logical/logicaland.h"
#include "functions/logical/logicalnot.h"
#include "functions/logical/logicalor.h"

#include "sequence/at.h"
#include "sequence/drop.h"
#include "sequence/erase.h"
#include "sequence/front.h"
#include "sequence/insert.h"
#include "sequence/islist.h"
#include "sequence/join.h"
#include "sequence/lookup.h"
#include "sequence/popfront.h"
#include "sequence/makesequence.h"
#include "sequence/pushback.h"
#include "sequence/pushfront.h"
#include "sequence/size.h"
#include "sequence/take.h"

#include "bool.h"
#include "int.h"
#include "integralconstant.h"
#include "list.h"
#include "nothing.h"
#include "../traits/typetraits.h"

#include "always.h"
#include "conditional.h"
#include "isinstance.h"
#include "sameas.h"

#endif//QOR_PP_H_MPL_MPL
