// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include <filesystem>
#include "stat.h"

namespace qor{ namespace io{ namespace filesystem {
        
    Stat::Stat(const Index& index) : m_index(index){ }
    
    bool Stat::IsBlockFile()
    {
        return std::filesystem::is_block_file(m_index.GetPath());
    }

    bool Stat::IsCharacterFile()
    {
        return std::filesystem::is_character_file(m_index.GetPath());
    }

    bool Stat::IsDir()
    {
        return std::filesystem::is_directory(m_index.GetPath());
    }

    bool Stat::IsEmpty()
    {
        return std::filesystem::is_empty(m_index.GetPath());
    }

    bool Stat::IsFIFO()
    {
        return std::filesystem::is_fifo(m_index.GetPath());
    }

    bool Stat::IsOther()
    {
        return std::filesystem::is_other(m_index.GetPath());
    }

    bool Stat::IsRegularFile()
    {
        return std::filesystem::is_regular_file(m_index.GetPath());
    }

    bool Stat::IsSocket()
    {
        return std::filesystem::is_socket(m_index.GetPath());
    }

    bool Stat::IsSymLink()
    {
        return std::filesystem::is_symlink(m_index.GetPath());
    }

    bool Stat::IsValid() 
    { 
        return std::filesystem::exists(m_index.GetPath());
    }

    bool Stat::IsFile() 
    { 
        return std::filesystem::is_regular_file(m_index.GetPath());
    }    

}}}//qor::io::filesystem
