// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include <iostream>
#include <format>
#include "src/qor/error/error.h"
#include "defaultloghandler.h"

namespace qor {

    qor_pp_signal_func DefaultLogHandler::forward(std::string logMessage)//don't call this outgoing interface directly
    {
        qor_pp_emit(forward,logMessage);
    }

    DefaultLogHandler::forwardFn DefaultLogHandler::GetForwardSignal() 
    {
        return &DefaultLogHandler::forward;
    }

    DefaultLogHandler::DefaultLogHandler(log::Level logLevel) : qor::IssueHandler<log::Log>(), m_level(logLevel), m_writeToStandardOutput(false), m_forward(true)
    {
    }

    std::string DefaultLogHandler::WhereText(const char* module, const char* file, const char* function, int line, const std::string& exceptionText, const std::string& instanceText, const std::string& threadText) const
    {
        return std::format("Module: {0}| File: {1}| Function: {2}| Line: {3}| {4}| {5}| Thread: {6}", 
            module, 
            file, 
            function, 
            line,
            exceptionText,
            instanceText,
            threadText);

    }

    std::string DefaultLogHandler::InstanceText(bool inInstance, const qor::AnyObject& any) const
    {
        return inInstance ?
            std::format("Object at: {0}", any.Ptr()->operator void*()) : 
            "Free function";
    }

    std::string DefaultLogHandler::InExceptionText(bool inException) const
    {
        return inException ? "Exceptional flow" : "Normal flow";
    }

    std::string DefaultLogHandler::MessageText(const std::string_view& level, const std::string& what, const std::string& where, const std::chrono::time_point<std::chrono::high_resolution_clock, std::chrono::nanoseconds>& when) const
    {
        return std::vformat("{0}:time_point??: |{2} \"{1}\"\n", std::make_format_args(level, what, where/*, when*/));
    }

    DefaultLogHandler& DefaultLogHandler::Forward(bool forward)
    {
        m_forward = forward;
        return *this;    
    }

    DefaultLogHandler& DefaultLogHandler::WriteToStandardOutput(bool write)
    {
        m_writeToStandardOutput = write;
        return *this;
    }

    DefaultLogHandler& DefaultLogHandler::WriteToFileSystem()
    {
        //Look for a LogFileWriter to write to the filesystem for us
        return *this;
    }

    DefaultLogHandler& DefaultLogHandler::WriteToPipeline()
    {
        //Look for a LogPipelineWriter to write to a custom Pipeline for us
        return *this;
    }

    std::string DefaultLogHandler::GetWhereClause(const qor::log::Log& log) const
    {
        std::string where = "location unknown";
        if(log.HasWhere())
        {
            where = WhereText(log.where().GetModuleContext(),log.where().GetFile(),log.where().GetFunction(),log.where().GetLine(),
                InExceptionText(log.where().GetInException()), InstanceText(log.where().GetInInstance(), log.where().GetObjectContext()), 
                log.where().GetThreadContext());
        }
        return where;
    }

    bool DefaultLogHandler::Handle(const log::Log& log)
    { 
        if(m_level > log.what().GetLevel())
        {
            return false;
        }

        const std::string_view logLevel = log::LevelNames[(int)log.what().GetLevel()];
        std::string logMessage = MessageText(logLevel, log.what().Content(), GetWhereClause(log), log.when().TimePoint());
        
        if(m_forward)
        {
            forward(logMessage);
        }

        if(m_writeToStandardOutput)
        {
            std::cout << logMessage << std::endl;
        }

        return true;
    }

}//qor