// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_LOG_HANDLER
#define QOR_PP_H_LOG_HANDLER

#include "src/framework/thread/thread.h"
#include "src/qor/objectcontext/typedany.h"
#include "src/qor/reference/flyerref.h"
#include "src/qor/reference/reference.h"
#include "src/qor/injection/typeidentity.h"
#include "src/qor/datastructures/guid.h"
#include "src/qor/interception/callcontext.h"
#include "src/qor/interception/flyer.h"
#include "src/qor/interception/flystrapbase.h"
#include "src/qor/error/handler.h"
#include "log.h"
#include "debug.h"
#include "informative.h"
#include "important.h"
#include "impactful.h"
#include "imperative.h"

namespace qor{

    constexpr GUID LevelIssueHandlerGUID = {0xe45ea271, 0x7394, 0x42d2, {0x8f, 0xb8, 0xec, 0x2a, 0x08, 0x5b, 0x2b, 0xec}};
    qor_pp_declare_guid_of(IssueHandler<log::Log>,LevelIssueHandlerGUID)
    qor_pp_declare_ref_of(IssueHandler<log::Log>,FlyerRef);

    constexpr GUID DebugLogHandlerGUID = {0x12637a5c, 0x5ed4, 0x431a, {0xaf, 0x64, 0x70, 0x0a, 0x0e, 0x63, 0xfc, 0x20}};
    qor_pp_declare_guid_of(IssueHandler<log::Debug>,DebugLogHandlerGUID)
    qor_pp_declare_ref_of(IssueHandler<log::Debug>,FlyerRef);
    
    constexpr GUID InformativeLogHandlerGUID = {0x75b73265, 0x75f1, 0x434f, {0x89, 0xcf, 0x76, 0x1d, 0x3c, 0x1a, 0xf4, 0x0d}};
    qor_pp_declare_guid_of(IssueHandler<log::Informative>,InformativeLogHandlerGUID)
    qor_pp_declare_ref_of(IssueHandler<log::Informative>,FlyerRef);

    constexpr GUID ImportantLogHandlerGUID = {0xb75b9b44, 0x1b5b, 0x4a26, {0x9f, 0x13, 0xb6, 0x58, 0xfc, 0x6b, 0x19, 0xf7}};
    qor_pp_declare_guid_of(IssueHandler<log::Important>,ImportantLogHandlerGUID)
    qor_pp_declare_ref_of(IssueHandler<log::Important>,FlyerRef);

    constexpr GUID ImpactfulLogHandlerGUID = {0x7f96ad25, 0xac48, 0x4536, {0xbd, 0x55, 0xbf, 0x17, 0x8f, 0x5e, 0xd7, 0x5d}};
    qor_pp_declare_guid_of(IssueHandler<log::Impactful>,ImpactfulLogHandlerGUID)
    qor_pp_declare_ref_of(IssueHandler<log::Impactful>,FlyerRef);
    
    constexpr GUID ImperativeLogHandlerGUID = {0x34f13609, 0x7100, 0x4093, {0x95, 0xe0, 0x1d, 0xf9, 0x02, 0x0f, 0x12, 0x90}};
    qor_pp_declare_guid_of(IssueHandler<log::Imperative>,ImperativeLogHandlerGUID)
    qor_pp_declare_ref_of(IssueHandler<log::Imperative>,FlyerRef);

}//qor

#endif//QOR_PP_H_LOG_HANDLER
