// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_GL_JOYSTICK
#define QOR_PP_H_GL_JOYSTICK

#include <stdint.h>

namespace qor{ namespace gl{

    struct MapElement
    {
        uint8_t         type;
        uint8_t         index;
        int8_t          axisScale;
        int8_t          axisOffset;
    };

    struct Mapping
    {
        char            name[128];
        char            guid[33];
        MapElement      buttons[15];
        MapElement      axes[6];
    };

    class qor_pp_module_interface(QOR_GL) Joystick
    {
        friend class Input;

    public:

        Joystick() = default;
        virtual ~Joystick() = default;

        constexpr static const int JOYSTICK_1             = 0;
        constexpr static const int JOYSTICK_2             = 1;
        constexpr static const int JOYSTICK_3             = 2;
        constexpr static const int JOYSTICK_4             = 3;
        constexpr static const int JOYSTICK_5             = 4;
        constexpr static const int JOYSTICK_6             = 5;
        constexpr static const int JOYSTICK_7             = 6;
        constexpr static const int JOYSTICK_8             = 7;
        constexpr static const int JOYSTICK_9             = 8;
        constexpr static const int JOYSTICK_10            = 9;
        constexpr static const int JOYSTICK_11            = 10;
        constexpr static const int JOYSTICK_12            = 11;
        constexpr static const int JOYSTICK_13            = 12;
        constexpr static const int JOYSTICK_14            = 13;
        constexpr static const int JOYSTICK_15            = 14;
        constexpr static const int JOYSTICK_16            = 15;
        constexpr static const int JOYSTICK_LAST          = JOYSTICK_16;

    protected:

        int             allocated = {0};
        int             connected = {0};
        float*          axes = {nullptr};
        int             axisCount = {0};
        unsigned char*  buttons = {nullptr};
        int             buttonCount = {0};
        unsigned char*  hats = {nullptr};
        int             hatCount = {0};
        char            name[128];
        void*           userPointer = {nullptr};
        char            guid[33];
        Mapping*        mapping = {nullptr};

        // This is defined in platform.h
        //GLFW_PLATFORM_JOYSTICK_STATE
    };
}}//qor::gl

#endif//QOR_PP_H_GL_JOYSTICK