// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_COMPONENTS_NETWORK_SESSION_PIPELINE
#define QOR_PP_H_COMPONENTS_NETWORK_SESSION_PIPELINE

#include "src/framework/thread/currentthread.h"
#include "src/qor/reference/newref.h"
#include "src/framework/pipeline/pipeline.h"
#include "src/framework/pipeline/protocol.h"
#include "src/components/framework/pipeline/connectors/socketconnector/socketconnector.h"
#include "src/components/framework/pipeline/connectors/socketconnector/socketsessionsource.h"
#include "src/components/framework/pipeline/connectors/socketconnector/socketsessionsink.h"

namespace qor{ namespace components {

    class SessionPipeline : public qor::pipeline::Pipeline
    {
    public:

        SessionPipeline(
            qor::ref_of<qor::network::Socket>::type socket, 
            qor::ref_of<qor::framework::AsyncIOContext::Session>::type ioSession,
            qor::ref_of<qor::pipeline::Protocol>::type protocol
        ) :
            m_socket(socket), 
            m_ioSession(ioSession)
        {
            m_filter = protocol->GetFilter();
            
            m_socketSessionConnector = new_ref<SocketConnector>(m_socket, m_ioSession);
            SetFlowMode(Element::FlowMode::Push);

            m_socketSource = new_ref<SocketSessionSource>();
            m_socketSource->SetPlug(m_socketSessionConnector);
            SetSource(m_socketSource, m_filter.operator->());
            
            m_socketSink = new_ref<SocketSessionSink>();
            m_socketSink->SetPlug(m_socketSessionConnector);
            SetSink(m_socketSink, m_filter.operator->());

            m_socketSource->SetSink(m_socketSink);
            m_socketSink->SetSource(m_socketSource);
            GetSink()->GetBuffer()->SetCapacity(m_ioBufferSize);
            GetSource()->GetBuffer()->SetCapacity(m_ioBufferSize);
            m_socketSessionConnector->Connect();
        }

        virtual ~SessionPipeline()
        {
            m_socketSessionConnector->Disconnect();
        }

    private:

        const size_t m_ioBufferSize = 1024;
        qor::ref_of<qor::pipeline::InlineFilter<byte>>::type m_filter;
        qor::ref_of<qor::network::Socket>::type m_socket;
        qor::ref_of<qor::framework::AsyncIOContext::Session>::type m_ioSession;
        qor::ref_of<qor::components::SocketConnector>::type m_socketSessionConnector;
        qor::ref_of<qor::components::SocketSessionSource>::type m_socketSource;
        qor::ref_of<qor::components::SocketSessionSink>::type m_socketSink;

    };

}}//qor::components

#endif//QOR_PP_H_COMPONENTS_NETWORK_SESSION_PIPELINE