// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_COMPONENTS_FRAMEWORK_TUI_DOM_NODE
#define QOR_PP_H_COMPONENTS_FRAMEWORK_TUI_DOM_NODE

#include <memory>
#include <vector>

#include "requirement.h"
#include "selection.h"
#include "../screen/box.h"
#include "../screen/screen.h"

namespace qor{ namespace components{ namespace tui {

    class Node;
    //class Screen;

    using Element = std::shared_ptr<Node>;
    using Elements = std::vector<Element>;

    // Node is the base class for all elements in the DOM tree.
    /// It typically contains child elements, which are also instances of Node.
    /// Users are expected to derive from this class to create custom elements.
    /// A list of builtin elements can be found in the `elements.hpp` file.
    class qor_pp_module_interface(QOR_TUI) Node 
    {
    public:
        Node();
        explicit Node(Elements children);
        Node(const Node&) = delete;
        Node(const Node&&) = delete;
        Node& operator=(const Node&) = delete;
        Node& operator=(const Node&&) = delete;

        virtual ~Node();

        // Step 1: Compute layout requirement. Tell parent what dimensions this element wants to be. Propagated from Children to Parents.
        virtual void ComputeRequirement();
        Requirement requirement() { return requirement_; }

        // Step 2: Assign this element its final dimensions. Propagated from Parents to Children.
        virtual void SetBox(Box box);

        // Step 3: (optional) Selection Propagated from Parents to Children.
        virtual void Select(Selection& selection);

        // Step 4: Draw this element.
        virtual void Render(Screen& screen);

        virtual std::string GetSelectedContent(Selection& selection);

        // Layout may not resolve within a single iteration for some elements. This
        // allows them to request additionnal iterations. This signal must be
        // forwarded to children at least once.
        struct Status 
        {
            int iteration = 0;
            bool need_iteration = false;
        };

        virtual void Check(Status* status);
        friend qor_pp_module_interface(QOR_TUI) void Render(Screen& screen, Node* node, Selection& selection);

    protected:
            Elements children_;
            Requirement requirement_;
            Box box_;
    };

    qor_pp_module_interface(QOR_TUI) void Render(Screen& screen, const Element& element);
    qor_pp_module_interface(QOR_TUI) void Render(Screen& screen, Node* node);
    qor_pp_module_interface(QOR_TUI) void Render(Screen& screen, Node* node, Selection& selection);
    qor_pp_module_interface(QOR_TUI) std::string GetNodeSelectedContent(Screen& screen, Node* node, Selection& selection);

}}}//qor::components::tui

#endif//QOR_PP_H_COMPONENTS_FRAMEWORK_TUI_DOM_NODE

