// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_INSTANCE_POOL
#define QOR_PP_H_INSTANCE_POOL

#include <stddef.h>
#include <list>
#include "src/qor/reference/reference.h"
#include "src/qor/factory/factory.h"
#include "src/qor/sync/recursive_mutex.h"
#include "src/qor/sync/lock.h"

//The pool instancer gives out one of a limited pool of reusable resources

namespace qor{

    template<typename T>
    struct pool_size_of
    {
        static constexpr size_t size = 2;
    };

    namespace detail 
    {
        template <class T, size_t poolSize = pool_size_of<T>::size >
        class PoolInstanceHolder final
        {
        public:
            PoolInstanceHolder() : m_instanceCount(0), maxCount(poolSize) {}

            ~PoolInstanceHolder()
            {
                Lock lock(m);
                Drain();
            }

            typename ref_of<T>::type Instance()
            {
                Lock lock(m);
                typename ref_of<T>::type instance;
                if(m_FreeList.size() > 0)
                {
                    auto it = m_FreeList.begin();
                    instance = factory_of<T>::type::ConstructFromExisting(*it);
                    m_FreeList.erase(m_FreeList.begin());
                }
                else
                {
                    if(m_instanceCount < maxCount)
                    {                        
                        instance = factory_of<T>::type::Construct();
                        ++m_instanceCount;
                    }
                }
                return instance;
            }

            template<typename... _p >
            typename ref_of<T>::type Instance(size_t count, _p&&... p1)
            {
                Lock lock(m);
                typename ref_of<T>::type instance;
                if(m_FreeList.size() > 0)
                {
                    auto it = m_FreeList.begin();
                    instance = factory_of<T>::type::ConstructFromExisting(*it);
                    m_FreeList.erase(m_FreeList.begin());
                    instance->Inflate();
                }
                else
                {
                    if(m_instanceCount < maxCount)
                    {                        
                        instance = factory_of<T>::type::Construct(count, std::forward<_p>(p1)...);
                        m_instanceCount += count;
                    }
                }
                return instance;
            }
               
            void Release(T* pinstance)
            {
                Lock lock(m);
                pinstance->Deflate();
                m_FreeList.push_back(pinstance);
            }

            void SetSize(size_t max)
            {
                maxCount = max;
            }

            void Drain()
            {                
                Lock lock(m);
                for(T* pt : m_FreeList)
                {
                    factory_of<T>::type::Destruct(pt, 1);
                }
                m_FreeList.erase(m_FreeList.begin(), m_FreeList.end());
                m_instanceCount = 0;
            }

        private:
            size_t maxCount;
            std::list<T*> m_FreeList;
            size_t m_instanceCount;
            bool bInitialised;
            RecursiveMutex m;
        };

    }//detail
    
	class PoolInstancer final
	{
	public:

		template< class T >
		static inline void Release(T* pt, size_t count = 1)
		{
			Holder<T>().Release(pt);
		}

		template< class T >
		static inline auto Instance(size_t count = 1)
		{
            return Holder<T>().Instance();
		}

        template< class T, typename... _p >
		static inline auto Instance(size_t count, _p&&... p1)
		{
			return Holder<T>().Instance(count, std::forward<_p>(p1)...);
		}

        template< class T >
        static inline void SetPoolSize(size_t size)
        {
            return Holder<T>().SetSize(size);
        }

        template< class T >
        static inline void Drain()
        {
            return Holder<T>().Drain();
        }
		
	private:

        template< class T>
        static detail::PoolInstanceHolder<T, pool_size_of<T>::size >& Holder()
        {
            static detail::PoolInstanceHolder<T> holder;
            return holder;
        }

        PoolInstancer() = delete;
		~PoolInstancer() = delete;
	};

}//qor

#endif//QOR_PP_H_INSTANCE_SINGLETON
