// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "messagebox.h"

#include "src/platform/os/windows/api_layer/user/user32.h"

using namespace qor::win::api;

#undef MessageBox

namespace qor{ namespace platform { namespace win{
    
    MessageBox::MessageBox(ref_of<Window>::type window, const tstring& text, const tstring& caption, unsigned int type, unsigned long milliseconds)
    {                
        if(milliseconds == 0)
        {
            m_result = User32::MessageBoxT( (HWND)(window.IsNotNull() ? window->GetHandle().Use() : nullptr), text.c_str(), caption.c_str(), type);
        }
        else
        {
            unsigned short languageId = MAKELANGID(LANG_NEUTRAL, SUBLANG_NEUTRAL);
            m_result = User32::MessageBoxTimeout((HWND)(window.IsNotNull() ? window->GetHandle().Use() : nullptr), text.c_str(), caption.c_str(), type, languageId, milliseconds);
        }
    }

    MessageBox::MessageBox(MsgBoxParams& params)
    {
        m_result = User32::MessageBoxIndirectT(reinterpret_cast<const LPMSGBOXPARAMS>(&params));
    }

    int MessageBox::Result()
    {
        return m_result;
    }

}}}//qor::platform::win
