// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

//Defines the entry point for a DLL.
#include "src/configuration/configuration.h"

#if( qor_pp_os_target == qor_pp_os_windows)

#include "src/qor/module/module.h"

extern "C" __declspec(dllexport) int __stdcall DllMain(void* /*hModule*/, unsigned long ul_reason_for_call, void* /*lpReserved*/)
{
    qor::Module& module = ThisModule();
	switch (ul_reason_for_call)
	{
	case 1://DLL_PROCESS_ATTACH:
		return 1;//ThisModule().WindowsProcessAttach();
	case 2://DLL_THREAD_ATTACH:
		return 1;//ThisModule().WindowsThreadAttach();
	case 3://DLL_THREAD_DETACH:
		return 1;//ThisModule().WindowsThreadDetach();
	case 4://DLL_PROCESS_DETACH:
		return 1;//ThisModule().WindowsProcessDetach();
	default:
		return 0;
	}
}

#endif

