// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include <sys/mman.h>
#include <sys/syscall.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "sdk/using_framework.h"
#include "src/components/framework/ui/egl/egl.h"
#include "src/components/framework/ui/egl/display.h"
#include "src/components/framework/ui/egl/context.h"
#include "src/components/framework/ui/egl/window.h"
#include "src/components/framework/ui/egl/session.h"
#include "src/components/framework/ui/opengles/opengles.h"
#include "src/components/framework/ui/opengles/constants.h"
#include "src/components/framework/ui/renderer/thor.h"

#include "sdk/platform/os/linux/wayland.h"
#include "src/platform/os/linux/wayland/egl/eglwindow.h"
#include "src/platform/os/linux/egl/display.h"
#include "src/qor/delegate/bindmember.h"

using namespace qor::platform::nslinux;
using namespace qor::components;

#include "sharedmem.h"
#include "custompopup.h"
#include "customwindow.h"
#include "custompointercontroller.h"
#include "customkeyboardcontroller.h"

//Declare an EGL session type that wraps up Linux EGL on a Wayland Display
typedef EGLSessionWrapper<wl::XDGSession, EglDisplay> SessionType;      

int waylandExampleRun(ref_of<SessionType>::type session)
{
    std::vector<int32_t> contextAttributes = { EGL_CONTEXT_CLIENT_VERSION, 3, EGL_NONE};
    auto window = new_ref<CustomWindow>(session,contextAttributes, 0, 0, 640, 480);     //Create a Top Level EGL window
    window->SetTitle("Wayland EGL Example");                                            //Set window properties    
    customKeyboardController keycon(session);                                           //Setup a Keyboard controller to catch Esc and quit the Session    
    customPointerController pointercon(session, window);                                //Setup a Pointer controller to catch clicks
    while(!session->Ended())
    {     
        session->GetDisplay()->DispatchPending();
        window->DrawFrame();
        window->Present();
    }
    return 0;
}

int waylandExampleCommon()
{
    auto waylandClient = GetFeature<WaylandClient>();                   //Get a reference to the Wayland Client feature
    auto display = waylandClient(qor_shared).GetDisplay();              //Get the default local display
    auto session = new_ref<SessionType>(display);                       //Create an EGL enabled Session over a Wayland XDG Session
    return waylandExampleRun(session);
}

const char* appName = "wedge";
qor_pp_implement_module(appName)
qor_pp_module_requires(WaylandClient)
qor_pp_module_requires(EGLFeature)
qor_pp_module_requires(OpenGLESFeature)

int main(int argc, char **argv) 
{    
    auto wedgeApp = AppBuilder().Build(appName);

    wedgeApp->SetRole<Role>(
        [](ref_of<IRole>::type role)
        {
            role->AddFeature<WaylandClient>();
            role->AddFeature<EGLFeature>();
            role->AddFeature<OpenGLESFeature>();
        }
    ).Run(
        make_runable( 
            []()->int
            {
                int result = waylandExampleCommon();
                printf("Disconnected from display\n");
                return result;
            }
        )
    );
}