// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_DETECTOS
#define QOR_PP_H_DETECTOS

#include "systems.h"

#ifndef qor_pp_os_target

#   ifdef __linux__
#       define qor_pp_os_target qor_pp_os_linux
#   elif (defined _WIN32 || defined _WIN64)
#       define qor_pp_os_target qor_pp_os_windows
#   elif (defined __APPLE__)
#       define qor_pp_os_target qor_pp_os_mac
#   elif (defined __ANDROID__)
#       error Target operating system Android detected but not supported
#   elif (defined __FreeBSD__)
#       error Target operating system Free BSD detected but not supported
#   else
#       error Target operating system could not be detected from host. Please define qor_pp_os_target in your build system
//NOTE: Add additional OS detection here - see:https://sourceforge.net/p/predef/wiki/OperatingSystems/
#   endif

#endif//qor_pp_os_target

#if (qor_pp_os_target == qor_pp_os_linux)
#   define qor_pp_os_root_folder linux
//qor_pp_compiler_message( "Build targetting Linux Operating Systems." )
#elif (qor_pp_os_target == qor_pp_os_windows)

#   define qor_pp_os_root_folder windows
#   ifdef _WIN64
#       define qor_pp_os_64bit
qor_pp_compiler_message( "Build targetting 64 bit Microsoft Windows Operating Systems." )
#       else
qor_pp_compiler_message( "Build targetting 32 bit Microsoft Windows Operating Systems." )
#   endif

#elif (qor_pp_os_target == qor_pp_os_mac)
#   define qor_pp_os_root_folder mac
qor_pp_compiler_message( "Build targetting Apple Mac Operating Systems." )
#endif

#endif//QOR_PP_H_OS
