// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_COMPONENTS_PROTOCOLS_HTTP_REQUESTPARSER_AUTHORITYTOKEN
#define QOR_PP_H_COMPONENTS_PROTOCOLS_HTTP_REQUESTPARSER_AUTHORITYTOKEN

#include "src/components/parser/state.h"
#include "src/components/parser/rfc5234.h"
#include "tokendefs.h"
#include "src/components/parser/oneormore.h"
#include "src/components/parser/nodes/char.h"
#include "authoritynode.h"
#include "userinfotoken.h"
#include "hosttoken.h"
#include "porttoken.h"

namespace qor { namespace components { namespace protocols { namespace http {

    //authority     = [ userinfo "@" ] host [ ":" port ]
    class qor_pp_module_interface(QOR_HTTP) authority : public qor::components::parser::Sequence
    {
    public: authority(qor::components::parser::Parser* parser) :
                qor::components::parser::Sequence(parser,
                    new_ref<qor::components::parser::Optional>(parser,
                        new_ref<qor::components::parser::Sequence>(parser,
                            new_ref<userinfo>(parser),
                            new_ref<qor::components::parser::Specific>(parser,'@')
                        )
                    ),
                    new_ref<qor::components::parser::Sequence>(parser,
                        new_ref<host>(parser),
                        new_ref<qor::components::parser::Optional>(parser,
                            new_ref<qor::components::parser::Sequence>(parser,
                                new_ref<qor::components::parser::Specific>(parser,':'),
                                new_ref<port>(parser)
                            )
                        )
                    ),
                    static_cast<uint64_t>(httpRequestToken::authority)
                )
        {}

        virtual ~authority() = default;

        virtual void Prepare();
        virtual void Emit();
        virtual void Fail();

    };

}}}}//qor::components::protocols::http

#endif//QOR_PP_H_COMPONENTS_PROTOCOLS_HTTP_REQUESTPARSER_AUTHORITYTOKEN