// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_COMPONENTS_PROTOCOLS_HTTP_REQUESTPARSER_PATH_ROOTLESSNODE
#define QOR_PP_H_COMPONENTS_PROTOCOLS_HTTP_REQUESTPARSER_PATH_ROOTLESSNODE

#include <string>
#include <vector>

#include "src/components/parser/state.h"
#include "src/components/parser/rfc5234.h"
#include "tokendefs.h"
#include "src/components/parser/parser.h"
#include "src/components/parser/oneormore.h"
#include "src/components/parser/nodes/char.h"

namespace qor { namespace components { namespace protocols { namespace http {

    class PathRootless
    {       
    protected: 
        std::vector<std::string> m_segments;
    };

    class PathRootlessNode : public parser::NodeAdapter<PathRootless>
    {
    public:

        PathRootlessNode() : parser::NodeAdapter<PathRootless>(static_cast<uint64_t>(httpRequestToken::path_rootless))
        {
        }

        PathRootlessNode(ref_of<PathRootless>::type path_rootless) : parser::NodeAdapter<PathRootless>(path_rootless, static_cast<uint64_t>(httpRequestToken::path_rootless))
        {
        }

        virtual ~PathRootlessNode() = default;

    };

}}}}

#endif//QOR_PP_H_COMPONENTS_PROTOCOLS_HTTP_REQUESTPARSER_PATH_ROOTLESSNODE