// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_COMPONENTS_PROTOCOLS_HTTP_REQUESTPARSER_TOKENDEFS
#define QOR_PP_H_COMPONENTS_PROTOCOLS_HTTP_REQUESTPARSER_TOKENDEFS

#include <map>
#include <cstdint>
#include "src/components/parser/tokens.h"

namespace qor { namespace components { namespace protocols { namespace http {

    enum class httpRequestToken : uint64_t
    {
        requestChar = static_cast<uint64_t>(qor::components::parser::eToken::Max) + 1ull,
        tchar,
        unreserved,
        pct_encoded,
        sub_delims,
        pchar,
        token,
        query,
        segment_nz,
        method,
        scheme,
        uri_absolute_path,
        uri_origin_form,
        segment,
        path_abempty,
        path_rootless,
        dec_octet,
        IPv4address,
        reg_name,
        IP_literal,
        host,
        port,
        userinfo,
        authority,
        heir_part,
        uri_absolute_form,
        uri_authority_form,
        uri_asterisk_form,
        target,
        protocol,
        protocol_name,
        protocol_version,
        request_line,
        field_vchar,
        field_name,
        field_content,
        field_value,
        field_line,
        request,
    };

    static const std::map<const uint64_t, const std::string> httpRequestTokenNames = {{
        {static_cast< const uint64_t>(httpRequestToken::requestChar), "requestChar"},
        {static_cast< const uint64_t>(httpRequestToken::tchar), "tchar"},
        {static_cast< const uint64_t>(httpRequestToken::unreserved), "unreserved"},
        {static_cast< const uint64_t>(httpRequestToken::pct_encoded), "pct_encoded"},
        {static_cast< const uint64_t>(httpRequestToken::sub_delims), "sub_delims"},
        {static_cast< const uint64_t>(httpRequestToken::pchar), "pchar"},
        {static_cast< const uint64_t>(httpRequestToken::token), "token"},
        {static_cast< const uint64_t>(httpRequestToken::query), "query"},
        {static_cast< const uint64_t>(httpRequestToken::segment_nz), "segment_nz"},
        {static_cast< const uint64_t>(httpRequestToken::method), "method"},
        {static_cast< const uint64_t>(httpRequestToken::scheme), "scheme"},
        {static_cast< const uint64_t>(httpRequestToken::uri_absolute_path), "uri_absolute_path"},
        {static_cast< const uint64_t>(httpRequestToken::uri_origin_form), "uri_origin_form"},
        {static_cast< const uint64_t>(httpRequestToken::segment), "segment"},
        {static_cast< const uint64_t>(httpRequestToken::path_abempty), "path_abempty"},
        {static_cast< const uint64_t>(httpRequestToken::path_rootless), "path_rootless"},
        {static_cast< const uint64_t>(httpRequestToken::dec_octet), "dec_octet"},
        {static_cast< const uint64_t>(httpRequestToken::IPv4address), "IPv4address"},
        {static_cast< const uint64_t>(httpRequestToken::reg_name), "reg_name"},
        {static_cast< const uint64_t>(httpRequestToken::IP_literal), "IP_literal"},
        {static_cast< const uint64_t>(httpRequestToken::host), "host"},
        {static_cast< const uint64_t>(httpRequestToken::port), "port"},
        {static_cast< const uint64_t>(httpRequestToken::userinfo), "userinfo"},
        {static_cast< const uint64_t>(httpRequestToken::authority), "authority"},
        {static_cast< const uint64_t>(httpRequestToken::heir_part), "heir_part"},
        {static_cast< const uint64_t>(httpRequestToken::uri_absolute_form), "uri_absolute_form"},
        {static_cast< const uint64_t>(httpRequestToken::uri_authority_form), "uri_authority_form"},
        {static_cast< const uint64_t>(httpRequestToken::uri_asterisk_form), "uri_asterisk_form"},
        {static_cast< const uint64_t>(httpRequestToken::target), "target"},
        {static_cast< const uint64_t>(httpRequestToken::protocol), "protocol"},
        {static_cast< const uint64_t>(httpRequestToken::protocol_name), "protocol_name"},
        {static_cast< const uint64_t>(httpRequestToken::protocol_version), "protocol_version"},
        {static_cast< const uint64_t>(httpRequestToken::request_line), "request_line"},
        {static_cast< const uint64_t>(httpRequestToken::field_vchar), "field_vchar"},
        {static_cast< const uint64_t>(httpRequestToken::field_name), "field_name"},
        {static_cast< const uint64_t>(httpRequestToken::field_content), "field_content"},
        {static_cast< const uint64_t>(httpRequestToken::field_value), "field_value"},
        {static_cast< const uint64_t>(httpRequestToken::field_line), "field_line"},
        {static_cast< const uint64_t>(httpRequestToken::request), "request"},
    }};

}}}}//qor::components::protocols::http

#endif//QOR_PP_H_COMPONENTS_PROTOCOLS_HTTP_REQUESTPARSER_TOKENDEFS
