// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include <algorithm>
#include <iostream>
#include <iomanip>
#include <ranges>
#include "src/qor/tdd/tdd.h"
#include "src/qor/essentials/text/strings/strings.h"

using namespace qor;
using namespace qor::test;

qor_pp_test_case(canInstanceUCS4String)
{
    UCS4String ucs4str(U"Hello World");
    qor_pp_assert_that(ucs4str.Length()).isEqualTo(11);
    qor_pp_assert_that(ucs4str[0]).isEqualTo('H');
    qor_pp_assert_that(ucs4str.At(10)).isEqualTo('d');
}

qor_pp_test_case(canFillAnExistingUCS4StringwithFixedChars)
{
    UCS4String ucs4str(U"Hello World");
    ucs4str.Fill(U'-');
    qor_pp_assert_that(ucs4str.Length()).isEqualTo(11);
    qor_pp_assert_that(ucs4str[0]).isEqualTo('-');
    qor_pp_assert_that(ucs4str.At(10)).isEqualTo('-');
}

qor_pp_test_case(canTranscodeAUCS4StringToUTF8String)
{
    UCS4String ucs4str(U"Hello World");
    UTF8String utf8str = ucs4str.Transcode<UTF8String>();
    qor_pp_assert_that(utf8str.Length()).isEqualTo(11);
}