// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "keyboardinput.h"
#include "../../messages.h"

namespace qor{ namespace platform { namespace nswindows{ namespace gui{ namespace view{

    KeyboardController::KeyboardController() : BaseWindowPartController()
    {
    }

    bool KeyboardController::ProcessMessage(Window& window, long long& lResult, unsigned int msg, unsigned long long wParam, long long lParam)
    {
        bool bProcessed = ProcessHook(window, lResult, msg, wParam, lParam);

        switch (msg)
        {
        case wmInputLangChangeRequest:
        {
            OnInputLangChangeRequest(window, wParam, lParam);
            bProcessed = true;
        }
        break;
        case wmInputLangChange:
        {
            OnInputLangChange(window, wParam, lParam);
            lResult = 1;
            bProcessed = true;
        }
        case wmKeyDown:
        {
            OnKeyDown(window, wParam, lParam);
            lResult = 0;
            bProcessed = true;
        }
        case wmKeyUp:
        {
            OnKeyUp(window, wParam, lParam);
            lResult = 0;
            bProcessed = true;
        }
        case wmChar:
        {
            OnChar(window, wParam, lParam);
            lResult = 0;
            bProcessed = true;
        }
        case wmDeadChar:
        {
            OnDeadChar(window, wParam, lParam);
            lResult = 0;
            bProcessed = true;
        }
        case wmSysKeyDown:
        {
            OnSysKeyDown(window, wParam, lParam);
            lResult = 0;
            bProcessed = true;
        }
        case wmSysKeyUp:
        {
            OnSysKeyUp(window, wParam, lParam);
            lResult = 0;
            bProcessed = true;
        }
        case wmSysChar:
        {
            OnSysChar(window, wParam, lParam);
            lResult = 0;
            bProcessed = true;
        }
        case wmSysDeadChar:
        {
            OnSysDeadChar(window, wParam, lParam);
            lResult = 0;
            bProcessed = true;
        }
        break;
        case wmCommand:
        {
            unsigned short wCode = HiWord(wParam);

            if (wCode == 1)
            {
                unsigned short wAccelID = LoWord(wParam);
                OnCommand(window, wAccelID);
                lResult = 0;
                bProcessed = true;
            }
        }
        break;        
        }

        return bProcessed;
    }
    
    void KeyboardController::OnInputLangChangeRequest(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmInputLangChangeRequest, wParam, lParam);
    }

    void KeyboardController::OnInputLangChange(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmInputLangChange, wParam, lParam);
    }

    void KeyboardController::OnKeyDown(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmKeyDown, wParam, lParam);
    }

    void KeyboardController::OnKeyUp(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmKeyUp, wParam, lParam);
    }

    void KeyboardController::OnChar(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmChar, wParam, lParam);
    }

    void KeyboardController::OnDeadChar(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmDeadChar, wParam, lParam);
    }

    void KeyboardController::OnSysKeyDown(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmSysKeyDown, wParam, lParam);
    }

    void KeyboardController::OnSysKeyUp(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmSysKeyUp, wParam, lParam);
    }

    void KeyboardController::OnSysChar(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmSysChar, wParam, lParam);
    }

    void KeyboardController::OnSysDeadChar(Window& window, unsigned long long wParam, long long lParam)
    {
        window.DefWindowProcT(wmSysDeadChar, wParam, lParam);
    }

    void KeyboardController::OnCommand(Window& window, unsigned short wAccelID)
    {

    }

}}}}}//qor::platform::nswindows::gui::view
    