// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_PLATFORM_FILESYSTEM_FILE_READER
#define QOR_PP_H_PLATFORM_FILESYSTEM_FILE_READER

#include <cstdint>
#include "src/qor/reflection/reflection.h"
#include "file.h"

namespace qor{ namespace io{

    class qor_pp_module_interface(QOR_FILESYSTEM) FileReader
	{
	public:

        FileReader(ref_of<IFile>::type file);
        FileReader(filesystem::Index index, OpenFor use);
        virtual ~FileReader() = default;

        std::string ReadLine() const;
        byte ReadByte() const;
        char ReadChar() const;
        bool ReadBool() const;// Always 1 byte, no ordering        
        int16_t ReadInt16() const;
        uint16_t ReadUInt16() const;
        int32_t ReadInt32() const;
        uint32_t ReadUInt32() const;
        int64_t ReadInt64() const;
        uint64_t ReadUInt64() const;
        float ReadFloat() const;
        double ReadDouble() const;

        void Read(unsigned char& b) const;
        void Read(char& c) const;
        void Read(bool& b) const;
        void Read(short& s) const;
        void Read(unsigned short& s) const;
        void Read(int& i) const;
        void Read(unsigned int& ui) const;
        void Read(long& l) const;
        void Read(unsigned long& ul) const;
        void Read(long long& ll) const;
        void Read(unsigned long long& ull) const;
        void Read(float& f) const;
        void Read(double& d) const;

		template< class T >
		void ReadStruct(T& t) const
		{
			qor_reflection::for_each_field(t, [this](auto& value, std::size_t i)
				{
                    Read(value);
				}
			);
		}

    private:

        arch::Endian m_endian;
        ref_of<IFile>::type m_file;
        filesystem::Index m_index;
    };

}}//qor::io

#endif//QOR_PP_H_PLATFORM_FILESYSTEM_FILE_READER
