// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_WINDOWS_GUI_FACTORY_WINDOWSTYLE
#define QOR_PP_H_WINDOWS_GUI_FACTORY_WINDOWSTYLE

#include "src/framework/parallel/thread/currentthread.h"
#include "src/qor/injection/typeidentity.h"
#include "src/qor/reference/newref.h"
#include "src/platform/os/windows/common/structures.h"

//All types on this interface must be portable
namespace qor{ namespace platform { namespace win{ 

    class qor_pp_module_interface(QOR_WINGUI) WindowStyle final
    {
    public:

        operator unsigned long()
        {
            return m_style;
        }

        bool IsOverlapped();
        bool IsBorder();
        bool IsCaption();
        bool IsChild();
        bool IsClipChildren();
        bool IsClipSiblings();
        bool IsDisabled();
        bool IsDialogFrame();
        bool IsGroup();
        bool IsHScroll();
        bool IsMaximize();
        bool IsMaximizeBox();
        bool IsMinimize();
        bool IsMinimizeBox();
        bool IsPopup();
        bool IsSizingBorder();
        bool IsSystemMenu();
        bool IsTabStop();
        bool IsVisible();
        bool IsVScroll();

        void SetBorder(bool value);
        void SetCaption(bool value);
        void SetChild(bool value);
        void SetClipChildren(bool value);
        void SetClipSiblings(bool value);
        void SetDisabled(bool value);
        void SetDialogFrame(bool value);
        void SetGroup(bool value);
        void SetHScroll(bool value);
        void SetMaximize(bool value);
        void SetMaximizeBox(bool value);
        void SetMinimize(bool value);
        void SetMinimizeBox(bool value);
        void SetPopup(bool value);
        void SetSizingBorder(bool value);
        void SetSystemMenu(bool value);
        void SetTabStop(bool value);
        void SetVisible(bool value);
        void SetVScroll(bool value);

    private:

        unsigned long Overlapped	  = 0x00000000;	//The window is an overlapped window. An overlapped window has a title bar and a border. Same as the WS_TILED style.
        unsigned long Border          = 0x00800000;	//The window has a thin-line border
        unsigned long Caption         = 0x00C00000;	//The window has a title bar (includes the WS_BORDER style).
        unsigned long Child           = 0x40000000;	//The window is a child window. A window with this style cannot have a menu bar. This style cannot be used with the WS_POPUP style.
        unsigned long ClipChildren    = 0x02000000;	//Excludes the area occupied by child windows when drawing occurs within the parent window. This style is used when creating the parent window.
        unsigned long ClipSiblings    = 0x04000000;	//Clips child windows relative to each other; that is, when a particular child window receives a WM_PAINT message, the WS_CLIPSIBLINGS style clips all other overlapping child windows out of the region of the child window to be updated. If WS_CLIPSIBLINGS is not specified and child windows overlap, it is possible, when drawing within the client area of a child window, to draw within the client area of a neighboring child window.
        unsigned long Disabled        = 0x08000000;	//The window is initially disabled. A disabled window cannot receive input from the user. To change this after a window has been created, use the EnableWindow function.
        unsigned long DialogFrame     = 0x00400000;	//The window has a border of a style typically used with dialog boxes. A window with this style cannot have a title bar.
        unsigned long Group           = 0x00020000;	//The window is the first control of a group of controls. The group consists of this first control and all controls defined after it, up to the next control with the WS_GROUP style. The first control in each group usually has the WS_TABSTOP style so that the user can move from group to group. The user can subsequently change the keyboard focus from one control in the group to the next control in the group by using the direction keys.You can turn this style on and off to change dialog box navigation. To change this style after a window has been created, use the SetWindowLong function.
        unsigned long HScroll         = 0x00100000;	//The window has a horizontal scroll bar.
        unsigned long Maximize        = 0x01000000;	//The window is initially maximized.
        unsigned long MaximizeBox     = 0x00010000;	//The window has a maximize button. Cannot be combined with the WS_EX_CONTEXTHELP style. The WS_SYSMENU style must also be specified.
        unsigned long Minimize        = 0x20000000;	//The window is initially minimized.
        unsigned long MinimizeBox     = 0x00020000;	//The window has a minimize button. Cannot be combined with the WS_EX_CONTEXTHELP style. The WS_SYSMENU style must also be specified.
        unsigned long Popup	          = 0x80000000;	//The window is a pop-up window. This style cannot be used with the WS_CHILD style.
        unsigned long SizingBorder    = 0x00040000; //The window has a sizing border. Same as the WS_THICKFRAME style.
        unsigned long SystemMenu      = 0x00080000;	//The window has a window menu on its title bar. The WS_CAPTION style must also be specified.
        unsigned long TabStop         = MaximizeBox;//The window is a control that can receive the keyboard focus when the user presses the TAB key. Pressing the TAB key changes the keyboard focus to the next control with the WS_TABSTOP style.You can turn this style on and off to change dialog box navigation. To change this style after a window has been created, use the SetWindowLong function. For user-created windows and modeless dialogs to work with tab stops, alter the message loop to call the IsDialogMessage function.
        unsigned long Visible	      = 0x10000000;	//The window is initially visible.
        unsigned long VScroll         = 0x00200000;	//The window has a vertical scroll bar.

        unsigned long m_topLevelStyle{Overlapped | Caption | SystemMenu | SizingBorder | MinimizeBox | MaximizeBox};
        unsigned long m_popupStyle = {Popup | Border | SystemMenu};
        unsigned long m_style{Overlapped | Caption | SystemMenu | SizingBorder | MinimizeBox | MaximizeBox};
    };

    class qor_pp_module_interface(QOR_WINGUI) ExtendedWindowStyle final
    {
    public:

        operator unsigned long()
        {
            return m_style;
        }

        bool IsAcceptFiles();
        bool IsAppWindow();
        bool IsClientEdge();
        bool IsComposited();
        bool IsContextHelp();
        bool IsControlParent();
        bool IsDialogModalFrame();
        bool IsLayered();
        bool IsLayoutRTL();
        bool IsLeftScrollBar();
        bool IsMDIChild();
        bool IsNoActivate();
        bool IsNoInheritLayout();
        bool IsNoParentNotify();
        bool IsNoRedirectionBitmap();
        bool IsRightAligned();
        bool IsRTLReading();
        bool IsStaticEdge();
        bool IsToolWindow();
        bool IsTopMost();
        bool IsTransparent();
        bool IsWindowEdge();

        void SetAcceptFiles(bool value);
        void SetAppWindow(bool value);
        void SetClientEdge(bool value);
        void SetComposited(bool value);
        void SetContextHelp(bool value);
        void SetControlParent(bool value);
        void SetDialogModalFrame(bool value);
        void SetLayered(bool value);
        void SetLayoutRTL(bool value);
        void SetLeftScrollBar(bool value);
        void SetMDIChild(bool value);
        void SetNoActivate(bool value);
        void SetNoInheritLayout(bool value);
        void SetNoParentNotify(bool value);
        void SetNoRedirectionBitmap(bool value);
        void SetRightAligned(bool value);
        void SetRTLReading(bool value);
        void SetStaticEdge(bool value);
        void SetToolWindow(bool value);
        void SetTopMost(bool value);
        void SetTransparent(bool value);
        void SetWindowEdge(bool value);

    private:

        unsigned long AcceptFiles       {0x00000010};   //The window accepts drag-drop files.
        unsigned long AppWindow         {0x00040000};   //Forces a top-level window onto the taskbar when the window is visible.
        unsigned long ClientEdge        {0x00000200};   //The window has a border with a sunken edge.
        unsigned long Composited        {0x02000000};   //Paints all descendants of a window in bottom-to-top painting order using double-buffering. Bottom-to-top painting order allows a descendent window to have translucency (alpha) and transparency (color-key) effects, but only if the descendent window also has the WS_EX_TRANSPARENT bit set. Double-buffering allows the window and its descendents to be painted without flicker. This cannot be used if the window has a class style of CS_OWNDC, CS_CLASSDC, or CS_PARENTDC. Windows 2000: This style is not supported.
        unsigned long ContextHelp       {0x00000400};   //The title bar of the window includes a question mark. When the user clicks the question mark, the cursor changes to a question mark with a pointer. If the user then clicks a child window, the child receives a WM_HELP message. The child window should pass the message to the parent window procedure, which should call the WinHelp function using the HELP_WM_HELP command. The Help application displays a pop-up window that typically contains help for the child window. Cannot be used with the WS_MAXIMIZEBOX or WS_MINIMIZEBOX styles.
        unsigned long ControlParent     {0x00010000};   //The window itself contains child windows that should take part in dialog box navigation. If this style is specified, the dialog manager recurses into children of this window when performing navigation operations such as handling the TAB key, an arrow key, or a keyboard mnemonic.
        unsigned long DialogModalFrame  {0x00000001};   //The window has a double border; the window can, optionally, be created with a title bar by specifying the WS_CAPTION style in the dwStyle parameter.
        unsigned long Layered           {0x00080000};   //The window is a layered window. This style cannot be used if the window has a class style of either CS_OWNDC or CS_CLASSDC. Windows 8: The WS_EX_LAYERED style is supported for top-level windows and child windows. Previous Windows versions support WS_EX_LAYERED only for top-level windows.
        unsigned long LayoutRTL         {0x00400000};   //If the shell language is Hebrew, Arabic, or another language that supports reading order alignment, the horizontal origin of the window is on the right edge. Increasing horizontal values advance to the left.
        unsigned long LeftScrollBar     {0x00004000};   //If the shell language is Hebrew, Arabic, or another language that supports reading order alignment, the vertical scroll bar (if present) is to the left of the client area. For other languages, the style is ignored.
        unsigned long MDIChild          {0x00000040};   //The window is a MDI child window.
        unsigned long NoActivate        {0x08000000};   //A top-level window created with this style does not become the foreground window when the user clicks it. The system does not bring this window to the foreground when the user minimizes or closes the foreground window. The window should not be activated through programmatic access or via keyboard navigation by accessible technology, such as Narrator. To activate the window, use the SetActiveWindow or SetForegroundWindow function. The window does not appear on the taskbar by default. To force the window to appear on the taskbar, use the WS_EX_APPWINDOW style.
        unsigned long NoInheritLayout   {0x00100000};   //The window does not pass its window layout to its child windows.
        unsigned long NoParentNotify    {0x00000004};   //The child window created with this style does not send the WM_PARENTNOTIFY message to its parent window when it is created or destroyed.
        unsigned long NoRedirectionBitmap {0x00200000}; //The window does not render to a redirection surface. This is for windows that do not have visible content or that use mechanisms other than surfaces to provide their visual.
        unsigned long RightAligned      {0x00001000};   //The window has generic "right-aligned" properties. This depends on the window class. This style has an effect only if the shell language is Hebrew, Arabic, or another language that supports reading-order alignment; otherwise, the style is ignored.Using the WS_EX_RIGHT style for static or edit controls has the same effect as using the SS_RIGHT or ES_RIGHT style, respectively. Using this style with button controls has the same effect as using BS_RIGHT and BS_RIGHTBUTTON styles.
        unsigned long RTLReading        {0x00002000};   //If the shell language is Hebrew, Arabic, or another language that supports reading-order alignment, the window text is displayed using right-to-left reading-order properties. For other languages, the style is ignored.
        unsigned long StaticEdge        {0x00020000};   //The window has a three-dimensional border style intended to be used for items that do not accept user input.
        unsigned long ToolWindow        {0x00000080};   //The window is intended to be used as a floating toolbar. A tool window has a title bar that is shorter than a normal title bar, and the window title is drawn using a smaller font. A tool window does not appear in the taskbar or in the dialog that appears when the user presses ALT+TAB. If a tool window has a system menu, its icon is not displayed on the title bar. However, you can display the system menu by right-clicking or by typing ALT+SPACE.
        unsigned long TopMost           {0x00000008};   //The window should be placed above all non-topmost windows and should stay above them, even when the window is deactivated. To add or remove this style, use the SetWindowPos function.
        unsigned long Transparent       {0x00000020};   //The window should not be painted until siblings beneath the window (that were created by the same thread) have been painted. The window appears transparent because the bits of underlying sibling windows have already been painted. To achieve transparency without these restrictions, use the SetWindowRgn function.
        unsigned long WindowEdge        {0x00000100};   //The window has a border with a raised edge.        
        unsigned long ExOverlapped      {WindowEdge | ClientEdge};//The window is an overlapped window.
        unsigned long PaletteWindow     {WindowEdge | ToolWindow | TopMost}; //The window is palette window, which is a modeless dialog box that presents an array of commands.

    private:
        unsigned long m_style{0x00000000};
    };
    
}}}//qor::platform::win

#endif//QOR_PP_H_WINDOWS_GUI_FACTORY_WINDOWSTYLE