// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include "src/qor/error/error.h"

#include "src/platform/os/linux/wayland/client/surface.h"
#include "src/platform/os/linux/wayland/client/display.h"
#include "src/platform/os/linux/wayland/xdgshell/xdgsurface.h"
#include "src/platform/os/linux/wayland/xdgshell/xdgtoplevel.h"
#include "src/platform/os/linux/wayland/xdgshell/listeners/xdgpopuplistener.h"
#include "src/platform/os/linux/wayland/xdgshell/listeners/xdgsurfacelistener.h"
#include "src/platform/os/linux/wayland/xdgshell/listeners/xdgtoplevellistener.h"
#include "src/platform/os/linux/wayland/xdgshell/listeners/xdgwmbaselistener.h"
#include "src/platform/os/linux/wayland/xdgshell/xdgsession.h"

#include "eglwindow.h"

#include <wayland-client-core.h>
#include <wayland-client-protocol.h>
#include <wayland-egl.h>

namespace qor{ namespace platform { namespace nslinux{ namespace wl{

    WEGLWindow::WEGLWindow(ref_of<XDGSession>::type session) : XDGTopLevelWindow(session), m_eglWindow(nullptr)
    {
    }

    WEGLWindow::~WEGLWindow()
    {
        if(m_eglWindow)
        {
            wl_egl_window_destroy(m_eglWindow);
        }
    }

    void WEGLWindow::DoConfiguration()
    {
        XDGWindow::DoConfiguration();
        m_eglWindow = wl_egl_window_create(m_xdgSurface->BaseSurface()->Use(), m_width, m_height);
    }

    wl_egl_window* WEGLWindow::Use() const
    {
        if(!m_eglWindow)
        {
            warning("Using EGLWindow with null wl_egl_window pointer");
        }
        return m_eglWindow;
    }

    void WEGLWindow::GetAttachedSize(int& width, int& height)
    {
        wl_egl_window_get_attached_size(m_eglWindow, &width, &height);
    }

    void WEGLWindow::Resize(int width, int height, int dx, int dy)
    {
        wl_egl_window_resize(m_eglWindow, width, height, dx, dy);
    }

    void WEGLWindow::OnXDGSurfaceConfigured()
    {
        m_xdgSurface->BaseSurface()->Commit(); 
    }

    void WEGLWindow::OnXDGTopLevelConfigured(int32_t width, int32_t height, struct wl_array* states)
    {
        if(!width && !height) return;

	    if(m_width != width || m_height != height) 
        {
		    m_width = width;
		    m_height = height;
		    Resize(m_width, m_height, 0, 0);
            m_xdgSurface->BaseSurface()->Commit();
    	}        
    }

}}}}//qor::platform::nslinux::wl
