// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "iouringeventprocessor.h"
#include "src/platform/os/linux/framework/asyncioservice/asyncioservice.h"
#include "src/qor/error/error.h"
#include "src/qor/log//informative.h"

qor_pp_module_provide(QOR_LINUXASYNCIOSERVICE, AsyncIOEventProcessor)

namespace qor{ namespace nslinux{ namespace framework{

    int IOUringEventProcessor::Event()
    {
        io_uring_cqe *temp = nullptr;
        __kernel_timespec ts{ .tv_sec = 0, .tv_nsec = 100000 /*/ (1 << scale)*/ };
        sigset_t sigmask;
        memset(&sigmask, sizeof(sigset_t), 0);        
        //log::inform("Waiting for {0} io events...", uring.ExpectationCount());
        int result = io_uring_submit_and_wait_timeout(uring.get(), &temp, uring.ExpectationCount(), &ts, &sigmask);
        
        if(result >= 0) 
        {
            if(temp != nullptr)
            {
                //log::inform("Got {0} io events with temp CQE.", result);
                if( result == 0)
                {
                    return uring.ConsumeCQEntries();
                }
                else
                {
                    return uring.ConsumeCQEntries(temp, result);
                }
            }
            else
            {
                //log::inform("Got {0} io events with no temp CQE.", result);
                return uring.ConsumeCQEntries();
            }
        }
        else if (result < 0)
        {            
            if(result == -EINTR || result == -EAGAIN)
            {
                return 0;
            }
            if(result != -ETIME)
            {
                serious("IOUring error");
            }
        }
        return result;
    }

}}}//qor::nslinux::framework