
#ifndef QOR_PP_H_SDK_QOR
#define QOR_PP_H_SDK_QOR

#include "src/configuration/configuration.h"
#include "src/qor/module/module.h"
#include "src/framework/event/delegate/delegate.h"
#include "src/framework/event/observer/observer.h"
#include "src/qor/instance/instance.h"
#include "src/qor/property/property.h"
#include "src/qor/reflection/reflection.h"
#include "src/qor/factory/factory.h"
#include "src/qor/datastructures/guid.h"
#include "src/qor/profiling/profiling.h"
#include "src/qor/tdd/tdd.h"
#include "src/qor/objectcontext/anyobject.h"
#include "src/qor/memory/memory.h"
#include "src/qor/injection/diwrapper.h"
#include "src/qor/interception/functioncontext.h"
#include "src/qor/interception/callcontext.h"
#include "src/qor/current/currentthread.h"
#include "src/qor/reference/newref.h"
#include "src/qor/issue/issue.h"
#include "src/qor/error/error.h"
#include "src/qor/error/handler.h"
#include "src/qor/error/defaulterrorhandler.h"
#include "src/qor/log/debug.h"
#include "src/qor/log/informative.h"
#include "src/qor/log/impactful.h"
#include "src/qor/log/important.h"
#include "src/qor/log/imperative.h"
#include "src/qor/log/defaultloghandler.h"
#include "src/framework/parallel/sync/sync.h"
#include "src/framework/parallel/sync/mutex.h"
#include "src/framework/parallel/sync/recursive_mutex.h"
#include "src/framework/parallel/sync/nullsection.h"

#endif//QOR_PP_H_SDK_QOR