// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "perthread.h"

#include "src/platform/os/windows/api_layer/gdi/gdi32.h"
#include "src/platform/os/windows/api_layer/opengl/opengl.h"

#undef AddMonitor

using namespace qor::win::api;

namespace qor{ namespace platform { namespace win{

    int PerThread::Run()
    {
        return m_messageHandler.MessageLoop();
    }

    void PerThread::SetWindowCreationInProgress(ref_of<Window>::type window)
    {
        m_inProgress = window;
    }

    ref_of<Window>::type PerThread::GetWindowCreationInProgress()
    {
        ref_of<Window>::type window = m_inProgress;
        m_inProgress.Dispose();
        return window;
    }

    bool PerThread::AddWindow(Window* window)
    {
        auto it = m_windowHandleMap.find(window->GetHandle().Use());
        if(it == m_windowHandleMap.end())
        {
            m_windowHandleMap.insert(std::make_pair(window->GetHandle().Use(), window));
            return true;
        }
        return false;
    }

    bool PerThread::RemoveWindow(Window* window)
    {
        auto it = m_windowHandleMap.find(window->GetHandle().Use());
        if(it != m_windowHandleMap.end())
        {
            m_windowHandleMap.erase(it);
            return true;
        }
        return false;
    }

    Window* PerThread::FromHandle(void* hWnd)
    {
        Window* window = nullptr;
        auto it = m_windowHandleMap.find(hWnd);
        if(it != m_windowHandleMap.end())
        {
            window = it->second;
        }
        return window;
    }

    void PerThread::SetWindowEnumProc(wndenumproc proc)
    {
        m_windowEnumProc = proc;
    }

    wndenumproc PerThread::GetWindowEnumProc()
    {
        return m_windowEnumProc;
    }

    void PerThread::SetPropertyEnumProc(propenumproc proc)
    {
        m_properrtyEnumProc = proc;
    }

    propenumproc PerThread::GetPropertyEnumProc()
    {
        return m_properrtyEnumProc;
    }

    bool PerThread::AddMenu(Menu* menu)
    {
        auto it = m_menuHandleMap.find(menu->GetHandle().Use());
        if(it == m_menuHandleMap.end())
        {
            m_menuHandleMap.insert(std::make_pair(menu->GetHandle().Use(), menu));
            return true;
        }
        return false;
    }

    bool PerThread::RemoveMenu(Menu* menu)
    {
        auto it = m_menuHandleMap.find(menu->GetHandle().Use());
        if(it != m_menuHandleMap.end())
        {
            m_menuHandleMap.erase(it);
            return true;
        }
        return false;
    }
        
    Menu* PerThread::MenuFromHandle(void* hMenu)
    {
        Menu* menu = nullptr;
        auto it = m_menuHandleMap.find(hMenu);
        if(it != m_menuHandleMap.end())
        {
            menu = it->second;
        }
        return menu;
    }

    bool PerThread::AddDeviceContext(ref_of<DeviceContext>::type dc)
    {
        auto it = m_deviceContextHandleMap.find(dc->GetHandle().Use());
        if(it == m_deviceContextHandleMap.end())
        {
            m_deviceContextHandleMap.insert(std::make_pair(dc->GetHandle().Use(), dc));
            return true;
        }
        return false;
    }

    bool PerThread::RemoveDeviceContext(ref_of<DeviceContext>::type dc)
    {
        auto it = m_deviceContextHandleMap.find(dc->GetHandle().Use());
        if(it != m_deviceContextHandleMap.end())
        {
            m_deviceContextHandleMap.erase(it);
            return true;
        }
        return false;
    }

    ref_of<DeviceContext>::type PerThread::DeviceContextFromHandle(void* hDC)
    {
        ref_of<DeviceContext>::type dc = nullptr;
        auto it = m_deviceContextHandleMap.find(hDC);
        if(it != m_deviceContextHandleMap.end())
        {
            dc = it->second;
        }
        if(hDC != nullptr && dc.IsNull())
        {
            dc = new_ref<DeviceContext>(PrimitiveHandle(hDC), false);            
        }
        return dc;
    }

    bool PerThread::AddMonitor(Monitor* mon)
    {
        auto it = m_monitorHandleMap.find(mon->GetHandle().Use());
        if(it == m_monitorHandleMap.end())
        {
            m_monitorHandleMap.insert(std::make_pair(mon->GetHandle().Use(), mon));
            return true;
        }
        return false;
    }

    bool PerThread::RemoveMonitor(Monitor* mon)
    {
        auto it = m_monitorHandleMap.find(mon->GetHandle().Use());
        if(it != m_monitorHandleMap.end())
        {
            m_monitorHandleMap.erase(it);
            return true;
        }
        return false;
    }

    Monitor* PerThread::MonitorFromHandle(void* hMon)
    {
        Monitor* monitor = nullptr;
        auto it = m_monitorHandleMap.find(hMon);
        if(it != m_monitorHandleMap.end())
        {
            monitor = it->second;
        }
        return monitor;
    }

    unsigned int PerThread::NextResourceId()
    {
        return ++m_nextResourceId;
    }

    bool PerThread::SetCurrentWGLContext(ref_of<DeviceContext>::type dc, ref_of<WGLContext>::type context)
    {
        m_currentWGLContext = context;
        return WGL::MakeCurrent((HDC)(dc->GetHandle().Use()), (HGLRC)(context->GetHandle().Use())) ? true : false;
    }
    
    bool PerThread::ClearCurrentWGLContext()
    {
        m_currentWGLContext = nullptr;
        return WGL::MakeCurrent((HDC)(nullptr), (HGLRC)(nullptr)) ? true : false;
    }

    bool PerThread::MakeThisWGLContextNotCurrent(WGLContext* context)
    {
        if(context == m_currentWGLContext)
        {
            ClearCurrentWGLContext();
            return true;
        }
        return false;
    }

    OpenGLSession& PerThread::OGLSession()
    {
        return m_openGLSession;
    }

}}}

thread_local qor::detail::ThreadInstanceHolder<qor::platform::win::PerThread> ThreadInstanceHolderPerThread;

qor_pp_export qor::detail::ThreadInstanceHolder<qor::platform::win::PerThread>* GetCurrentPerThread()
{
    return &ThreadInstanceHolderPerThread;
}

namespace qor {
    namespace detail {

        template<>
        qor_pp_export ThreadInstanceHolder<qor::platform::win::PerThread>* theThreadInstanceHolder<qor::platform::win::PerThread>()
        {
            return GetCurrentPerThread();
        }
    }
}
