// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "3rdparty/glad/gl.h"

#include "src/qor/assert/assert.h"
#include "context.h"
#include "../window/window.h"
#include "../session.h"

namespace qor{ namespace gl {

    Context::Context()
    {
    }

    Context::~Context()
    {        
    }

    void Context::MakeCurrent(Window* handle)
    {
        REQUIRE_INIT();

        Window* window = handle;
        Window* previous = (Window*)(TheSession().GetPlatform().PlatformGetTls(&TheSession().contextSlot));

        if (window && window->context.client == NO_API)
        {
            Session::InputError(NO_WINDOW_CONTEXT, "Cannot make current with a window that has no OpenGL or OpenGL ES context");
            return;
        }

        if (previous)
        {
            if (!window || window->context.source != previous->context.source)
            {
                previous->context.MakeCurrent(nullptr);
            }
        }

        if (window)
        {
            window->context.MakeCurrent(window);
        }
    }

    Window* Context::GetCurrent(void)
    {
        REQUIRE_INIT_OR_RETURN(nullptr);
        return (Window*)(TheSession().GetPlatform().PlatformGetTls(&TheSession().contextSlot));
    }

    void Context::SwapBuffers(Window* handle)
    {
        REQUIRE_INIT();

        Window* window = handle;
        qor_pp_assert_that(window != nullptr);

        if (window->context.client == NO_API)
        {
            Session::InputError(NO_WINDOW_CONTEXT, "Cannot swap buffers of a window that has no OpenGL or OpenGL ES context");
            return;
        }

        window->context.SwapBuffers(window);

    }

    void Context::SwapInterval(int interval)
    {
        Window* window = nullptr;

        REQUIRE_INIT();

        window = (Window*)(TheSession().GetPlatform().PlatformGetTls(&TheSession().contextSlot));
        if (!window)
        {
            Session::InputError(NO_CURRENT_CONTEXT, "Cannot set swap interval without a current OpenGL or OpenGL ES context");
            return;
        }

        window->context.SwapInterval(interval);

    }
        
    bool Context::ExtensionSupported(const char* extension)
    {
        Window* window = nullptr;
        qor_pp_assert_that(extension != nullptr);

        REQUIRE_INIT_OR_RETURN(false);

        window = (Window*)(TheSession().GetPlatform().PlatformGetTls(&TheSession().contextSlot));
        if (!window)
        {
            Session::InputError(NO_CURRENT_CONTEXT, "Cannot query extension without a current OpenGL or OpenGL ES context");
            return false;
        }

        if (*extension == '\0')
        {
            Session::InputError(INVALID_VALUE, "Extension name cannot be an empty string");
            return false;
        }

        if (window->context.major >= 3)
        {
            int i;
            int count;

            // Check if extension is in the modern OpenGL extensions string list

            window->context.GetIntegerv(GL_NUM_EXTENSIONS, &count);

            for (i = 0;  i < count;  i++)
            {
                const char* en = (const char*)
                    window->context.GetStringi(GL_EXTENSIONS, i);
                if (!en)
                {
                    Session::InputError(PLATFORM_ERROR, "Extension string retrieval is broken");
                    return false;
                }

                if (strcmp(en, extension) == 0)
                {
                    return true;
                }
            }
        }
        else
        {
            // Check if extension is in the old style OpenGL extensions string

            const char* extensions = (const char*) window->context.GetString(GL_EXTENSIONS);
            if (!extensions)
            {
                Session::InputError(PLATFORM_ERROR, "Extension string retrieval is broken");
                return false;
            }

            if (StringInExtensionString(extension, extensions))
            {
                return true;
            }
        }

        // Check if extension is in the platform-specific string
        return window->context.ExtensionSupported(extension);

    }

    glproc Context::GetProcAddress(const char* procname)
    {
        Window* window = nullptr;
        qor_pp_assert_that(procname != nullptr);

        REQUIRE_INIT_OR_RETURN(nullptr);

        window = (Window*)(TheSession().GetPlatform().PlatformGetTls(&TheSession().contextSlot));
        if (!window)
        {
            Session::InputError(NO_CURRENT_CONTEXT,"Cannot query entry point without a current OpenGL or OpenGL ES context");
            return nullptr;
        }

        return window->context.GetProcAddress(procname);
    }

    //private

    // Searches an extension string for the specified extension
    bool Context::StringInExtensionString(const char* string, const char* extensions)
    {
        const char* start = extensions;

        for (;;)
        {
            const char* where;
            const char* terminator;

            where = strstr(start, string);
            if (!where)
                return false;

            terminator = where + strlen(string);
            if (where == start || *(where - 1) == ' ')
            {
                if (*terminator == ' ' || *terminator == '\0')
                    break;
            }

            start = terminator;
        }

        return true;
    }

    ref_of<ContextPimpl>::type Context::GetPimpl()
    {
        return m_impl;
    }

}}//qor::gl