// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "filereader.h"
#include "src/platform/platform.h"
#include "src/platform/architecture/detectarchitecture.h"
#include "src/platform/filesystem/filesystem.h"

namespace qor{ namespace platform{

    FileReader::FileReader(ref_of<IFile>::type file)
    {
        m_file = file;
    }

    FileReader::FileReader(FileIndex index, OpenFor use)
    {
        auto fileSystem = ThePlatform(qor_shared)->GetSubsystem<FileSystem>();
        m_file = fileSystem->Open(index, use);
    }

    std::string FileReader::ReadLine() const
    {
        std::string line;
        char c = '\0';
        while( c != 0xA && m_file->Read((byte*)&c,1))//Redo this to use ReadChar 
        {
            if( c != 0xD )
            {
                line.push_back(c);
            }
        }
        return line;
    }

    byte FileReader::ReadByte() const
    {
        byte b;
        m_file->Read(&b, 1);
        return b;
    }

    char FileReader::ReadChar() const
    {
        char c;
        m_file->Read((byte*)&c, 1);
        return c;
    }

    bool FileReader::ReadBool() const
    {
        byte b = ReadByte();
        return b != 0 ? true : false;

    }

    //right now these jst naievely flip the byte order
    //we may need them to handle word ordering for different types. 

    int16_t FileReader::ReadInt16(arch::Endian endian) const
    {
        int16_t s = 0;
        if(endian == arch::host || (endian == qor::arch::endian))
        {            
            m_file->Read((byte*)&s, 2);            
        }
        else
        {            
            m_file->Read(((byte*)&s) + 1, 1);
            m_file->Read((byte*)&s, 1);
        }
        return s;
    }

    uint16_t FileReader::ReadUInt16(arch::Endian endian) const
    {
        uint16_t s = 0;
        if(endian == arch::host || (endian == qor::arch::endian))
        {            
            m_file->Read((byte*)&s, 2);            
        }
        else
        {            
            m_file->Read(((byte*)&s) + 1, 1);
            m_file->Read((byte*)&s, 1);
        }
        return s;
    }

    int32_t FileReader::ReadInt32(arch::Endian endian) const
    {
        int32_t i = 0;
        if(endian == arch::host || (endian == qor::arch::endian))
        {            
            m_file->Read((byte*)&i, 4);
        }
        else
        {   
            byte data[4];
            m_file->Read(data, 4);
            byte* p = reinterpret_cast<byte*>(&i);
            for(unsigned int l = 0; l < 4; ++l)
            {
                *p++ = data[3 - l];
            }
        }
        return i;
    }

    uint32_t FileReader::ReadUInt32(arch::Endian endian) const
    {
        uint32_t i = 0;
        if(endian == arch::host || (endian == qor::arch::endian))
        {            
            m_file->Read((byte*)&i, 4);
        }
        else
        {   
            byte data[4];
            m_file->Read(data,4);
            byte* p = reinterpret_cast<byte*>(&i);
            for(unsigned int l = 0; l < 4; ++l)
            {
                *p++ = data[3 - l];
            }
        }
        return i;
    }
    
    int64_t FileReader::ReadInt64(arch::Endian endian) const
    {
        int64_t i = 0;
        if(endian == arch::host || (endian == qor::arch::endian))
        {            
            m_file->Read((byte*)&i, 8);
        }
        else
        {   
            byte data[8];
            m_file->Read(data, 8);
            byte* p = reinterpret_cast<byte*>(&i);
            for(unsigned int l = 0; l < 8; ++l)
            {
                *p++ = data[7 - l];
            }
        }
        return i;
    }

    uint64_t FileReader::ReadUInt64(arch::Endian endian) const
    {
        uint64_t i = 0;
        if(endian == arch::host || (endian == qor::arch::endian))
        {            
            m_file->Read((byte*)&i, 8);
        }
        else
        {   
            byte data[8];
            m_file->Read(data, 8);
            byte* p = reinterpret_cast<byte*>(&i);
            for(unsigned int l = 0; l < 8; ++l)
            {
                *p++ = data[7 - l];
            }
        }
        return i;
    }
    
    float FileReader::ReadFloat(arch::Endian endian) const
    {
        float f = 0.0f;
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Read((byte*)&f, sizeof(float));
        }
        else
        {
            byte data[sizeof(float)];
            m_file->Read(data, sizeof(float));
            byte* p = reinterpret_cast<byte*>(&f);
            for(unsigned int l = 0; l < sizeof(float); ++l)
            {
                *p++ = data[sizeof(float) - (1 + l)];
            }
        }
        return f;
    }

    double FileReader::ReadDouble(arch::Endian endian) const
    {
        double d = 0.0;
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Read((byte*)&d, sizeof(double));
        }
        else
        {
            byte data[sizeof(double)];
            m_file->Read(data, sizeof(double));
            byte* p = reinterpret_cast<byte*>(&d);
            for(unsigned int l = 0; l < sizeof(double); ++l)
            {
                *p++ = data[sizeof(double) - (1 + l)];
            }
        }
        return d;
    }

    void FileReader::Read(unsigned char& b, arch::Endian endian) const
    {
        b = ReadByte();
    }

    void FileReader::Read(char& c, arch::Endian endian) const
    {
        c = ReadChar();
    }

    void FileReader::Read(bool& b, arch::Endian endian) const
    {
        byte v = ReadByte();
        b = v ? true : false;
    }

    void FileReader::Read(short& s, arch::Endian endian) const
    {
        if(sizeof(int16_t) > sizeof(short))
        {
            warning("coersing int16_t to a short looses data on this platform");
        }
        int16_t v = ReadInt16(endian);
        s = v;
    }

    void FileReader::Read(unsigned short& us, arch::Endian endian) const
    {
        if(sizeof(uint16_t) > sizeof(unsigned short))
        {
            warning("coersing uint16_t to a unsigned short looses data on this platform");
        }
        uint16_t v = ReadUInt16(endian);
        us = v;
    }

    void FileReader::Read(int& i, arch::Endian endian) const
    {
        if(sizeof(int32_t) > sizeof(int))
        {
            warning("coersing int32_t to int looses data on this platform");
        }
        int32_t v = ReadInt32(endian);
        i = v;
    }

    void FileReader::Read(unsigned int& ui, arch::Endian endian) const
    {
        if(sizeof(uint32_t) > sizeof(unsigned int))
        {
            warning("coersing uint32_t to unsigned int looses data on this platform");
        }
        uint32_t v = ReadUInt32(endian);
        ui = v;
    }

    void FileReader::Read(long& l, arch::Endian endian) const
    {
        if(sizeof(int32_t) > sizeof(long))
        {
            warning("coersing int32_t to long looses data on this platform");
        }
        int32_t v = ReadInt32(endian);
        l = v;
    }

    void FileReader::Read(unsigned long& ul, arch::Endian endian) const
    {
        if(sizeof(uint32_t) > sizeof(unsigned long))
        {
            warning("coersing uint32_t to unsigned long looses data on this platform");
        }
        uint32_t v = ReadUInt32(endian);
        ul = v;
    }

    void FileReader::Read(long long& ll, arch::Endian endian) const
    {
        if(sizeof(int64_t) > sizeof(long long))
        {
            warning("coersing int64_t to long long looses data on this platform");
        }
        int64_t v = ReadInt64(endian);
        ll = v;
    }

    void FileReader::Read(unsigned long long& ull, arch::Endian endian) const
    {
        if(sizeof(uint64_t) > sizeof(unsigned long long))
        {
            warning("coersing uint64_t to unsigned long long looses data on this platform");
        }
        uint64_t v = ReadUInt64(endian);
        ull = v;
    }

    void FileReader::Read(float& f, arch::Endian endian) const
    {
        if(sizeof(uint32_t) != sizeof(float))
        {
            serious("coersing 4 bytes to float is incompatble with this platform");
            f = 0.0;
        }
        else
        {
            int32_t v = ReadInt32(endian);
            f = *(reinterpret_cast<float*>(&v));
        }
    }

    void FileReader::Read(double& d, arch::Endian endian) const
    {
        if(sizeof(uint64_t) != sizeof(double))
        {
            serious("coersing 8 bytes to double is incompatble with this platform");
            d = 0.0;
        }
        else
        {
            uint64_t v = ReadUInt64(endian);
            d = *(reinterpret_cast<double*>(&v));
        }
    }

}}//qor::platform