// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"

#include "filewriter.h"
#include "src/platform/platform.h"
#include "src/platform/architecture/detectarchitecture.h"
#include "src/platform/filesystem/filesystem.h"

namespace qor{ namespace platform{

    FileWriter::FileWriter(ref_of<IFile>::type file)
    {
        m_file = file;
    }

    FileWriter::FileWriter(FileIndex index, OpenFor use)
    {
        auto fileSystem = ThePlatform(qor_shared)->GetSubsystem<FileSystem>();
        m_file = fileSystem->Open(index, use);
    }
    
    void FileWriter::WriteLine(const std::string& line, const std::string& end) const
    {        
        m_file->Write((byte*)line.data(), line.size());
        m_file->Write((byte*)end.data(), end.size());
    }

    void FileWriter::WriteByte(const byte& b) const
    {        
        m_file->Write((byte*)&b, 1);        
    }

    void FileWriter::WriteChar(const char& c) const
    {        
        m_file->Write((byte*)&c, 1);
    }

    void FileWriter::WriteBool(const bool& b) const
    {
        m_file->Write((byte*)&b, 1);
    }
        
    void FileWriter::WriteInt16(const int16_t& i, arch::Endian endian) const
    {
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Write((byte*)&i, 2);
        }
        else
        {
            byte* p = (byte*)&i;
            m_file->Write( p + 1, 1);
            m_file->Write( p, 1);
        }
    }

    void FileWriter::WriteUInt16(const uint16_t& ui, arch::Endian endian) const
    {
        byte* p = (byte*)&ui;
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Write(p, 2);
        }
        else
        {            
            m_file->Write( p + 1, 1);
            m_file->Write( p, 1);
        }
    }

    void FileWriter::WriteInt32(const int32_t& i, arch::Endian endian) const
    {
        byte* p = (byte*)&i;
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Write(p, 4);
        }
        else
        {            
            m_file->Write( p + 3, 1);
            m_file->Write( p + 2, 1);
            m_file->Write( p + 1, 1);
            m_file->Write( p, 1);
        }
    }

    void FileWriter::WriteUInt32(const uint32_t& ui, arch::Endian endian) const
    {
        byte* p = (byte*)&ui;
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Write(p, 4);
        }
        else
        {            
            m_file->Write( p + 3, 1);
            m_file->Write( p + 2, 1);
            m_file->Write( p + 1, 1);
            m_file->Write( p, 1);
        }
    }

    void FileWriter::WriteInt64(const int64_t& i, arch::Endian endian) const
    {
        byte* p = (byte*)&i;
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Write(p, 8);
        }
        else
        {            
            m_file->Write( p + 7, 1);
            m_file->Write( p + 6, 1);
            m_file->Write( p + 5, 1);
            m_file->Write( p + 4, 1);
            m_file->Write( p + 3, 1);
            m_file->Write( p + 2, 1);
            m_file->Write( p + 1, 1);
            m_file->Write( p, 1);
        }
    }

    void FileWriter::WriteUInt64(const uint64_t& ui, arch::Endian endian) const
    {
        byte* p = (byte*)&ui;
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Write(p, 8);
        }
        else
        {            
            m_file->Write( p + 7, 1);
            m_file->Write( p + 6, 1);
            m_file->Write( p + 5, 1);
            m_file->Write( p + 4, 1);
            m_file->Write( p + 3, 1);
            m_file->Write( p + 2, 1);
            m_file->Write( p + 1, 1);
            m_file->Write( p, 1);
        }
    }

    void FileWriter::WriteFloat(const float& f, arch::Endian endian) const
    {
        byte* p = (byte*)&f;
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Write(p, sizeof(float));
        }
        else
        {
            for(unsigned int loop = sizeof(float) -1; loop >=0; --loop)
            {
                m_file->Write( p + loop, 1);
            }
        }
    }

    void FileWriter::WriteDouble(const double& d, arch::Endian endian) const
    {
        byte* p = (byte*)&d;
        if(endian == arch::host || (endian == qor::arch::endian))
        {
            m_file->Write(p, sizeof(double));
        }
        else
        {
            for(unsigned int loop = sizeof(double) -1; loop >=0; --loop)
            {
                m_file->Write( p + loop, 1);
            }
        }
    }


    void FileWriter::Write(const char c, arch::Endian endian) const
    {
        if(sizeof(char) > 1)
        {
            warning("coersing char to byte for serialization looses data on this platform.");
        }
        WriteChar(c);
    }

    void FileWriter::Write(const unsigned char c, arch::Endian endian) const
    {
        if(sizeof(unsigned char) > 1)
        {
            warning("coersing unsigned char to byte for serialization looses data on this platform.");
        }
        WriteByte(c);
    }

    void FileWriter::Write(const bool b, arch::Endian endian) const
    {
        if(sizeof(bool) > 1)
        {
            warning("coersing bool to byte for serialization looses data on this platform.");
        }
        WriteBool(b);
    }

    void FileWriter::Write(const short s, arch::Endian endian) const
    {
        if(sizeof(short) > sizeof(int16_t))
        {
            warning("coersing short to int16_t for serialization looses data on this platform");
        }
        int16_t i = s;
        WriteInt16(i, endian);
    }

    void FileWriter::Write(const unsigned short s, arch::Endian endian) const
    {
        if(sizeof(unsigned short) > sizeof(uint16_t))
        {
            warning("coersing unsigned short to uint16_t for serialization looses data on this platform");
        }
        uint16_t ui = s;
        WriteUInt16(ui, endian);
    }

    void FileWriter::Write(const int i, arch::Endian endian) const
    {
        if(sizeof(int) > sizeof(int32_t))
        {
            warning("coersing int to int32_t for serialization looses data on this platform");
        }
        int32_t v = i;
        WriteInt32(v, endian);
    }

    void FileWriter::Write(const unsigned int ui, arch::Endian endian) const
    {
        if(sizeof(unsigned int) > sizeof(uint32_t))
        {
            warning("coersing unsigned int to uint32_t for serialization looses data on this platform");
        }
        uint32_t v = ui;
        WriteUInt32(v, endian);
    }

    void FileWriter::Write(const long l, arch::Endian endian) const
    {
        if(sizeof(long) > sizeof(int32_t))
        {
            warning("coersing long to int32_t for serialization looses data on this platform");
        }
        int32_t i = l;
        WriteInt32(i, endian);
    }

    void FileWriter::Write(const unsigned long ul, arch::Endian endian) const
    {
        if(sizeof(unsigned long) > sizeof(uint32_t))
        {
            warning("coersing unsigned long to uint32_t for serialization looses data on this platform");
        }
        uint32_t ui = ul;
        WriteUInt32(ui, endian);
    }

    void FileWriter::Write(const long long ll, arch::Endian endian) const
    {
        if(sizeof(long long) > sizeof(int64_t))
        {
            warning("coersing long long to int64_t for serialization looses data on this platform");
        }
        int64_t i = ll;
        WriteInt64(i, endian);

    }

    void FileWriter::Write(const unsigned long long ull, arch::Endian endian) const
    {
        if(sizeof(unsigned long long) > sizeof(uint64_t))
        {
            warning("coersing unsigned long long to uint64_t for serialization looses data on this platform");
        }
        uint64_t ui = ull;
        WriteUInt64(ui, endian);
    }

    void FileWriter::Write(const float f, arch::Endian endian) const
    {
        if(sizeof(float) > sizeof(uint32_t))
        {
            warning("coersing float to 4 bytes for serialization looses data on this platform. Will use 8 byte type.");
            double d = f;
            Write(d, endian);
        }
        else
        {
            const uint32_t ui = *(reinterpret_cast<const uint32_t*>(&f));
            WriteUInt32(ui, endian);
        }
    }

    void FileWriter::Write(const double d, arch::Endian endian) const
    {
        if(sizeof(double) > sizeof(uint64_t))
        {
            serious("coersing double to 8 bytes for serialization looses data on this platfrom. Output would be corrupt.");
        }
        const uint64_t ui = *(reinterpret_cast<const uint64_t*>(&d));
        WriteUInt64(ui, endian);
    }

}}//qor::platform