// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_GL_PLATFORMIMPL
#define QOR_PP_H_GL_PLATFORMIMPL

#include "src/qor/current/currentthread.h"
#include "src/qor/memory/instance/singleton.h"
#include "src/qor/memory/factory/factory.h"
#include "src/qor/injection/typeidentity.h"
#include "src/qor/memory/factory/externalfactory.h"
#include "src/qor/memory/reference/newref.h"
#include "iplatform.h"

namespace qor{ namespace gl{

    class qor_pp_module_interface(QOR_GL) PlatformImpl : public IPlatform
    {        

    public:

        PlatformImpl() = default;
        virtual ~PlatformImpl() = default;

        //input
        virtual void GetCursorPos(Window*,double*,double*);
        virtual void SetCursorPos(Window*,double,double);
        virtual void SetCursorMode(Window*,int);
        virtual void SetRawMouseMotion(Window*,int);
        virtual bool RawMouseMotionSupported(void);
        virtual int CreateCursor(Cursor*,const Image*,int,int);
        virtual int CreateStandardCursor(Cursor*,int);
        virtual void DestroyCursor(Cursor*);
        virtual void SetCursor(Window*,Cursor*);
        virtual const char* GetScancodeName(int);
        virtual int GetKeyScancode(int);
        virtual void SetClipboardString(const char*);
        virtual const char* GetClipboardString(void);
        virtual int InitJoysticks(void);
        virtual void TerminateJoysticks(void);
        virtual int PollJoystick(Joystick*,int);
        virtual const char* GetMappingName(void);
        virtual void UpdateGamepadGUID(char*);

        //monitor
        virtual void FreeMonitor(Monitor*);
        virtual void GetMonitorPos(Monitor*,int*,int*);
        virtual void GetMonitorContentScale(Monitor*,float*,float*);
        virtual void GetMonitorWorkarea(Monitor*,int*,int*,int*,int*);
        virtual VidMode* GetVideoModes(Monitor*,int*);
        virtual int GetVideoMode(Monitor*,VidMode*);
        virtual int GetGammaRamp(Monitor*,GammaRamp*);
        virtual void SetGammaRamp(Monitor*,const GammaRamp*);

        // window
        virtual int CreateWindow(Window*,const Wndconfig*,const Ctxconfig*,const FBconfig*);
        virtual void DestroyWindow(Window*);
        virtual void SetWindowTitle(Window*,const std::string& title);
        virtual void SetWindowIcon(Window*,int,const Image*);
        virtual void GetWindowPos(Window*,int*,int*);
        virtual void SetWindowPos(Window*,int,int);
        virtual void GetWindowSize(Window*,int*,int*);
        virtual void SetWindowSize(Window*,int,int);
        virtual void SetWindowSizeLimits(Window*,int,int,int,int);
        virtual void SetWindowAspectRatio(Window*,int,int);
        virtual void GetFramebufferSize(Window*,int*,int*);
        virtual void GetWindowFrameSize(Window*,int*,int*,int*,int*);
        virtual void GetWindowContentScale(Window*,float*,float*);
        virtual void IconifyWindow(Window*);
        virtual void RestoreWindow(Window*);
        virtual void MaximizeWindow(Window*);
        virtual void ShowWindow(Window*);
        virtual void HideWindow(Window*);
        virtual void RequestWindowAttention(Window*);
        virtual void FocusWindow(Window*);
        virtual void SetWindowMonitor(Window*, Monitor*,int,int,int,int,int);
        virtual int WindowFocused(Window*);
        virtual int WindowIconified(Window*);
        virtual int WindowVisible(Window*);
        virtual int WindowMaximized(Window*);
        virtual int WindowHovered(Window*);
        virtual bool FramebufferTransparent(Window*);
        virtual float GetWindowOpacity(Window*);
        virtual void SetWindowResizable(Window*,int);
        virtual void SetWindowDecorated(Window*,int);
        virtual void SetWindowFloating(Window*,int);
        virtual void SetWindowOpacity(Window*,float);
        virtual void SetWindowMousePassthrough(Window*,int);
        virtual void PollEvents(void);
        virtual void WaitEvents(void);
        virtual void WaitEventsTimeout(double);
        virtual void PostEmptyEvent(void);
        // EGL
        //virtual EGLenum getEGLPlatform(EGLint**);
        //virtual EGLNativeDisplayType getEGLNativeDisplay(void);
        //virtual EGLNativeWindowType getEGLNativeWindow(Window*);
        // vulkan
        virtual void GetRequiredInstanceExtensions(std::vector<std::string>& extensions);
        //virtual int getPhysicalDevicePresentationSupport(VkInstance,VkPhysicalDevice,uint32_t);
        //virtual VkResult createWindowSurface(VkInstance,Window*,const VkAllocationCallbacks*,VkSurfaceKHR*);

        virtual void PlatformInitTimer(void);
        virtual uint64_t PlatformGetTimerValue(void);
        virtual uint64_t PlatformGetTimerFrequency(void);
        
        virtual bool PlatformCreateTls(TLS* tls);
        virtual void PlatformDestroyTls(TLS* tls);
        virtual void* PlatformGetTls(TLS* tls);
        virtual void PlatformSetTls(TLS* tls, void* value);
        /*
        virtual bool PlatformCreateMutex(RecursiveMutex* mutex);
        virtual void PlatformDestroyMutex(RecursiveMutex* mutex);
        virtual void PlatformLockMutex(RecursiveMutex* mutex);
        virtual void PlatformUnlockMutex(RecursiveMutex* mutex);

        virtual void* PlatformLoadModule(const char* path);
        virtual void PlatformFreeModule(void* module);
        virtual proc PlatformGetModuleSymbol(void* module, const char* name);*/

    protected:

        virtual int Init(void);
        virtual void Terminate(void);

    };

    }
    
    qor_pp_declare_factory_of(gl::PlatformImpl, ExternalFactory);
    constexpr GUID PlatformImplGUID = {0x4D4C1691, 0xF2C2, 0x4C95, {0xA6, 0x7A, 0x6F, 0x4D, 0x63, 0x16, 0x94, 0x30}};
    qor_pp_declare_guid_of(gl::PlatformImpl,PlatformImplGUID);

}//qor::gl

#endif//QOR_PP_H_GL_PLATFORMIMPL
