// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_FRAMEWORK_ASYNCIOSERVICE_ASYNCIOEVENTPROCESSOR
#define QOR_PP_H_FRAMEWORK_ASYNCIOSERVICE_ASYNCIOEVENTPROCESSOR
 
#include "src/qor/essentials/datastructures/guid.h"
#include "src/qor/essentials/current/currentthread.h"
#include "src/qor/flyers/interception/functioncontext.h"
#include "src/qor/memory/factory/factory.h"
#include "src/qor/memory/injection/typeidentity.h"
#include "src/qor/memory/factory/externalfactory.h"
#include "src/framework/parallel/sync/asyncmanualresetevent.h"
#include "src/framework/parallel/task/task.h"
#include "src/framework/parallel/task/syncwait.h"
#include "src/framework/io/iodescriptor.h"
#include "src/qor/flyers/error/error.h"

namespace qor { namespace async{
  
    class qor_pp_module_interface(QOR_ASYNCIOSERVICE) AsyncIOEventProcessor
    {
    public:

        AsyncIOEventProcessor() : 
        m_freeRun(false),
        m_StopRequested(false){ }
        
        virtual ~AsyncIOEventProcessor() noexcept = default;

        virtual int Run();
        virtual void Stop() { m_StopRequested = true; }
        virtual void Reset() { m_StopRequested = false;}

        virtual bool Enroll(io::IODescriptor& /*ioDescriptor*/) const {return false;}

    protected:

        virtual int Event(){return 0;};
        bool m_freeRun;
        bool m_StopRequested;
    };

    }//async

    qor_pp_declare_factory_of(async::AsyncIOEventProcessor, ExternalFactory);    
    constexpr GUID AsyncIOEventProcessorGUID = {0xe92b1e2d, 0x2295, 0x4f5e, {0xb0, 0xba, 0xea, 0xb9, 0x97, 0x27, 0xb5, 0x22}};
    qor_pp_declare_guid_of(async::AsyncIOEventProcessor,AsyncIOEventProcessorGUID);

}//qor

#endif//QOR_PP_H_FRAMEWORK_ASYNCIOSERVICE_ASYNCIOEVENTPROCESSOR
