// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "src/configuration/configuration.h"
#include "src/framework/gl/input/input.h"

#include <windows.h>
#include <dwmapi.h>
#include <Xinput.h>
// GL uses DirectInput8 interfaces
#define DIRECTINPUT_VERSION 0x0800
#include <dinput.h>

#include "session.h"
#include "platform.h"
#include "monitor.h"
#include "joystick.h"
#include "window.h"

namespace qor{ namespace framework{ namespace win{ namespace gl {

    //input
    void Platform::GetCursorPos(qor::gl::Window* window, double* xpos, double* ypos)
    {

    }

    void Platform::SetCursorPos(qor::gl::Window*,double,double)
    {

    }

    void Platform::SetCursorMode(qor::gl::Window* window ,int)
    {

    }
    
    void Platform::SetRawMouseMotion(qor::gl::Window* window, int)
    {

    }

    bool Platform::RawMouseMotionSupported(void)
    {
        return false;
    }

    int Platform::CreateCursor(qor::gl::Cursor* cursor, const qor::gl::Image* image, int, int)
    {
        return 0;
    }
    
    int Platform::CreateStandardCursor(qor::gl::Cursor* cursor,int)
    {
        return 0;
    }

    void Platform::DestroyCursor(qor::gl::Cursor* cursor)
    {

    }

    void Platform::SetCursor(qor::gl::Window* window, qor::gl::Cursor* cursor)
    {

    }

    const char* Platform::GetScancodeName(int scancode)
    {
        if (scancode < 0 || scancode > (KF_EXTENDED | 0xff))
        {
            qor::gl::Session::InputError(qor::gl::INVALID_VALUE, "Invalid scancode %i", scancode);
            return nullptr;
        }

        const int key = TheSession().keycodes[scancode];

        if (key == qor::gl::KEY_UNKNOWN)
        {
            return nullptr;
        }

        return TheSession().keynames[key];

    }

    int Platform::GetKeyScancode(int key)
    {
        return TheSession().scancodes[key];
    }

    void Platform::SetClipboardString(const char* string)
    {
        int characterCount, tries = 0;
        HANDLE object;
        WCHAR* buffer;

        characterCount = MultiByteToWideChar(CP_UTF8, 0, string, -1, NULL, 0);
        if (!characterCount)
            return;

        object = GlobalAlloc(GMEM_MOVEABLE, characterCount * sizeof(WCHAR));
        if (!object)
        {
            Session::InputErrorWin32(qor::gl::PLATFORM_ERROR, "Win32: Failed to allocate global handle for clipboard");
            return;
        }

        buffer = (WCHAR*)GlobalLock(object);
        if (!buffer)
        {
            Session::InputErrorWin32(qor::gl::PLATFORM_ERROR, "Win32: Failed to lock global handle");
            GlobalFree(object);
            return;
        }

        MultiByteToWideChar(CP_UTF8, 0, string, -1, buffer, characterCount);
        GlobalUnlock(object);

        // NOTE: Retry clipboard opening a few times as some other application may have it
        //       open and also the Windows Clipboard History reads it after each update
        while (!OpenClipboard(TheSession().helperWindowHandle))
        {
            Sleep(1);
            tries++;

            if (tries == 3)
            {
                Session::InputErrorWin32(qor::gl::PLATFORM_ERROR, "Win32: Failed to open clipboard");
                GlobalFree(object);
                return;
            }
        }

        EmptyClipboard();
        SetClipboardData(CF_UNICODETEXT, object);
        CloseClipboard();

    }

    const char* Platform::GetClipboardString(void)
    {
        HANDLE object;
        WCHAR* buffer;
        int tries = 0;

        // NOTE: Retry clipboard opening a few times as some other application may have it
        //       open and also the Windows Clipboard History reads it after each update
        while (!OpenClipboard(TheSession().helperWindowHandle))
        {
            Sleep(1);
            tries++;

            if (tries == 3)
            {
                Session::InputErrorWin32(qor::gl::PLATFORM_ERROR, "Win32: Failed to open clipboard");
                return NULL;
            }
        }

        object = GetClipboardData(CF_UNICODETEXT);
        if (!object)
        {
            Session::InputErrorWin32(qor::gl::FORMAT_UNAVAILABLE, "Win32: Failed to convert clipboard to string");
            CloseClipboard();
            return NULL;
        }

        buffer = (WCHAR*)GlobalLock(object);
        if (!buffer)
        {
            Session::InputErrorWin32(qor::gl::PLATFORM_ERROR, "Win32: Failed to lock global handle");
            CloseClipboard();
            return NULL;
        }

        qor::gl::Session::free(TheSession().clipboardString);
        TheSession().clipboardString = Session::CreateUTF8FromWideStringWin32(buffer);

        GlobalUnlock(object);
        CloseClipboard();

        return TheSession().clipboardString;

    }

    int Platform::InitJoysticks(void)
    {
        if (TheSession().dinput8.instance)
        {
            if (FAILED(DirectInput8Create(TheSession().instance,
                                        DIRECTINPUT_VERSION,
                                        IID_IDirectInput8W,
                                        (void**) &TheSession().dinput8.api,
                                        NULL)))
            {
                qor::gl::Session::InputError(qor::gl::PLATFORM_ERROR, "Win32: Failed to create interface");
                return false;
            }
        }

        DetectJoystickConnectionWin32();
        return true;
    }

    void Platform::TerminateJoysticks(void)
    {
        int jid;

        for (jid = qor::gl::Joystick::JOYSTICK_1;  jid <= qor::gl::Joystick::JOYSTICK_LAST;  jid++)
        {
            //TODO:delete TheSession().joysticks[jid];
        }

        if (TheSession().dinput8.api)
        {
            IDirectInput8_Release(TheSession().dinput8.api);
        }
    }

    int Platform::PollJoystick(qor::gl::Joystick* joystick, int mode)
    {
        joystickWin32* js = dynamic_cast<joystickWin32*>(joystick);

        if (js->device)
        {
            int i, ai = 0, bi = 0, pi = 0;
            HRESULT result;
            DIJOYSTATE state = {0};

            IDirectInputDevice8_Poll(js->device);
            result = IDirectInputDevice8_GetDeviceState(js->device, sizeof(state), &state);
            if (result == DIERR_NOTACQUIRED || result == DIERR_INPUTLOST)
            {
                IDirectInputDevice8_Acquire(js->device);
                IDirectInputDevice8_Poll(js->device);
                result = IDirectInputDevice8_GetDeviceState(js->device, sizeof(state), &state);
            }

            if (FAILED(result))
            {
                delete js;
                return false;
            }

            if (mode == qor::gl::POLL_PRESENCE)
                return true;

            for (i = 0;  i < js->objectCount;  i++)
            {
                const void* data = (char*) &state + js->objects[i].offset;

                switch (js->objects[i].type)
                {
                    case TYPE_AXIS:
                    case TYPE_SLIDER:
                    {
                        const float value = (*((LONG*) data) + 0.5f) / 32767.5f;
                        qor::gl::Input::InputJoystickAxis(js, ai, value);
                        ai++;
                        break;
                    }

                    case TYPE_BUTTON:
                    {
                        const char value = (*((BYTE*) data) & 0x80) != 0;
                        qor::gl::Input::InputJoystickButton(js, bi, value);
                        bi++;
                        break;
                    }

                    case TYPE_POV:
                    {
                        const int states[9] =
                        {
                            qor::gl::HAT_UP,
                            qor::gl::HAT_RIGHT_UP,
                            qor::gl::HAT_RIGHT,
                            qor::gl::HAT_RIGHT_DOWN,
                            qor::gl::HAT_DOWN,
                            qor::gl::HAT_LEFT_DOWN,
                            qor::gl::HAT_LEFT,
                            qor::gl::HAT_LEFT_UP,
                            qor::gl::HAT_CENTERED
                        };

                        // Screams of horror are appropriate at this point
                        int stateIndex = LOWORD(*(DWORD*) data) / (45 * DI_DEGREES);
                        if (stateIndex < 0 || stateIndex > 8)
                            stateIndex = 8;

                        qor::gl::Input::InputJoystickHat(js, pi, states[stateIndex]);
                        pi++;
                        break;
                    }
                }
            }
        }
        else
        {
            int i, dpad = 0;
            DWORD result;
            XINPUT_STATE xis;
            const WORD buttons[10] =
            {
                XINPUT_GAMEPAD_A,
                XINPUT_GAMEPAD_B,
                XINPUT_GAMEPAD_X,
                XINPUT_GAMEPAD_Y,
                XINPUT_GAMEPAD_LEFT_SHOULDER,
                XINPUT_GAMEPAD_RIGHT_SHOULDER,
                XINPUT_GAMEPAD_BACK,
                XINPUT_GAMEPAD_START,
                XINPUT_GAMEPAD_LEFT_THUMB,
                XINPUT_GAMEPAD_RIGHT_THUMB
            };

            result = XInputGetState(js->index, &xis);
            if (result != ERROR_SUCCESS)
            {
                if (result == ERROR_DEVICE_NOT_CONNECTED)
                {
                    delete js;
                }

                return false;
            }

            if (mode == qor::gl::POLL_PRESENCE)
            {
                return true;
            }

            qor::gl::Input::InputJoystickAxis(js, 0, (xis.Gamepad.sThumbLX + 0.5f) / 32767.5f);
            qor::gl::Input::InputJoystickAxis(js, 1, -(xis.Gamepad.sThumbLY + 0.5f) / 32767.5f);
            qor::gl::Input::InputJoystickAxis(js, 2, (xis.Gamepad.sThumbRX + 0.5f) / 32767.5f);
            qor::gl::Input::InputJoystickAxis(js, 3, -(xis.Gamepad.sThumbRY + 0.5f) / 32767.5f);
            qor::gl::Input::InputJoystickAxis(js, 4, xis.Gamepad.bLeftTrigger / 127.5f - 1.f);
            qor::gl::Input::InputJoystickAxis(js, 5, xis.Gamepad.bRightTrigger / 127.5f - 1.f);

            for (i = 0;  i < 10;  i++)
            {
                const char value = (xis.Gamepad.wButtons & buttons[i]) ? 1 : 0;
                qor::gl::Input::InputJoystickButton(js, i, value);
            }

            if (xis.Gamepad.wButtons & XINPUT_GAMEPAD_DPAD_UP)
                dpad |= qor::gl::HAT_UP;
            if (xis.Gamepad.wButtons & XINPUT_GAMEPAD_DPAD_RIGHT)
                dpad |= qor::gl::HAT_RIGHT;
            if (xis.Gamepad.wButtons & XINPUT_GAMEPAD_DPAD_DOWN)
                dpad |= qor::gl::HAT_DOWN;
            if (xis.Gamepad.wButtons & XINPUT_GAMEPAD_DPAD_LEFT)
                dpad |= qor::gl::HAT_LEFT;

            // Treat invalid combinations as neither being pressed
            // while preserving what data can be preserved
            if ((dpad & qor::gl::HAT_RIGHT) && (dpad & qor::gl::HAT_LEFT))
                dpad &= ~(qor::gl::HAT_RIGHT | qor::gl::HAT_LEFT);
            if ((dpad & qor::gl::HAT_UP) && (dpad & qor::gl::HAT_DOWN))
                dpad &= ~(qor::gl::HAT_UP | qor::gl::HAT_DOWN);

            qor::gl::Input::InputJoystickHat(js, 0, dpad);
        }

        return true;
    }

    const char* Platform::GetMappingName(void)
    {
        return "Windows";
    }

    void Platform::UpdateGamepadGUID(char* guid)
    {
        if (strcmp(guid + 20, "504944564944") == 0)
        {
            char original[33];
            strncpy(original, guid, sizeof(original) - 1);
            sprintf(guid, "03000000%.4s0000%.4s000000000000",
                    original, original + 4);
        }
    }


    //monitor

    void Platform::FreeMonitor(qor::gl::Monitor* monitor)
    {
    }

    void Platform::GetMonitorPos(qor::gl::Monitor* monitor, int* xpos, int* ypos)
    {
        (dynamic_cast<Monitor*>(monitor))->GetPos(xpos,ypos);
    }

    void Platform::GetMonitorContentScale(qor::gl::Monitor* monitor, float* xscale, float* yscale)
    {
        (dynamic_cast<Monitor*>(monitor))->GetContentScale(xscale, yscale);
    }

    void Platform::GetMonitorWorkarea(qor::gl::Monitor* monitor, int* xpos, int* ypos, int* width, int* height)
    {
        (dynamic_cast<Monitor*>(monitor))->GetWorkarea(xpos, ypos, width, height);
    }

    qor::gl::VidMode* Platform::GetVideoModes(qor::gl::Monitor* monitor, int* count)
    {
        return (dynamic_cast<Monitor*>(monitor))->GetVideoModes(count);
    }

    int Platform::GetVideoMode(qor::gl::Monitor* monitor, qor::gl::VidMode* mode)
    {
        return (dynamic_cast<Monitor*>(monitor))->GetVideoMode(mode);
    }

    int Platform::GetGammaRamp(qor::gl::Monitor* monitor, qor::gl::GammaRamp* ramp)
    {
        return (dynamic_cast<Monitor*>(monitor))->GetGammaRamp(ramp);
    }

    void Platform::SetGammaRamp(qor::gl::Monitor* monitor, const qor::gl::GammaRamp* ramp)
    {
        (dynamic_cast<Monitor*>(monitor))->SetGammaRamp(ramp);
    }

    #undef CreateWindow

    // window
    int Platform::CreateWindow(qor::gl::Window* window, const qor::gl::Wndconfig* wndConfig, const qor::gl::Ctxconfig* ctxConfig, const qor::gl::FBconfig* fbConfig)
    {
        return 0;        
    }

    void Platform::DestroyWindow(qor::gl::Window* window)
    {
        
    }

    void Platform::SetWindowTitle(qor::gl::Window* window, const std::string& title)
    {
        
    }

    void Platform::SetWindowIcon(qor::gl::Window* window,int,const qor::gl::Image*)
    {
        
    }

    void Platform::GetWindowPos(qor::gl::Window* window,int*,int*)
    {
        
    }

    void Platform::SetWindowPos(qor::gl::Window*,int,int)
    {
        
    }

    void Platform::GetWindowSize(qor::gl::Window*,int*,int*)
    {
        
    }

    void Platform::SetWindowSize(qor::gl::Window*,int,int)
    {
        
    }

    void Platform::SetWindowSizeLimits(qor::gl::Window*,int,int,int,int)
    {
        
    }

    void Platform::SetWindowAspectRatio(qor::gl::Window*,int,int)
    {
        
    }

    void Platform::GetFramebufferSize(qor::gl::Window*,int*,int*)
    {
        
    }

    void Platform::GetWindowFrameSize(qor::gl::Window*,int*,int*,int*,int*)
    {
        
    }

    void Platform::GetWindowContentScale(qor::gl::Window*,float*,float*)
    {
        
    }

    void Platform::IconifyWindow(qor::gl::Window*)
    {
        
    }

    void Platform::RestoreWindow(qor::gl::Window*)
    {
        
    }

    void Platform::MaximizeWindow(qor::gl::Window*)
    {
        
    }

    void Platform::ShowWindow(qor::gl::Window*)
    {
        
    }

    void Platform::HideWindow(qor::gl::Window*)
    {
        
    }

    void Platform::RequestWindowAttention(qor::gl::Window*)
    {
        
    }

    void Platform::FocusWindow(qor::gl::Window*)
    {
        
    }

    void Platform::SetWindowMonitor(qor::gl::Window*, qor::gl::Monitor*,int,int,int,int,int)
    {
        
    }

    int Platform::WindowFocused(qor::gl::Window*)
    {
        return 0;        
    }

    int Platform::WindowIconified(qor::gl::Window*)
    {
        return 0;        
    }

    int Platform::WindowVisible(qor::gl::Window*)
    {
        return 0;        
    }

    int Platform::WindowMaximized(qor::gl::Window*)
    {
        return 0;        
    }

    int Platform::WindowHovered(qor::gl::Window*)
    {
        return 0;        
    }

    bool Platform::FramebufferTransparent(qor::gl::Window*)
    {
        return false;
    }

    float Platform::GetWindowOpacity(qor::gl::Window*)
    {
        return 0.0;        
    }

    void Platform::SetWindowResizable(qor::gl::Window*,int)
    {
        
    }

    void Platform::SetWindowDecorated(qor::gl::Window*,int)
    {
        
    }

    void Platform::SetWindowFloating(qor::gl::Window*,int)
    {
        
    }

    void Platform::SetWindowOpacity(qor::gl::Window*,float)
    {
        
    }

    void Platform::SetWindowMousePassthrough(qor::gl::Window*,int)
    {
        
    }

    void Platform::PollEvents(void)
    {
        
    }

    void Platform::WaitEvents(void)
    {
        ::WaitMessage();

        Window::PollEvents();        
    }

    void Platform::WaitEventsTimeout(double timeout)
    {
        ::MsgWaitForMultipleObjects(0, NULL, FALSE, (DWORD) (timeout * 1e3), QS_ALLINPUT);

        Window::PollEvents();        
    }

    void Platform::PostEmptyEvent(void)
    {
        ::PostMessageW(TheSession().helperWindowHandle, WM_NULL, 0, 0);
    }


    void Platform::GetRequiredInstanceExtensions(std::vector<std::string>& extensions)
    {
        if (!TheSession().vk.KHR_surface || !TheSession().vk.KHR_win32_surface)
            return;

        extensions.emplace_back(std::string("VK_KHR_surface"));
        extensions.emplace_back(std::string("VK_KHR_win32_surface"));

    }

    void Platform::PlatformInitTimer(void)
    {
        QueryPerformanceFrequency((LARGE_INTEGER*) &TheSession().timer.frequency);
    }

    uint64_t Platform::PlatformGetTimerValue(void)
    {
        uint64_t value;
        ::QueryPerformanceCounter((LARGE_INTEGER*) &value);
        return value;
    }

    uint64_t Platform::PlatformGetTimerFrequency(void)
    {
        return TheSession().timer.frequency;
    }

}}}}