// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef QOR_PP_H_WINDOWS_GUI_ACCELERATORTABLE
#define QOR_PP_H_WINDOWS_GUI_ACCELERATORTABLE

#include <vector>
#include <string>
#include "src/platform/os/windows/common/handles/handle.h"

//All types on this interface must be portable
namespace qor{ namespace platform { namespace nswindows{ 

    struct qor_pp_module_interface(QOR_WINGUI) Accel
    {
#ifndef _MAC
        unsigned char fVirt;
        unsigned short key;
        unsigned short cmd;
#else
        unsigned short fVirt;
        unsigned short key;
        unsigned long cmd;
#endif
    };

    class qor_pp_module_interface(QOR_WINGUI) Window;
    
    class qor_pp_module_interface(QOR_WINGUI) AcceleratorTable
    {
    public:

        AcceleratorTable();
        AcceleratorTable(const PrimitiveHandle& h);
        AcceleratorTable(std::vector<Accel>& accels);
        AcceleratorTable(void* hInstance, const std::string& tableName);
        virtual ~AcceleratorTable();

        const Handle& GetHandle() const;
        int Copy(Accel* lpAccelDst, int cAccelEntries);
        int Translate(Window& wnd, Message& msg);

    protected:

        bool m_temporary;
        Handle m_handle;
    };
    
}}}//qor::platform::nswindows

#endif//QOR_PP_H_WINDOWS_GUI_ACCELERATORTABLE