// Copyright Querysoft Limited 2008 - 2025
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "../../configuration/configuration.h"
#include "src/platform/compiler/compiler.h"
#include "module.h"

namespace qor{
	qor_pp_import Module* TheHost();
}
/*We'll get a linker warning when, and only when, we link this file into qor_host which implements TheHost
In every other case linking in this library will make the module import TheHost from qor_host. The warning is
harmless so we supress in, in the qor_host build only.*/

namespace qor{
	
    Module::Module(const char* name, const char* version, bool doRegister) : Library(name, version, false)
	{
		if(doRegister)
		{
			Module* host = TheHost();
			host->RegisterModule(this);
		}
	}
	
	Module::~Module() noexcept
	{
		Module* host = TheHost();
		host->UnregisterModule(this);
	}

	bool Module::RegisterLibrary(Library* library)
	{
		if (library)
		{
			if (m_StaticLibraryList == nullptr)
			{
				m_StaticLibraryList = library;
			}
			else
			{
				m_StaticLibraryList->Append(library);
			}
		}
		return library != nullptr;
	}
	
	void Module::UnregisterLibrary(Library* library)
	{
		Library* search = m_StaticLibraryList;
		if (search == library)
		{
			m_StaticLibraryList = const_cast<Library*>(library->Next());
		}
		else
		{
			while (search != nullptr)
			{
				if (search->Next() == library)
				{
					search->SetNext(library->Next());
				}
                else
                {
                    search = const_cast<Library*>(search->Next());
                }
			}
		}
	}

	void Module::RegisterModule(Module*){ }

	void Module::UnregisterModule(Module*){ }

    ModuleRegistry* Module::Modules()
    {
        return m_ModuleReg;
    }

}//qor
